package init

import (
	"bytes"
	"os/exec"
	"strings"
	"testing"

	"github.com/atomicobject/rhizome/pkg/vault/ignore"
	"github.com/atomicobject/rhizome/pkg/vault/obsidian"
	"github.com/stretchr/testify/require"
)

// bulkyRepo returns a Git repository with content worth skipping, content
// worth keeping, an already-ignored vendor/ folder, and an untracked large
// file. Everything except the untracked file is staged.
func bulkyRepo(t *testing.T) string {
	t.Helper()
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git is not installed")
	}
	root := firstRunRepo(t)
	large := strings.Repeat("# big\n", 400_000) // about 2.4 MB
	for rel, content := range map[string]string{
		"third_party/lib/a.go": "package lib\n",
		"third_party/lib/b.go": "package lib\n",
		"web/app.min.js":       "var a=1;\n",
		"api/service.pb.go":    "package api\n",
		"pkg/gen.go":           "// Code generated by stringer. DO NOT EDIT.\npackage pkg\n",
		"pkg/real.go":          "package pkg\n",
		"docs/export.md":       large,
		"data/dump.json":       large,
		"vendor/dep/x.go":      "package dep\n",
		"pkg/testdata/case.md": "# Golden case\n",
	} {
		writeFixtureFile(t, root, rel, content)
	}
	git := func(args ...string) {
		cmd := exec.Command("git", args...)
		cmd.Dir = root
		out, err := cmd.CombinedOutput()
		require.NoError(t, err, string(out))
	}
	git("init", "-q")
	git("add", "-A")
	writeFixtureFile(t, root, "notes/untracked.md", large)
	return root
}

func TestDetectSkipsProposesOnlyTrackedBulkyIndexableContent(t *testing.T) {
	root := bulkyRepo(t)
	layout, err := DetectLayout(root)
	require.NoError(t, err)

	skips := detectSkips(root, obsidian.LocalVaultConfig{}, layout.Code.Files, nil)

	require.Equal(t, []skip{
		{path: "pkg/testdata/", reason: reasonFixtures, files: 1},
		{path: "third_party/", reason: reasonVendored, files: 2},
		{path: "api/service.pb.go", reason: reasonGenCode},
		{path: "docs/export.md", reason: "large file, 2 MB"},
		{path: "pkg/gen.go", reason: reasonGenCode},
		{path: "web/app.min.js", reason: reasonBundled},
	}, skips)
	require.Equal(t, "pkg/testdata/ (1 file), third_party/ (2 files), 2 generated files, docs/export.md (large file, 2 MB), and web/app.min.js (minified or bundled)", skipSummary(skips))

	kept := detectSkips(root, obsidian.LocalVaultConfig{}, layout.Code.Files, map[string]bool{"third_party": true, "docs/export.md": true})
	require.Len(t, kept, 4, "paths marked keep indexed are not proposed")
}

func TestFirstRunWritesSuggestedSkipsThatExplainNames(t *testing.T) {
	root := bulkyRepo(t)

	out, err := runInit(t, RunOptions{Dir: root})

	require.NoError(t, err)
	require.Contains(t, out, "third_party/ (2 files)")
	ignoreFile := readIgnoreFile(t, root)
	require.Contains(t, ignoreFile, suggestedSkipsHeader+"\n# "+reasonFixtures+"\n/pkg/testdata/\n# "+reasonVendored+"\n/third_party/\n")
	require.Contains(t, ignoreFile, "# large file, 2 MB\n/docs/export.md\n")
	decision := ignore.LoadUnifiedMatcher(root, nil).Explain("third_party/lib/a.go", false)
	require.True(t, decision.Ignored)
	require.NotNil(t, decision.Rule)
	require.Equal(t, ".rhizome/ignore", decision.Rule.Source)
	require.Equal(t, "/third_party/", decision.Rule.Pattern)

	out, err = runInit(t, RunOptions{Dir: root})
	require.NoError(t, err)
	require.Contains(t, out, "Everything is up to date.", "written skips are not proposed again")
}

func TestRerunProposesNewSkipsAndCheckCountsThem(t *testing.T) {
	root := bulkyRepo(t)
	_, err := runInit(t, RunOptions{Dir: root})
	require.NoError(t, err)
	writeFixtureFile(t, root, "web/vendor.bundle.js", "var b=2;\n")
	cmd := exec.Command("git", "add", "web/vendor.bundle.js")
	cmd.Dir = root
	require.NoError(t, cmd.Run())

	out, err := runInit(t, RunOptions{Dir: root, Check: true})
	require.ErrorIs(t, err, ErrChangesPending)
	require.Contains(t, out, "- Skip web/vendor.bundle.js (minified or bundled)")

	_, err = runInit(t, RunOptions{Dir: root})
	require.NoError(t, err)
	require.Contains(t, readIgnoreFile(t, root), "/web/vendor.bundle.js\n")
}

func TestSettingsStopSkippingIsRemembered(t *testing.T) {
	root := bulkyRepo(t)
	_, err := runInit(t, RunOptions{Dir: root})
	require.NoError(t, err)

	// s opens settings, 1 what gets indexed, 5 stop skipping; Enter leaves
	// settings and Enter applies.
	out, err := runInit(t, RunOptions{Dir: root, Interactive: true, Stdin: bytes.NewBufferString("s\n1\n2\nweb/app.min.js\n\n\n")})

	require.NoError(t, err)
	require.Contains(t, out, "+ Index web/app.min.js again")
	ignoreFile := readIgnoreFile(t, root)
	require.NotContains(t, ignoreFile, "/web/app.min.js\n")
	require.NotContains(t, ignoreFile, "# "+reasonBundled+"\n", "the reason line goes with its entry")
	require.Contains(t, ignoreFile, keepIndexedPrefix+"web/app.min.js\n")

	out, err = runInit(t, RunOptions{Dir: root})
	require.NoError(t, err)
	require.Contains(t, out, "Everything is up to date.")
}

func TestSettingsSkipAPathWritesIt(t *testing.T) {
	root := rerunRepo(t)

	out, err := runInit(t, RunOptions{Dir: root, Interactive: true, Stdin: bytes.NewBufferString("s\n1\n1\n./cmd\n\n\n")})

	require.NoError(t, err)
	require.Contains(t, out, "- Skip cmd/ ("+reasonManual+")")
	require.Contains(t, readIgnoreFile(t, root), "# "+reasonManual+"\n/cmd/\n")
}

func TestSkipPatternEscapesWildcards(t *testing.T) {
	for rel, want := range map[string]string{
		"third_party/":    "/third_party/",
		"docs/[draft].md": `/docs/\[draft].md`,
		"a*b.js":          `/a\*b.js`,
	} {
		require.Equal(t, want, skipPattern(rel))
		require.Equal(t, strings.TrimSuffix(rel, "/"), cleanSkipPath(unescapeSkipPattern(want)))
	}
}
