package ontology

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"

	initdiff "github.com/atomicobject/rhizome/pkg/app/cli/init/diff"
	"github.com/atomicobject/rhizome/pkg/noteformat"
	"github.com/atomicobject/rhizome/pkg/paths"
	"github.com/atomicobject/rhizome/pkg/vault/obsidian"
	"gopkg.in/yaml.v3"
)

type ConflictKind string

const (
	ConflictKindMissingNode       ConflictKind = "MISSING_NODE"
	ConflictKindMissingField      ConflictKind = "MISSING_FIELD"
	ConflictKindCollectionDrift   ConflictKind = "COLLECTION_DRIFT"
	ConflictKindUnsupportedTarget ConflictKind = "UNSUPPORTED_TARGET"
	ConflictKindFieldChanged      ConflictKind = "FIELD_CHANGED"
	ConflictKindSourceChanged     ConflictKind = "SOURCE_CHANGED"
)

type CommitOutcome string

const (
	CommitOutcomeCommitted  CommitOutcome = "committed"
	CommitOutcomeUnchanged  CommitOutcome = "unchanged"
	CommitOutcomeConflicted CommitOutcome = "conflicted"
	CommitOutcomeFailed     CommitOutcome = "failed"
)

// ConflictReport describes one commit-time replay failure for a staged edit.
type ConflictReport struct {
	Kind             ConflictKind `json:"kind"`
	OperationID      string       `json:"operationId,omitempty"`
	NotePath         string       `json:"notePath"`
	NodeRef          string       `json:"nodeRef,omitempty"`
	Field            string       `json:"field,omitempty"`
	ExpectedValue    string       `json:"expectedValue,omitempty"`
	CurrentValue     string       `json:"currentValue,omitempty"`
	CurrentValues    []string     `json:"currentValues,omitempty"`
	CurrentValueKind string       `json:"currentValueKind,omitempty"`
	ProposedValue    string       `json:"proposedValue,omitempty"`
	Message          string       `json:"message"`
}

// FileCommitPlan is the preview payload for one note touched by an edit session.
type FileCommitPlan struct {
	NotePath              string `json:"notePath"`
	BaseFingerprint       string `json:"baseFingerprint"`
	CurrentFingerprint    string `json:"currentFingerprint"`
	UpdatedFingerprint    string `json:"updatedFingerprint"`
	Diff                  string `json:"diff,omitempty"`
	Rebased               bool   `json:"rebased,omitempty"`
	HasMaterialChange     bool   `json:"hasMaterialChange"`
	UpdatedContentPreview string `json:"updatedContentPreview,omitempty"`
}

// CommitPlan previews all per-file text edits generated by a session.
type CommitPlan struct {
	Files []FileCommitPlan `json:"files"`
}

// CommitResult reports whether a staged edit plan was applied and whether replay rebased.
type CommitResult struct {
	Outcome   CommitOutcome    `json:"outcome"`
	Plan      CommitPlan       `json:"plan"`
	Conflicts []ConflictReport `json:"conflicts,omitempty"`
	Warnings  []string         `json:"warnings,omitempty"`
	Applied   bool             `json:"applied"`
	Rebased   bool             `json:"rebased"`
}

// CommitOptions controls how much preview payload replay should produce.
type CommitOptions struct {
	IncludeDiff                  bool
	IncludeUpdatedContentPreview bool
	TransactionID                string
	CompletionArtifact           func(CommitResult) (*CommitCompletionArtifact, error)
	// VaultWriteLeaseHeld is reserved for a caller that already owns this
	// vault's canonical index lock across a larger source-and-index transaction.
	// The edit transaction still acquires its per-note leases.
	VaultWriteLeaseHeld bool
}

// CommitCompletionArtifact is caller-owned evidence published atomically with
// the edited notes. It is used by transports to make commit retries durable.
type CommitCompletionArtifact struct {
	Path    string
	Content []byte
}

type planOptions struct {
	CompareWithDisk              bool
	IncludeDiff                  bool
	IncludeUpdatedContentPreview bool
	CapturePreviewRefLineage     bool
}

// PreviewRefLineage records a canonical staged ref and the preview identity
// produced by applying that field edit within this session replay.
type PreviewRefLineage struct {
	Original NodeRef `json:"original"`
	Preview  NodeRef `json:"preview"`
}

// EditSession stages ontology-aware note edits and replays them into minimal text changes.
// Docs: [[ontology-edit-replay-conflict-contract#^spec-0046-operation-model]].
type EditSession struct {
	vaultDef              obsidian.VaultDefinition
	noteMgr               obsidian.NoteReader
	schema                *Schema
	formats               *noteformat.Runtime
	allowSelectorRecovery bool
	ops                   []editOp
	docs                  map[string]*documentState
}

type editOp interface {
	notePath() string
	apply(*documentState) error
}

type documentState struct {
	notePath                   string
	content                    string
	baseContent                string
	expectedCurrentFingerprint string
	baseSnapshot               *DocumentSnapshot
	schema                     *Schema
	formats                    *noteformat.Runtime
	allowSelectorRecovery      bool
	snapshot                   *DocumentSnapshot
	snapshotFor                string
	captureRefLineage          bool
	refLineage                 []PreviewRefLineage
	invalidRefStructural       map[string]bool
}

func (s *documentState) setContent(content string) {
	if s.content == content {
		return
	}
	s.content = content
	s.snapshot = nil
	s.snapshotFor = ""
}

type setFieldOp struct {
	Ref               NodeRef
	Field             string
	Values            []string
	IsLinks           bool
	RequireScalarList bool
	Unset             bool
	ExpectedValues    []string
	ExpectedValueKind string
	ExpectedCaptured  bool
	RawRootMetadata   bool
}

type addEmbeddedNodeOp struct {
	ParentRef NodeRef
	Field     string
	Heading   string
	Body      string
	BlockID   string
}

type deleteNodeOp struct {
	Ref NodeRef
}

type reorderCollectionOp struct {
	ParentRef        NodeRef
	Field            string
	OrderedFragments []string
}

type setNarrativeOp struct {
	Ref              NodeRef
	Range            ByteRange
	PreviousMarkdown string
	Markdown         string
}

type insertNarrativeOp struct {
	Ref      NodeRef
	Markdown string
}

type ensureBlockIDOp struct {
	Ref     NodeRef
	BlockID string
}

type setBlockIDOp struct {
	Ref     NodeRef
	BlockID string
}

// removeBlockIDOp deletes the `^block-id` anchor (plus its enclosing line) from
// an embedded node. The ref's NodeID/Structural identifies the node; the apply
// path is a no-op when the node carries no anchor.
//
// WHY: SPEC-0023's opt-in orphan cleanup needs a source-preserving way to drop
// anchors that no inbound external reference targets. Reusing setBlockIDOp
// with an empty target was rejected because callers should be able to express
// "remove without replacement" without ambiguity.
// Coderefs: [[linkable-embedded-node-identifiers#^spec-0023-us4]]
type removeBlockIDOp struct {
	Ref NodeRef
}

type rewriteFileOp struct {
	NotePathValue string
	NewContent    string
}

type transformFileOp struct {
	NotePathValue string
	Transform     func(content string) (string, error)
}

// NewEditSession creates a library-first edit session over one vault.
func NewEditSession(vaultDef obsidian.VaultDefinition, noteMgr obsidian.NoteReader, schema *Schema) *EditSession {
	return &EditSession{
		vaultDef: vaultDef,
		noteMgr:  noteMgr,
		schema:   schema,
		docs:     map[string]*documentState{},
	}
}

// NewProviderAwareEditSession creates an edit session that dispatches root
// metadata operations through the configured source-format runtime.
func NewProviderAwareEditSession(vaultDef obsidian.VaultDefinition, noteMgr obsidian.NoteReader, schema *Schema, formats noteformat.Runtime) *EditSession {
	session := NewEditSession(vaultDef, noteMgr, schema)
	session.formats = &formats
	return session
}

// NewIdentifierRepairEditSession creates an edit session that may recover a
// selector-matched type after an identifier grammar change makes the ordinary
// typed projection unresolved. This authority is intentionally limited to a
// reviewed identifier-repair plan; general edit sessions remain fail-closed.
func NewIdentifierRepairEditSession(vaultDef obsidian.VaultDefinition, noteMgr obsidian.NoteReader, schema *Schema) *EditSession {
	session := NewEditSession(vaultDef, noteMgr, schema)
	session.allowSelectorRecovery = true
	return session
}

// RestoreBaseFingerprints seeds note-level base fingerprints for a replayed session.
// This is used when reconstructing a session from a serialized op snapshot after
// process restart: the current disk content becomes the replay base, while the
// restored fingerprint preserves whether the content drifted since the original
// client-backed session state.
func (s *EditSession) RestoreBaseFingerprints(ctx context.Context, fingerprints map[string]string) error {
	if len(fingerprints) == 0 {
		return nil
	}
	for notePath, fingerprint := range fingerprints {
		notePath = strings.TrimSpace(notePath)
		fingerprint = strings.TrimSpace(fingerprint)
		if notePath == "" || fingerprint == "" {
			continue
		}
		snapshot, err := s.loadEditDocumentSnapshot(ctx, notePath)
		if err != nil {
			return err
		}
		baseSnapshot := *snapshot
		baseSnapshot.ContentFingerprint = fingerprint
		s.docs[notePath] = &documentState{
			notePath:              notePath,
			content:               snapshot.Content,
			baseContent:           snapshot.Content,
			baseSnapshot:          &baseSnapshot,
			schema:                s.schema,
			formats:               s.formats,
			allowSelectorRecovery: s.allowSelectorRecovery,
		}
	}
	return nil
}

// LoadNode resolves a node against current on-disk content without staging any edits.
func (s *EditSession) LoadNode(ctx context.Context, ref NodeRef) (*NodeProjection, error) {
	snapshot, err := s.loadEditDocumentSnapshot(ctx, ref.NotePath)
	if err != nil {
		return nil, err
	}
	state := &documentState{notePath: ref.NotePath, content: snapshot.Content, baseContent: snapshot.Content, baseSnapshot: snapshot, schema: s.schema, formats: s.formats}
	if rootOnly, rootErr := state.providerRootOnly(); rootErr != nil {
		return nil, rootErr
	} else if rootOnly {
		if ref.Kind != NodeKindNote || strings.TrimSpace(ref.Fragment) != "" || strings.TrimSpace(ref.NodeID) != "" {
			return nil, fmt.Errorf("%w: provider exposes only the note root", errUnsupportedTarget)
		}
		_, _, projection, projectErr := state.projectProviderRoot(snapshot.Content)
		return projection, projectErr
	}
	projection, err := ProjectNodeFromSnapshot(snapshot, s.schema, ref)
	if err != nil {
		return nil, err
	}
	if s.allowSelectorRecovery && projection.Type == nil && strings.TrimSpace(ref.TypeName) != "" {
		recovered, recoveryErr := ProjectNodeFromSnapshotWithSelectorRecovery(snapshot, s.schema, ref)
		if recoveryErr != nil {
			return nil, recoveryErr
		}
		if recovered.Type == nil {
			return nil, fmt.Errorf("missing selector-matched note projection for %s", ref.String())
		}
		projection = recovered
	}
	return projection, nil
}

// SetScalarField stages a scalar field replacement for the target node.
func (s *EditSession) SetScalarField(ref NodeRef, field string, value string) error {
	return s.stage(setFieldOp{Ref: ref, Field: field, Values: []string{value}})
}

// SetScalarListField stages a scalar-list field replacement for the target node.
func (s *EditSession) SetScalarListField(ref NodeRef, field string, values []string) error {
	return s.stage(setFieldOp{
		Ref: ref, Field: field, Values: append([]string(nil), values...), RequireScalarList: true,
	})
}

// SetInlineField stages an inline field replacement for the target node.
func (s *EditSession) SetInlineField(ref NodeRef, field string, value string) error {
	return s.SetScalarField(ref, field, value)
}

// SetLinkField stages a link field replacement for the target node.
func (s *EditSession) SetLinkField(ref NodeRef, field string, values []string) error {
	return s.stage(setFieldOp{Ref: ref, Field: field, Values: append([]string(nil), values...), IsLinks: true})
}

// UnsetField stages removal of a field value while preserving the distinction
// from an explicitly empty scalar or list.
func (s *EditSession) UnsetField(ref NodeRef, field string) error {
	return s.stage(setFieldOp{Ref: ref, Field: field, Unset: true})
}

// UnsetLinkField stages removal of a link field value while preserving the
// distinction from an explicitly empty link list.
func (s *EditSession) UnsetLinkField(ref NodeRef, field string) error {
	return s.stage(setFieldOp{Ref: ref, Field: field, IsLinks: true, Unset: true})
}

// SetRootMetadataList stages a provider-neutral raw list for canonical root
// metadata such as tags or aliases.
func (s *EditSession) SetRootMetadataList(ref NodeRef, field string, values []string) error {
	return s.stage(setFieldOp{
		Ref: ref, Field: strings.TrimSpace(field), Values: append([]string(nil), values...),
		RawRootMetadata: true, RequireScalarList: true,
	})
}

// UnsetRootMetadataList stages removal of provider-neutral canonical root
// metadata while preserving the distinction from a present empty list.
func (s *EditSession) UnsetRootMetadataList(ref NodeRef, field string) error {
	return s.stage(setFieldOp{
		Ref: ref, Field: strings.TrimSpace(field), RawRootMetadata: true,
		RequireScalarList: true, Unset: true,
	})
}

// SetRootMetadataListWithWitness stages a provider-neutral list while retaining
// the exact value observed by the editor so concurrent metadata changes conflict.
func (s *EditSession) SetRootMetadataListWithWitness(ref NodeRef, field string, values, expected []string, expectedKind string, unset bool) error {
	return s.stage(setFieldOp{
		Ref: ref, Field: strings.TrimSpace(field), Values: append([]string(nil), values...),
		RawRootMetadata: true, RequireScalarList: true, Unset: unset,
		ExpectedValues: append([]string(nil), expected...), ExpectedValueKind: expectedKind, ExpectedCaptured: true,
	})
}

// AddEmbeddedNode stages insertion of a new embedded node into a section collection.
func (s *EditSession) AddEmbeddedNode(parentRef NodeRef, collectionField string, heading string, body string, blockID string) error {
	return s.stage(addEmbeddedNodeOp{
		ParentRef: parentRef,
		Field:     collectionField,
		Heading:   heading,
		Body:      body,
		BlockID:   blockID,
	})
}

// DeleteNode stages removal of one section or embedded node.
func (s *EditSession) DeleteNode(ref NodeRef) error {
	return s.stage(deleteNodeOp{Ref: ref})
}

// ReorderCollection stages a new order for a section-backed collection.
func (s *EditSession) ReorderCollection(parentRef NodeRef, field string, orderedFragments []string) error {
	return s.stage(reorderCollectionOp{
		ParentRef:        parentRef,
		Field:            field,
		OrderedFragments: append([]string(nil), orderedFragments...),
	})
}

// RewriteFile stages a whole-file content replacement for the given note.
// This is the escape hatch for transformations that compute the full updated
// text outside the node-level op model.
func (s *EditSession) RewriteFile(notePath, newContent string) error {
	notePath = strings.TrimSpace(notePath)
	if notePath == "" {
		return fmt.Errorf("rewrite file: notePath is required")
	}
	return s.stage(rewriteFileOp{NotePathValue: notePath, NewContent: newContent})
}

// StageFileTransform stages a function that computes the new file content from
// the current in-plan content at apply time. This lets callers (like validate
// fix appliers) compose with earlier ops on the same file without freezing
// text at stage time. Transforms for different files may run concurrently while
// planning, so callers must make captured state concurrency-safe.
func (s *EditSession) StageFileTransform(notePath string, transform func(content string) (string, error)) error {
	notePath = strings.TrimSpace(notePath)
	if notePath == "" {
		return fmt.Errorf("transform file: notePath is required")
	}
	if transform == nil {
		return fmt.Errorf("transform file: transform is required")
	}
	return s.stage(transformFileOp{NotePathValue: notePath, Transform: transform})
}

// SetNarrative stages a source-preserving markdown replacement for one
// narrative body block within the target node.
func (s *EditSession) SetNarrative(ref NodeRef, rangeStart, rangeEnd int, previousMarkdown, markdown string) error {
	return s.stage(setNarrativeOp{
		Ref:              ref,
		Range:            ByteRange{Start: rangeStart, End: rangeEnd},
		PreviousMarkdown: previousMarkdown,
		Markdown:         markdown,
	})
}

// InsertNarrative inserts the first narrative block at the canonical body
// boundary owned by ref. It fails closed once that node has authored body
// content, allowing the caller to retry through SetNarrative instead.
func (s *EditSession) InsertNarrative(ref NodeRef, markdown string) error {
	if strings.TrimSpace(markdown) == "" {
		return nil
	}
	return s.stage(insertNarrativeOp{Ref: ref, Markdown: strings.TrimRight(markdown, " \t\n")})
}

// EnsureBlockID stages a source-preserving block ID insertion for an embedded node.
func (s *EditSession) EnsureBlockID(ref NodeRef, blockID string) error {
	op := ensureBlockIDOp{
		Ref:     ref,
		BlockID: strings.TrimSpace(strings.TrimPrefix(blockID, "^")),
	}
	for _, existing := range s.ops {
		typed, ok := existing.(ensureBlockIDOp)
		if !ok {
			continue
		}
		if typed.Ref.String() == op.Ref.String() && typed.Ref.NodeID == op.Ref.NodeID && typed.Ref.Structural == op.Ref.Structural && typed.BlockID == op.BlockID {
			return nil
		}
	}
	return s.stage(op)
}

// SetBlockID stages a source-preserving block ID replacement for an embedded node.
func (s *EditSession) SetBlockID(ref NodeRef, blockID string) error {
	return s.stage(setBlockIDOp{
		Ref:     ref,
		BlockID: strings.TrimSpace(strings.TrimPrefix(blockID, "^")),
	})
}

// RemoveBlockID stages a source-preserving deletion of an embedded node's
// `^block-id` anchor. Idempotent: if the node has no anchor the apply is a
// no-op. Coderefs: [[linkable-embedded-node-identifiers#^spec-0023-us4]]
func (s *EditSession) RemoveBlockID(ref NodeRef) error {
	return s.stage(removeBlockIDOp{Ref: ref})
}

func (s *EditSession) stage(op editOp) error {
	if s == nil {
		return fmt.Errorf("edit session is nil")
	}
	canonical, err := canonicalizeEditOp(op)
	if err != nil {
		return err
	}
	s.ops = append(s.ops, canonical)
	return nil
}

// Preview computes the current per-file diff without touching disk.
func (s *EditSession) Preview(ctx context.Context) (CommitPlan, error) {
	plan, _, err := s.plan(ctx, planOptions{IncludeDiff: true, IncludeUpdatedContentPreview: true})
	return plan, err
}

// PreviewWithRefLineage computes the current plan and the uniquely surviving
// field-edit identities produced by this session's own replay. Callers may use
// the lineage only for refs already resolved against this exact preview.
func (s *EditSession) PreviewWithRefLineage(ctx context.Context) (CommitPlan, []PreviewRefLineage, error) {
	plan, states, err := s.plan(ctx, planOptions{
		IncludeDiff:                  true,
		IncludeUpdatedContentPreview: true,
		CapturePreviewRefLineage:     true,
	})
	if err != nil {
		return plan, nil, err
	}
	lineage := make([]PreviewRefLineage, 0)
	for _, state := range states {
		lineage = append(lineage, state.refLineage...)
	}
	return plan, lineage, nil
}

// PreviewCurrent replays staged ops against current disk state without writing files.
// It surfaces safe rebases in the returned plan and reports typed conflicts
// when the underlying file changed in a way that invalidates staged assumptions.
func (s *EditSession) PreviewCurrent(ctx context.Context) (CommitPlan, []ConflictReport, error) {
	plan, _, conflicts, err := s.previewCurrent(ctx, false)
	return plan, conflicts, err
}

// PreviewCurrentWithRefLineage captures uniquely surviving field-edit refs
// during the same current-source replay used to authorize a commit. The caller
// may publish that lineage only after committing this exact plan.
func (s *EditSession) PreviewCurrentWithRefLineage(ctx context.Context) (CommitPlan, []PreviewRefLineage, []ConflictReport, error) {
	return s.previewCurrent(ctx, true)
}

func (s *EditSession) previewCurrent(ctx context.Context, captureLineage bool) (CommitPlan, []PreviewRefLineage, []ConflictReport, error) {
	plan, states, err := s.plan(ctx, planOptions{
		CompareWithDisk: true, IncludeDiff: true, IncludeUpdatedContentPreview: true,
		CapturePreviewRefLineage: captureLineage,
	})
	if err != nil {
		var conflictErr conflictListError
		if AsConflictList(err, &conflictErr) {
			return plan, nil, conflictErr.Conflicts, nil
		}
		return CommitPlan{}, nil, nil, err
	}
	var lineage []PreviewRefLineage
	for _, state := range states {
		lineage = append(lineage, state.refLineage...)
	}
	return plan, lineage, nil, nil
}

// Commit replays staged ops against current disk state and writes files when replay succeeds.
func (s *EditSession) Commit(ctx context.Context) (CommitResult, error) {
	return s.CommitWithOptions(ctx, CommitOptions{IncludeDiff: true, IncludeUpdatedContentPreview: true})
}

// CommitWithOptions replays staged ops against current disk state and writes files when replay succeeds.
func (s *EditSession) CommitWithOptions(ctx context.Context, opts CommitOptions) (CommitResult, error) {
	vaultPaths, err := paths.NewVaultPaths(s.vaultDef.BasePath())
	if err != nil {
		return CommitResult{Outcome: CommitOutcomeFailed}, err
	}
	if err := recoverInterruptedEditWrites(&vaultPaths, opts.VaultWriteLeaseHeld); err != nil {
		return CommitResult{Outcome: CommitOutcomeFailed}, err
	}
	plan, states, err := s.plan(ctx, planOptions{
		CompareWithDisk:              true,
		IncludeDiff:                  opts.IncludeDiff,
		IncludeUpdatedContentPreview: opts.IncludeUpdatedContentPreview,
	})
	if err != nil {
		var conflictErr conflictListError
		if AsConflictList(err, &conflictErr) {
			return CommitResult{
				Outcome:   CommitOutcomeConflicted,
				Plan:      plan,
				Conflicts: conflictErr.Conflicts,
				Applied:   false,
			}, nil
		}
		return CommitResult{}, err
	}
	if !planHasMaterialChange(plan) {
		return CommitResult{
			Outcome: CommitOutcomeUnchanged,
			Plan:    plan,
			Applied: false,
			Rebased: planHasRebased(plan),
		}, nil
	}
	for _, state := range states {
		rootOnly, formatErr := state.providerRootOnly()
		if formatErr != nil {
			return CommitResult{}, formatErr
		}
		if rootOnly {
			return CommitResult{}, fmt.Errorf("provider root metadata saves require the journaled application adapter")
		}
	}
	materialNotePaths := materialNotePathSet(plan)
	for notePath, state := range states {
		if state == nil || !materialNotePaths[notePath] {
			delete(states, notePath)
		}
	}
	committedResult := CommitResult{
		Outcome: CommitOutcomeCommitted,
		Plan:    plan,
		Applied: true,
		Rebased: planHasRebased(plan),
	}
	var completion *CommitCompletionArtifact
	if opts.CompletionArtifact != nil {
		completion, err = opts.CompletionArtifact(committedResult)
		if err != nil {
			return CommitResult{Outcome: CommitOutcomeFailed}, err
		}
	}
	writeErr := writeStatesAtomically(states, &vaultPaths, opts.TransactionID, completion, opts.VaultWriteLeaseHeld)
	if writeErr != nil {
		var warning publicationWarningError
		if errors.As(writeErr, &warning) {
			return CommitResult{
				Outcome:  CommitOutcomeCommitted,
				Plan:     plan,
				Warnings: []string{warning.Error()},
				Applied:  true,
				Rebased:  planHasRebased(plan),
			}, nil
		}
		var writeConflict writeConflictError
		if errors.As(writeErr, &writeConflict) {
			return CommitResult{
				Outcome: CommitOutcomeConflicted,
				Plan:    plan,
				Conflicts: []ConflictReport{{
					Kind:     ConflictKindSourceChanged,
					NotePath: writeConflict.notePath,
					Message:  writeConflict.Error(),
				}},
				Applied: false,
				Rebased: planHasRebased(plan),
			}, nil
		}
		return CommitResult{Outcome: CommitOutcomeFailed}, writeErr
	}
	return committedResult, nil
}

func (s *EditSession) plan(ctx context.Context, opts planOptions) (CommitPlan, map[string]*documentState, error) {
	if err := ctx.Err(); err != nil {
		return CommitPlan{}, nil, err
	}
	if s.noteMgr == nil {
		return CommitPlan{}, nil, fmt.Errorf("note reader is required")
	}
	grouped := make(map[string][]editOp)
	for _, op := range s.ops {
		canonical, err := canonicalizeEditOp(op)
		if err != nil {
			return CommitPlan{}, nil, err
		}
		notePath := canonical.notePath()
		grouped[notePath] = append(grouped[notePath], canonical)
	}
	pathsList := make([]string, 0, len(grouped))
	for notePath := range grouped {
		pathsList = append(pathsList, notePath)
	}
	sort.Strings(pathsList)

	plan := CommitPlan{Files: make([]FileCommitPlan, 0, len(pathsList))}
	states := make(map[string]*documentState, len(pathsList))
	conflicts := make([]ConflictReport, 0)
	jobs := make([]fileEditPlanJob, 0, len(pathsList))

	for index, notePath := range pathsList {
		baseState := s.docs[notePath]
		if baseState == nil {
			// Capture the base snapshot at first replay, not at op staging time.
			// Browser sessions that need restart recovery seed this explicitly via
			// RestoreBaseFingerprints so drift remains visible after restore.
			baseSnapshot, err := s.loadEditDocumentSnapshot(ctx, notePath)
			if err != nil {
				return plan, nil, err
			}
			baseState = &documentState{
				notePath:              notePath,
				content:               baseSnapshot.Content,
				baseContent:           baseSnapshot.Content,
				baseSnapshot:          baseSnapshot,
				schema:                s.schema,
				formats:               s.formats,
				allowSelectorRecovery: s.allowSelectorRecovery,
			}
			s.docs[notePath] = baseState
		}
		var currentSnapshot *DocumentSnapshot
		if opts.CompareWithDisk {
			var err error
			currentSnapshot, err = s.loadEditDocumentSnapshot(ctx, notePath)
			if err != nil {
				return plan, nil, err
			}
		}
		jobs = append(jobs, fileEditPlanJob{
			index:           index,
			notePath:        notePath,
			baseState:       baseState,
			currentSnapshot: currentSnapshot,
			ops:             grouped[notePath],
		})
	}

	results := s.planFiles(jobs, opts)
	for _, result := range results {
		if result.err != nil {
			return plan, nil, result.err
		}
		if result.conflict != nil {
			conflicts = append(conflicts, *result.conflict)
		}
		states[result.notePath] = result.state
		plan.Files = append(plan.Files, result.filePlan)
	}
	if len(conflicts) > 0 {
		return plan, nil, conflictListError{Conflicts: conflicts}
	}
	return plan, states, nil
}

type fileEditPlanJob struct {
	index           int
	notePath        string
	baseState       *documentState
	currentSnapshot *DocumentSnapshot
	ops             []editOp
}

type fileEditPlanResult struct {
	index    int
	notePath string
	state    *documentState
	filePlan FileCommitPlan
	conflict *ConflictReport
	err      error
}

const maxConcurrentFilePlans = 8

func (s *EditSession) planFiles(jobs []fileEditPlanJob, opts planOptions) []fileEditPlanResult {
	results := make([]fileEditPlanResult, len(jobs))
	if len(jobs) == 0 {
		return results
	}
	workerCount := min(len(jobs), maxConcurrentFilePlans)
	work := make(chan fileEditPlanJob)
	var wg sync.WaitGroup
	for range workerCount {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range work {
				results[job.index] = s.planFile(job, opts)
			}
		}()
	}
	for _, job := range jobs {
		work <- job
	}
	close(work)
	wg.Wait()
	return results
}

func (s *EditSession) planFile(job fileEditPlanJob, opts planOptions) fileEditPlanResult {
	result := fileEditPlanResult{
		index:    job.index,
		notePath: job.notePath,
	}
	state := &documentState{
		notePath:              job.notePath,
		content:               job.baseState.baseContent,
		baseContent:           job.baseState.baseContent,
		baseSnapshot:          job.baseState.baseSnapshot,
		schema:                s.schema,
		formats:               s.formats,
		allowSelectorRecovery: s.allowSelectorRecovery,
		captureRefLineage:     opts.CapturePreviewRefLineage,
	}
	rebased := false
	currentFingerprint := job.baseState.baseSnapshot.ContentFingerprint
	currentContent := job.baseState.baseContent
	if opts.CompareWithDisk {
		if job.currentSnapshot == nil {
			result.err = fmt.Errorf("plan file %s: current snapshot is required when comparing with disk", job.notePath)
			return result
		}
		currentSnapshot := job.currentSnapshot
		currentFingerprint = currentSnapshot.ContentFingerprint
		currentContent = currentSnapshot.Content
		state.expectedCurrentFingerprint = currentFingerprint
		if currentSnapshot.ContentFingerprint != job.baseState.baseSnapshot.ContentFingerprint {
			// IMPORTANT: replay ops against current disk content for commit and
			// PreviewCurrent, but keep the original base fingerprint in the plan
			// so callers can report a safe rebase instead of pretending the file
			// was unchanged.
			state.setContent(currentSnapshot.Content)
			rebased = true
		}
	}
	if opts.CompareWithDisk {
		if conflict := fieldChangedConflict(job.baseState, state, job.ops); conflict != nil {
			result.conflict = conflict
		}
	}
	finish := func() fileEditPlanResult {
		result.state = state
		result.filePlan = FileCommitPlan{
			NotePath:           job.notePath,
			BaseFingerprint:    job.baseState.baseSnapshot.ContentFingerprint,
			CurrentFingerprint: currentFingerprint,
			UpdatedFingerprint: hashText(state.content),
			Rebased:            rebased,
			HasMaterialChange:  state.content != currentContent,
		}
		result.err = populatePlanPayload(&result.filePlan, state, opts)
		return result
	}
	if result.conflict != nil {
		return finish()
	}
	baseNoop := false
	baseReplayNoop := false
	if opts.CompareWithDisk && rebased && !hasExplicitFieldWitness(job.ops) {
		baseReplay := &documentState{
			notePath:              job.notePath,
			content:               job.baseState.baseContent,
			baseContent:           job.baseState.baseContent,
			baseSnapshot:          job.baseState.baseSnapshot,
			schema:                s.schema,
			formats:               s.formats,
			allowSelectorRecovery: s.allowSelectorRecovery,
		}
		baseNoop = true
		for _, op := range job.ops {
			if !editOpMatchesBase(baseReplay, op) {
				baseNoop = false
				break
			}
		}
		baseReplayOK := applyEditOps(baseReplay, job.ops) == nil
		baseReplayNoop = baseReplayOK && baseReplay.content == job.baseState.baseContent
	}
	if opts.CompareWithDisk && rebased && (baseNoop || baseReplayNoop) {
		state.setContent(currentContent)
		return finish()
	}
	if err := applyEditOps(state, job.ops); err != nil {
		conflict := conflictFromError(job.notePath, err.op, err.err)
		result.conflict = &conflict
	}
	return finish()
}

func hasExplicitFieldWitness(ops []editOp) bool {
	for _, rawOp := range ops {
		if op, ok := rawOp.(setFieldOp); ok && op.ExpectedCaptured {
			return true
		}
	}
	return false
}

func populatePlanPayload(filePlan *FileCommitPlan, state *documentState, opts planOptions) error {
	if opts.IncludeDiff {
		diffText, _, err := initdiff.GenerateUnifiedDiff(state.baseContent, state.content, state.notePath)
		if err != nil {
			return err
		}
		filePlan.Diff = diffText
	}
	if opts.IncludeUpdatedContentPreview {
		filePlan.UpdatedContentPreview = state.content
	}
	return nil
}

type editApplyError struct {
	op  editOp
	err error
}

func applyEditOps(state *documentState, ops []editOp) *editApplyError {
	for i := 0; i < len(ops); {
		if _, ok := ops[i].(setFieldOp); ok {
			start := i
			for i < len(ops) {
				if _, ok := ops[i].(setFieldOp); !ok {
					break
				}
				i++
			}
			if err := applySetFieldOps(state, ops[start:i]); err != nil {
				return err
			}
			continue
		}
		if rootOnly, err := state.providerRootOnly(); err != nil {
			return &editApplyError{op: ops[i], err: err}
		} else if rootOnly {
			return &editApplyError{op: ops[i], err: fmt.Errorf("%w: source format permits root metadata edits only", errUnsupportedTarget)}
		}
		if state.captureRefLineage && len(state.refLineage) > 0 {
			// Structural edits after a captured field target can delete, replace,
			// or manufacture an indistinguishable node. Refuse to carry lineage
			// across that boundary without stronger operation-specific evidence.
			state.refLineage = nil
		}
		var beforeStructural map[string]int
		if state.captureRefLineage {
			beforeStructural = documentStructuralCounts(state)
		}
		if err := ops[i].apply(state); err != nil {
			return &editApplyError{op: ops[i], err: err}
		}
		if state.captureRefLineage {
			state.recordStructuralInvalidations(beforeStructural, documentStructuralCounts(state), ops[i])
		}
		i++
	}
	return nil
}

func applySetFieldOps(state *documentState, ops []editOp) *editApplyError {
	if rootOnly, err := state.providerRootOnly(); err != nil {
		return &editApplyError{op: ops[0], err: err}
	} else if rootOnly {
		typed := make([]setFieldOp, len(ops))
		for index, op := range ops {
			typed[index] = op.(setFieldOp)
		}
		failed, applyErr := applyProviderRootFieldOps(state, typed)
		if applyErr != nil {
			if failed == nil {
				failed = ops[0]
			}
			return &editApplyError{op: failed, err: applyErr}
		}
		return nil
	}
	if len(ops) == 1 && !state.captureRefLineage {
		if err := ops[0].apply(state); err != nil {
			return &editApplyError{op: ops[0], err: err}
		}
		return nil
	}
	typed := make([]setFieldOp, 0, len(ops))
	for _, op := range ops {
		typed = append(typed, op.(setFieldOp))
	}
	updated, targets, edits, ok, failedOp, err := tryApplySetFieldOpsBatch(state, typed)
	if err != nil {
		return &editApplyError{op: failedOp, err: err}
	}
	if ok {
		state.setContent(updated)
		if state.captureRefLineage {
			captureFieldRefLineage(state, targets, edits)
		}
		return nil
	}
	bindings := make(map[NodeRef]NodeRef)
	for _, rawOp := range ops {
		original := rawOp.(setFieldOp)
		effective := original
		if rebound, exists := bindings[original.Ref]; exists {
			effective.Ref = rebound
		}
		_, projection, projectionErr := projectState(state, effective.Ref)
		if projectionErr != nil {
			return &editApplyError{op: rawOp, err: projectionErr}
		}
		before := projection.Ref
		if err := effective.apply(state); err != nil {
			return &editApplyError{op: rawOp, err: err}
		}
		preview, ok := fieldReplaySuccessor(state, before)
		if !ok {
			delete(bindings, original.Ref)
			continue
		}
		bindings[original.Ref] = preview
		recordFieldRefLineage(state, original.Ref, preview)
	}
	return nil
}

// fieldReplaySuccessor binds a node only after its original identity resolved
// strictly and this replay changed it. The pre-edit byte position is evidence
// local to that mutation; it is never used to recover an initially stale ref.
func fieldReplaySuccessor(state *documentState, before NodeRef) (NodeRef, bool) {
	snapshot, err := state.documentSnapshot()
	if err != nil {
		return NodeRef{}, false
	}
	resolver, err := newProjectionResolver(snapshot, state.schema)
	if err != nil {
		return NodeRef{}, false
	}
	preview, ok := replayRefAtStart(replayRefsByStart(resolver)[before.StartByte], before.Kind, before.TypeName)
	if !ok || (strings.TrimSpace(preview.Structural) == "" && strings.TrimSpace(preview.NodeID) == "") {
		return NodeRef{}, false
	}
	return preview, true
}

func recordFieldRefLineage(state *documentState, original, preview NodeRef) {
	if state == nil || !state.captureRefLineage || strings.TrimSpace(preview.Structural) == "" {
		return
	}
	if state.invalidRefStructural[strings.TrimSpace(original.Structural)] {
		return
	}
	for i := range state.refLineage {
		if state.refLineage[i].Original == original {
			state.refLineage[i].Preview = preview
			return
		}
	}
	state.refLineage = append(state.refLineage, PreviewRefLineage{Original: original, Preview: preview})
}

type contentEdit struct {
	r           ByteRange
	replacement string
	order       int
}

type fieldReplayTarget struct {
	Original NodeRef
	Before   NodeRef
}

func tryApplySetFieldOpsBatch(state *documentState, ops []setFieldOp) (string, []fieldReplayTarget, []contentEdit, bool, editOp, error) {
	snapshot, err := state.documentSnapshot()
	if err != nil {
		return "", nil, nil, false, ops[0], err
	}
	edits := make([]contentEdit, 0, len(ops))
	var targets []fieldReplayTarget
	if state.captureRefLineage {
		targets = make([]fieldReplayTarget, 0, len(ops))
	}
	for i, op := range ops {
		projection, err := projectSnapshot(snapshot, state.schema, op.Ref, state.allowSelectorRecovery)
		if err != nil {
			return "", nil, nil, false, op, err
		}
		field, err := validateSetFieldOperation(projection, op, state.schema, state.allowSelectorRecovery)
		if err != nil {
			return "", nil, nil, false, op, err
		}
		if op.Unset {
			return "", nil, nil, false, nil, nil
		}
		if state.captureRefLineage {
			targets = append(targets, fieldReplayTarget{Original: op.Ref, Before: projection.Ref})
		}
		opEdits, ok, err := setFieldBatchEdits(snapshot, projection, field, op)
		if err != nil {
			return "", nil, nil, false, op, err
		}
		if !ok {
			return "", nil, nil, false, nil, nil
		}
		for j := range opEdits {
			opEdits[j].order = i
			edits = append(edits, opEdits[j])
		}
	}
	if editsOverlap(edits) {
		return "", nil, nil, false, nil, nil
	}
	sort.SliceStable(edits, func(i, j int) bool {
		if edits[i].r.Start == edits[j].r.Start {
			return edits[i].order > edits[j].order
		}
		return edits[i].r.Start > edits[j].r.Start
	})
	content := snapshot.Content
	for _, edit := range edits {
		content = replaceRange(content, edit.r, edit.replacement)
	}
	return content, targets, edits, true, nil, nil
}

func captureFieldRefLineage(state *documentState, targets []fieldReplayTarget, edits []contentEdit) {
	if state == nil || !state.captureRefLineage || len(targets) == 0 {
		return
	}
	snapshot, err := state.documentSnapshot()
	if err != nil {
		return
	}
	resolver, err := newProjectionResolver(snapshot, state.schema)
	if err != nil {
		return
	}
	refsByStart := replayRefsByStart(resolver)
	starts := shiftedReplayTargetStarts(targets, edits)
	for i, target := range targets {
		if state.invalidRefStructural[strings.TrimSpace(target.Original.Structural)] {
			continue
		}
		preview, ok := replayRefAtStart(refsByStart[starts[i]], target.Before.Kind, target.Before.TypeName)
		if !ok || strings.TrimSpace(preview.Structural) == "" {
			continue
		}
		recordFieldRefLineage(state, target.Original, preview)
	}
}

func documentStructuralCounts(state *documentState) map[string]int {
	out := make(map[string]int)
	if state == nil {
		return out
	}
	snapshot, err := state.documentSnapshot()
	if err != nil {
		return out
	}
	resolver, err := newProjectionResolver(snapshot, state.schema)
	if err != nil {
		return out
	}
	for _, refs := range replayRefsByStart(resolver) {
		for _, ref := range refs {
			if structural := strings.TrimSpace(ref.Structural); structural != "" {
				out[structural]++
			}
		}
	}
	return out
}

func (state *documentState) recordStructuralInvalidations(before, after map[string]int, op editOp) {
	if state.invalidRefStructural == nil {
		state.invalidRefStructural = make(map[string]bool)
	}
	_, rewrite := op.(rewriteFileOp)
	_, transform := op.(transformFileOp)
	for structural, count := range before {
		afterCount := after[structural]
		if count > 0 && (count != 1 || afterCount != 1 || rewrite || transform) {
			state.invalidRefStructural[structural] = true
		}
	}
}

func replayRefsByStart(resolver *projectionResolver) map[int][]NodeRef {
	out := make(map[int][]NodeRef)
	for _, span := range resolver.snapshot.SourceSpans {
		if span == nil || span.Shape == EmbeddedSourceShapeSection {
			continue
		}
		out[span.Range.Start] = append(out[span.Range.Start], resolver.sourceSpanNodeRef(span))
	}
	var walk func([]*SectionNode)
	walk = func(nodes []*SectionNode) {
		for _, node := range nodes {
			if node == nil {
				continue
			}
			out[node.StartByte] = append(out[node.StartByte], resolver.sectionNodeRef(node))
			walk(node.Children)
		}
	}
	walk(resolver.snapshot.Sections)
	return out
}

func replayRefAtStart(refs []NodeRef, kind NodeKind, typeName string) (NodeRef, bool) {
	var found NodeRef
	for _, ref := range refs {
		if ref.Kind != kind || (strings.TrimSpace(typeName) != "" && ref.TypeName != typeName) {
			continue
		}
		if !found.IsZero() {
			return NodeRef{}, false
		}
		found = ref
	}
	return found, !found.IsZero()
}

func shiftedReplayTargetStarts(targets []fieldReplayTarget, edits []contentEdit) []int {
	type editDelta struct {
		end   int
		delta int
	}
	deltas := make([]editDelta, 0, len(edits))
	for _, edit := range edits {
		deltas = append(deltas, editDelta{end: edit.r.End, delta: len(edit.replacement) - edit.r.Len()})
	}
	sort.Slice(deltas, func(i, j int) bool { return deltas[i].end < deltas[j].end })
	order := make([]int, len(targets))
	for i := range targets {
		order[i] = i
	}
	sort.Slice(order, func(i, j int) bool {
		return targets[order[i]].Before.StartByte < targets[order[j]].Before.StartByte
	})
	out := make([]int, len(targets))
	deltaIndex, cumulative := 0, 0
	for _, targetIndex := range order {
		start := targets[targetIndex].Before.StartByte
		for deltaIndex < len(deltas) && deltas[deltaIndex].end <= start {
			cumulative += deltas[deltaIndex].delta
			deltaIndex++
		}
		out[targetIndex] = start + cumulative
	}
	return out
}

func editsOverlap(edits []contentEdit) bool {
	nonEmpty := make([]contentEdit, 0, len(edits))
	for _, edit := range edits {
		if edit.r.Len() == 0 {
			continue
		}
		nonEmpty = append(nonEmpty, edit)
	}
	sort.Slice(nonEmpty, func(i, j int) bool {
		return nonEmpty[i].r.Start < nonEmpty[j].r.Start
	})
	for i := 1; i < len(nonEmpty); i++ {
		if nonEmpty[i].r.Start < nonEmpty[i-1].r.End {
			return true
		}
	}
	return false
}

func setFieldBatchEdits(snapshot *DocumentSnapshot, projection *NodeProjection, field *Field, op setFieldOp) ([]contentEdit, bool, error) {
	if strings.EqualFold(op.Field, "title") {
		return titleBatchEdits(snapshot, projection, op.Values)
	}
	if field.SourceKind == FieldSourceCheckbox {
		return checkboxBatchEdits(snapshot, projection, field, op.Values)
	}
	if projection.Ref.Kind == NodeKindEmbedded && embeddedNodeNeedsBlockID(snapshot, projection) {
		return nil, false, nil
	}
	if field.SourceKind == FieldSourceInline {
		edits, err := inlineFieldEdits(snapshot, projection, field, op.Values)
		return edits, err == nil, err
	}
	return nil, false, nil
}

func titleBatchEdits(snapshot *DocumentSnapshot, projection *NodeProjection, values []string) ([]contentEdit, bool, error) {
	if len(values) != 1 {
		return nil, false, fmt.Errorf("%w: title expects one value", errUnsupportedTarget)
	}
	value := oneLineTitleValue(values[0])
	switch projection.Ref.Kind {
	case NodeKindEmbedded:
		if span := snapshot.SourceSpansByID[projection.Ref.NodeID]; span != nil &&
			(span.Shape == EmbeddedSourceShapeCheckboxItem || span.Shape == EmbeddedSourceShapeListItem) {
			edit, err := sourceSpanTitleEdit(snapshot, span, value)
			if err != nil {
				return nil, false, err
			}
			return []contentEdit{edit}, true, nil
		}
		return nil, false, nil
	default:
		return nil, false, nil
	}
}

func sourceSpanTitleEdit(snapshot *DocumentSnapshot, span *MarkdownSourceSpan, value string) (contentEdit, error) {
	if !span.ContentRange.Valid(len(snapshot.Content)) || span.ContentRange.Len() == 0 {
		return contentEdit{}, fmt.Errorf("%w: invalid title range", errCollectionDrift)
	}
	lineEnd := span.ContentRange.End
	if nextLine := strings.IndexByte(snapshot.Content[span.ContentRange.Start:span.ContentRange.End], '\n'); nextLine >= 0 {
		lineEnd = span.ContentRange.Start + nextLine
	}
	titleEnd := lineEnd
	for _, marker := range span.Markers {
		if marker.Range.Start >= span.ContentRange.Start && marker.Range.Start < titleEnd {
			titleEnd = marker.Range.Start
		}
	}
	for _, inline := range scanInlineFieldsInListSegment(snapshot.Content[span.ContentRange.Start:lineEnd], span.ContentRange.Start) {
		if inline.WholeRange.Start >= span.ContentRange.Start && inline.WholeRange.Start < titleEnd {
			titleEnd = inline.WholeRange.Start
		}
	}
	if tokenStart := trailingListMetadataTokenStart(snapshot.Content[span.ContentRange.Start:lineEnd], 0, lineEnd-span.ContentRange.Start); tokenStart >= 0 {
		absolute := span.ContentRange.Start + tokenStart
		if absolute < titleEnd {
			titleEnd = absolute
		}
	}
	titleEnd = trimSpaceLeftBounded(snapshot.Content, span.ContentRange.Start, titleEnd)
	if titleEnd < lineEnd && value != "" && snapshot.Content[titleEnd] != ' ' && snapshot.Content[titleEnd] != '\t' {
		value += " "
	}
	return contentEdit{r: ByteRange{Start: span.ContentRange.Start, End: titleEnd}, replacement: value}, nil
}

func checkboxBatchEdits(snapshot *DocumentSnapshot, projection *NodeProjection, field *Field, values []string) ([]contentEdit, bool, error) {
	if field.TypeName != "Boolean" || field.List || len(values) != 1 {
		return nil, false, nil
	}
	desired, err := parseCheckboxEditValue(values[0])
	if err != nil {
		return nil, false, err
	}
	span := snapshot.SourceSpansByID[projection.Ref.NodeID]
	if span == nil || span.Shape != EmbeddedSourceShapeCheckboxItem || span.Checkbox == nil {
		return nil, false, nil
	}
	r := span.Checkbox.TokenRange
	if !r.Valid(len(snapshot.Content)) || r.Len() != len("[ ]") {
		return nil, false, fmt.Errorf("%w: invalid checkbox token range for %s", errCollectionDrift, projection.Ref.String())
	}
	if span.Checkbox.Checked == desired {
		return nil, true, nil
	}
	token := "[ ]"
	if desired {
		token = "[x]"
	}
	return []contentEdit{{r: r, replacement: token}}, true, nil
}

func inlineFieldEdits(snapshot *DocumentSnapshot, projection *NodeProjection, field *Field, values []string) ([]contentEdit, error) {
	binding := projection.Fields[field.Name]
	propertyName := DefaultPropertyName(field.Name, projection.PropertyCase)
	lineText := propertyName + ":: " + strings.Join(values, ", ")
	if len(binding.InlineSpans) > 0 {
		edits := make([]contentEdit, 0, len(binding.InlineSpans))
		first := binding.InlineSpans[0]
		editRange := inlineFieldEditRange(snapshot.Content, first)
		replacement := inlineFieldReplacementPrefix(snapshot.Content, first) + lineText
		if editRange != first.LineRange {
			replacement = lineText
		} else if rangeStartsLine(snapshot.Content, first.LineRange.Start) {
			replacement += "\n"
		}
		edits = append(edits, contentEdit{r: editRange, replacement: replacement})
		for i := 1; i < len(binding.InlineSpans); i++ {
			edits = append(edits, contentEdit{r: inlineFieldEditRange(snapshot.Content, binding.InlineSpans[i])})
		}
		return edits, nil
	}
	insertAt := inlineInsertOffset(snapshot, projection)
	if insertAt < 0 || insertAt > len(snapshot.Content) {
		return nil, fmt.Errorf("%w: invalid inline insert offset for %s", errUnsupportedTarget, field.Name)
	}
	prefix := ""
	if insertAt > 0 && snapshot.Content[insertAt-1] != '\n' {
		prefix = "\n"
	}
	return []contentEdit{{r: ByteRange{Start: insertAt, End: insertAt}, replacement: prefix + lineText + "\n"}}, nil
}

func editOpMatchesBase(state *documentState, op editOp) bool {
	switch typed := op.(type) {
	case setFieldOp:
		return setFieldOpMatchesBase(state, typed)
	case reorderCollectionOp:
		return reorderCollectionOpMatchesBase(state, typed)
	default:
		return false
	}
}

func setFieldOpMatchesBase(state *documentState, op setFieldOp) bool {
	if state == nil {
		return false
	}
	rootOnly, err := state.providerRootOnly()
	if err != nil {
		return false
	}
	if op.RawRootMetadata || (rootOnly && op.Ref.Kind == NodeKindNote && strings.TrimSpace(op.Ref.Fragment) == "" && strings.TrimSpace(op.Ref.NodeID) == "") {
		values, kind, err := fieldValueForReplay(state, op)
		if err != nil {
			return false
		}
		return equalEditFieldValue(kind, values, fieldValueKindForOp(op), op.Values)
	}
	_, projection, err := projectState(state, op.Ref)
	if err != nil || projection == nil {
		return false
	}
	if strings.EqualFold(op.Field, "title") {
		return len(op.Values) == 1 && oneLineTitleValue(op.Values[0]) == projectedNodeTitle(projection)
	}
	binding, ok := projection.Fields[op.Field]
	if !ok {
		return false
	}
	if op.Unset {
		return !binding.Present
	}
	if !binding.Present {
		return false
	}
	if len(op.Values) != len(binding.Values) {
		return false
	}
	for i := range op.Values {
		if op.Values[i] != binding.Values[i] {
			return false
		}
	}
	return true
}

func fieldChangedConflict(baseState, currentState *documentState, ops []editOp) *ConflictReport {
	if baseState == nil || currentState == nil || len(ops) == 0 {
		return nil
	}
	for _, rawOp := range ops {
		op, ok := rawOp.(setFieldOp)
		if !ok {
			continue
		}
		expected := append([]string(nil), op.ExpectedValues...)
		expectedKind := op.ExpectedValueKind
		if !op.ExpectedCaptured {
			var err error
			expected, expectedKind, err = fieldValueForReplay(baseState, op)
			if err != nil {
				continue
			}
		}
		if !op.ExpectedCaptured && equalEditFieldValue(expectedKind, expected, fieldValueKindForOp(op), op.Values) {
			continue
		}
		current, currentKind, err := fieldValueForReplay(currentState, op)
		if err != nil || equalEditFieldValue(expectedKind, expected, currentKind, current) {
			continue
		}
		return &ConflictReport{
			Kind:             ConflictKindFieldChanged,
			NotePath:         op.Ref.NotePath,
			NodeRef:          op.Ref.String(),
			Field:            op.Field,
			ExpectedValue:    formatEditValues(expected),
			CurrentValue:     formatEditValues(current),
			CurrentValues:    append([]string(nil), current...),
			CurrentValueKind: currentKind,
			ProposedValue:    formatEditValues(op.Values),
			Message: fmt.Sprintf(
				"field %s changed: expected %q, current %q, proposed %q",
				op.Field,
				formatEditValues(expected),
				formatEditValues(current),
				formatEditValues(op.Values),
			),
		}
	}
	return nil
}

func fieldValueForReplay(state *documentState, op setFieldOp) ([]string, string, error) {
	rootOnly, err := state.providerRootOnly()
	if err != nil {
		return nil, "", err
	}
	if op.RawRootMetadata || (rootOnly && op.Ref.Kind == NodeKindNote && strings.TrimSpace(op.Ref.Fragment) == "" && strings.TrimSpace(op.Ref.NodeID) == "") {
		return providerRootFieldValueForReplay(state, op)
	}
	_, projection, err := projectState(state, op.Ref)
	if err != nil {
		return nil, "", err
	}
	if strings.EqualFold(op.Field, "title") {
		return []string{projectedNodeTitle(projection)}, "scalar", nil
	}
	if projection == nil || projection.Type == nil {
		return nil, "", fmt.Errorf("%w: node type is required", errMissingNode)
	}
	binding, ok := projection.Fields[op.Field]
	if !ok {
		return nil, "", fmt.Errorf("%w: field %s not found", errMissingField, op.Field)
	}
	if !binding.Present {
		return nil, "unset", nil
	}
	kind := "scalar"
	if op.IsLinks || op.RequireScalarList {
		kind = "list"
	}
	values := append([]string(nil), binding.Values...)
	if kind == "scalar" && len(values) == 0 {
		values = []string{""}
	}
	return values, kind, nil
}

func fieldValueKindForOp(op setFieldOp) string {
	if op.Unset {
		return "unset"
	}
	if op.IsLinks || op.RequireScalarList {
		return "list"
	}
	return "scalar"
}

func equalEditFieldValue(leftKind string, left []string, rightKind string, right []string) bool {
	return leftKind == rightKind && equalEditValues(left, right)
}

func equalEditValues(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}
	return true
}

func formatEditValues(values []string) string {
	return strings.Join(values, ", ")
}

func reorderCollectionOpMatchesBase(state *documentState, op reorderCollectionOp) bool {
	if state == nil {
		return false
	}
	_, projection, err := projectState(state, op.ParentRef)
	if err != nil || projection == nil {
		return false
	}
	collection, ok := projection.Collections[op.Field]
	if !ok || validateCollectionPermutation(collection.Items, op.OrderedFragments) != nil {
		return false
	}
	for i, fragment := range op.OrderedFragments {
		if strings.TrimSpace(strings.TrimPrefix(fragment, "#")) != strings.TrimSpace(strings.TrimPrefix(collection.Items[i].Ref.Fragment, "#")) {
			return false
		}
	}
	return true
}

func projectedNodeTitle(projection *NodeProjection) string {
	if projection == nil || projection.Snapshot == nil {
		return ""
	}
	if projection.Ref.Kind == NodeKindNote {
		if title, ok := projection.Snapshot.Frontmatter["title"].(string); ok && strings.TrimSpace(title) != "" {
			return title
		}
		for _, section := range projection.Snapshot.Sections {
			if section != nil && section.Level == SectionLevelH1 && strings.TrimSpace(section.Title) != "" {
				return section.Title
			}
		}
		return titleFromNotePath(projection.Ref.NotePath)
	}
	if span := projection.Snapshot.SourceSpansByID[projection.Ref.NodeID]; span != nil {
		return span.Title
	}
	if section := projection.Snapshot.SectionsByID[projection.Ref.NodeID]; section != nil {
		return section.Title
	}
	return ""
}

func planHasMaterialChange(plan CommitPlan) bool {
	for _, file := range plan.Files {
		if file.HasMaterialChange {
			return true
		}
	}
	return false
}

func materialNotePathSet(plan CommitPlan) map[string]bool {
	out := make(map[string]bool, len(plan.Files))
	for _, file := range plan.Files {
		if file.HasMaterialChange {
			out[file.NotePath] = true
		}
	}
	return out
}

func planHasRebased(plan CommitPlan) bool {
	for _, file := range plan.Files {
		if file.Rebased {
			return true
		}
	}
	return false
}

type conflictListError struct {
	Conflicts []ConflictReport
}

func (e conflictListError) Error() string {
	if len(e.Conflicts) == 0 {
		return "edit conflict"
	}
	return e.Conflicts[0].Message
}

// AsConflictList unwraps a commit/preview conflict list error into a typed payload.
func AsConflictList(err error, target *conflictListError) bool {
	if err == nil || target == nil {
		return false
	}
	value, ok := err.(conflictListError)
	if !ok {
		return false
	}
	*target = value
	return true
}

func (op setFieldOp) notePath() string          { return op.Ref.NotePath }
func (op addEmbeddedNodeOp) notePath() string   { return op.ParentRef.NotePath }
func (op deleteNodeOp) notePath() string        { return op.Ref.NotePath }
func (op reorderCollectionOp) notePath() string { return op.ParentRef.NotePath }
func (op setNarrativeOp) notePath() string      { return op.Ref.NotePath }
func (op insertNarrativeOp) notePath() string   { return op.Ref.NotePath }
func (op ensureBlockIDOp) notePath() string     { return op.Ref.NotePath }
func (op setBlockIDOp) notePath() string        { return op.Ref.NotePath }
func (op removeBlockIDOp) notePath() string     { return op.Ref.NotePath }
func (op rewriteFileOp) notePath() string       { return op.NotePathValue }

func (op rewriteFileOp) apply(state *documentState) error {
	state.setContent(op.NewContent)
	return nil
}

func (op transformFileOp) notePath() string { return op.NotePathValue }

func (op transformFileOp) apply(state *documentState) error {
	updated, err := op.Transform(state.content)
	if err != nil {
		return err
	}
	state.setContent(updated)
	return nil
}

func (op setFieldOp) apply(state *documentState) error {
	if op.RawRootMetadata {
		if op.Ref.Kind != NodeKindNote || strings.TrimSpace(op.Ref.Fragment) != "" || strings.TrimSpace(op.Ref.NodeID) != "" {
			return fmt.Errorf("%w: raw root metadata requires a note root", errUnsupportedTarget)
		}
		if op.Unset {
			updated, err := unsetFrontmatterField(state.content, &Field{
				Name: op.Field, Source: op.Field, SourceKind: FieldSourceFrontmatter,
				Kind: FieldKindScalar, TypeName: "String", List: true,
			})
			if err != nil {
				return err
			}
			state.setContent(updated)
			return nil
		}
		updated, err := setRawFrontmatterList(state.content, op.Field, op.Values)
		if err != nil {
			return err
		}
		state.setContent(updated)
		return nil
	}
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	field, err := validateSetFieldOperation(projection, op, state.schema, state.allowSelectorRecovery)
	if err != nil {
		return err
	}
	if strings.EqualFold(op.Field, "title") {
		updated, err := setNodeTitleField(snapshot, projection, op.Values)
		if err != nil {
			return err
		}
		state.setContent(updated)
		return nil
	}
	if op.Unset {
		var updated string
		switch {
		case field.SourceKind == FieldSourceCheckbox:
			updated, err = setCheckboxField(snapshot, projection, field, []string{"false"})
		case projection.Ref.Kind == NodeKindNote && field.SourceKind == FieldSourceFrontmatter:
			updated, err = unsetFrontmatterField(state.content, field)
		case field.SourceKind == FieldSourceInline:
			updated, err = unsetInlineField(snapshot, projection, field)
		default:
			err = fmt.Errorf("%w: unsupported field target %s", errUnsupportedTarget, op.Field)
		}
		if err != nil {
			return err
		}
		state.setContent(updated)
		return nil
	}
	if field.SourceKind == FieldSourceCheckbox {
		updated, err := setCheckboxField(snapshot, projection, field, op.Values)
		if err != nil {
			return err
		}
		state.setContent(updated)
		return nil
	}
	if projection.Ref.Kind == NodeKindEmbedded && embeddedNodeNeedsBlockID(snapshot, projection) {
		updated, _, err := EnsureBlockIDInSnapshot(snapshot, projection, "")
		if err != nil {
			return err
		}
		state.setContent(updated)
		updatedRef := op.Ref
		updatedRef.NodeID = ""
		updatedRef.Structural = ""
		updatedRef.StartByte = 0
		updatedRef.EndByte = 0
		snapshot, projection, err = projectState(state, updatedRef)
		if err != nil {
			return err
		}
	}
	var updated string
	switch {
	case projection.Ref.Kind == NodeKindNote && field.SourceKind == FieldSourceFrontmatter:
		updated, err = setFrontmatterField(state.content, field, op.Values, op.IsLinks)
	case field.SourceKind == FieldSourceInline:
		updated, err = setInlineField(snapshot, projection, field, op.Values)
	default:
		err = fmt.Errorf("%w: unsupported field target %s", errUnsupportedTarget, op.Field)
	}
	if err != nil {
		return err
	}
	state.setContent(updated)
	return nil
}

func fieldSupportsValueList(field *Field) bool {
	return field != nil && field.List && (field.Kind == FieldKindScalar || field.Kind == FieldKindEnum)
}

func validateSetFieldOperation(projection *NodeProjection, op setFieldOp, schema *Schema, allowIdentifierRepair bool) (*Field, error) {
	if projection == nil || projection.Type == nil {
		if strings.EqualFold(op.Field, "title") {
			return nil, nil
		}
		return nil, fmt.Errorf("%w: node %s has no resolved ontology type", errMissingNode, op.Ref.String())
	}
	field := projection.Type.ByName[op.Field]
	if field == nil && strings.EqualFold(op.Field, "title") {
		for name, candidate := range projection.Type.ByName {
			if strings.EqualFold(name, op.Field) {
				field = candidate
				break
			}
		}
	}
	if field == nil {
		if strings.EqualFold(op.Field, "title") {
			return nil, nil
		}
		return nil, fmt.Errorf("%w: field %s not found on %s", errMissingField, op.Field, projection.Ref.String())
	}
	if field.IsIdentifier && !allowIdentifierRepair {
		return nil, fmt.Errorf("%w: identifier field %s requires the graph-safe identifier rename workflow", errUnsupportedTarget, op.Field)
	}
	if op.RequireScalarList && !fieldSupportsValueList(field) {
		return nil, fmt.Errorf("%w: field %s is not a scalar or enum list", errUnsupportedTarget, op.Field)
	}
	if op.IsLinks && field.Kind != FieldKindLink {
		return nil, fmt.Errorf("%w: field %s is not a relation", errUnsupportedTarget, op.Field)
	}
	if !op.IsLinks && field.Kind == FieldKindLink {
		return nil, fmt.Errorf("%w: relation field %s requires a link edit", errUnsupportedTarget, op.Field)
	}
	if op.Unset {
		if field.Required {
			return nil, fmt.Errorf("%w: required field %s cannot be unset", errUnsupportedTarget, op.Field)
		}
		return field, nil
	}
	if err := validateEditFieldValues(field, op.Values, schema); err != nil {
		return nil, err
	}
	if op.IsLinks {
		for _, value := range op.Values {
			if strings.TrimSpace(value) == "" {
				return nil, fmt.Errorf("%w: relation field %s contains an empty target", errUnsupportedTarget, op.Field)
			}
		}
	}
	return field, nil
}

func setNodeTitleField(snapshot *DocumentSnapshot, projection *NodeProjection, values []string) (string, error) {
	if snapshot == nil || projection == nil {
		return "", fmt.Errorf("%w: title projection is required", errMissingNode)
	}
	if len(values) != 1 {
		return "", fmt.Errorf("%w: title expects one value", errUnsupportedTarget)
	}
	value := oneLineTitleValue(values[0])
	switch projection.Ref.Kind {
	case NodeKindNote:
		if _, ok := snapshot.Frontmatter["title"]; ok || snapshot.FrontmatterRange.Len() > 0 {
			return setFrontmatterField(snapshot.Content, &Field{Name: "title", Source: "title", SourceKind: FieldSourceFrontmatter, TypeName: "String"}, []string{value}, false)
		}
		return setNotePrimaryHeadingTitle(snapshot, value)
	case NodeKindSection:
		return setSectionHeadingTitle(snapshot, projection, value)
	case NodeKindEmbedded:
		if span := snapshot.SourceSpansByID[projection.Ref.NodeID]; span != nil {
			if span.Shape == EmbeddedSourceShapeSection {
				return setSectionHeadingTitle(snapshot, projection, value)
			}
			return setSourceSpanTitleField(snapshot, projection, value)
		}
		return setSectionHeadingTitle(snapshot, projection, value)
	default:
		return "", fmt.Errorf("%w: unsupported title target %s", errUnsupportedTarget, projection.Ref.String())
	}
}

func setNotePrimaryHeadingTitle(snapshot *DocumentSnapshot, value string) (string, error) {
	if snapshot == nil {
		return "", fmt.Errorf("%w: title projection is required", errMissingNode)
	}
	h1s := make([]*SectionNode, 0, 1)
	for _, node := range snapshot.Sections {
		if node != nil && node.Level == SectionLevelH1 {
			h1s = append(h1s, node)
		}
	}
	if len(h1s) != 1 {
		return "", fmt.Errorf("%w: note title requires title frontmatter or one H1", errUnsupportedTarget)
	}
	return replaceHeadingLineTitle(snapshot.Content, h1s[0].StartByte, value)
}

func setSectionHeadingTitle(snapshot *DocumentSnapshot, projection *NodeProjection, value string) (string, error) {
	if snapshot == nil || projection == nil {
		return "", fmt.Errorf("%w: title projection is required", errMissingNode)
	}
	if node := snapshot.SectionsByID[projection.Ref.NodeID]; node != nil {
		return replaceHeadingLineTitle(snapshot.Content, node.StartByte, value)
	}
	return "", fmt.Errorf("%w: heading title not found for %s", errMissingNode, projection.Ref.String())
}

func replaceHeadingLineTitle(content string, lineStart int, value string) (string, error) {
	if lineStart < 0 || lineStart >= len(content) {
		return "", fmt.Errorf("%w: invalid heading title range", errCollectionDrift)
	}
	lineEnd := len(content)
	if nextLine := strings.IndexByte(content[lineStart:], '\n'); nextLine >= 0 {
		lineEnd = lineStart + nextLine
	}
	line := content[lineStart:lineEnd]
	leading := 0
	for leading < len(line) && line[leading] == ' ' {
		leading++
	}
	hashes := leading
	for hashes < len(line) && line[hashes] == '#' {
		hashes++
	}
	if hashes == leading || hashes-leading > 6 {
		return "", fmt.Errorf("%w: target line is not a heading", errUnsupportedTarget)
	}
	titleStart := hashes
	for titleStart < len(line) && (line[titleStart] == ' ' || line[titleStart] == '\t') {
		titleStart++
	}
	titleEnd := trimHeadingTitleEnd(line, titleStart, len(line))
	if titleEnd < titleStart {
		titleEnd = titleStart
	}
	return replaceRange(content, ByteRange{Start: lineStart + titleStart, End: lineStart + titleEnd}, value), nil
}

func trimHeadingTitleEnd(line string, start, end int) int {
	end = trimSpaceLeftBounded(line, start, end)
	cursor := end - 1
	for cursor >= start && line[cursor] == '#' {
		cursor--
	}
	if cursor < end-1 {
		beforeHashes := trimSpaceLeftBounded(line, start, cursor+1)
		if beforeHashes < cursor+1 {
			return beforeHashes
		}
	}
	return end
}

func setSourceSpanTitleField(snapshot *DocumentSnapshot, projection *NodeProjection, value string) (string, error) {
	span := snapshot.SourceSpansByID[projection.Ref.NodeID]
	if span == nil || (span.Shape != EmbeddedSourceShapeCheckboxItem && span.Shape != EmbeddedSourceShapeListItem) {
		return "", fmt.Errorf("%w: unsupported title target %s", errUnsupportedTarget, projection.Ref.String())
	}
	if !span.ContentRange.Valid(len(snapshot.Content)) || span.ContentRange.Len() == 0 {
		return "", fmt.Errorf("%w: invalid title range for %s", errCollectionDrift, projection.Ref.String())
	}
	edit, err := sourceSpanTitleEdit(snapshot, span, value)
	if err != nil {
		return "", err
	}
	return replaceRange(snapshot.Content, edit.r, edit.replacement), nil
}

func oneLineTitleValue(value string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(value, "\n", " ")), " ")
}

func setCheckboxField(snapshot *DocumentSnapshot, projection *NodeProjection, field *Field, values []string) (string, error) {
	if snapshot == nil || projection == nil || field == nil {
		return "", fmt.Errorf("%w: checkbox projection is required", errMissingNode)
	}
	if field.TypeName != "Boolean" || field.List {
		return "", fmt.Errorf("%w: checkbox field %s must be a singular Boolean", errUnsupportedTarget, field.Name)
	}
	if len(values) != 1 {
		return "", fmt.Errorf("%w: checkbox field %s expects one value", errUnsupportedTarget, field.Name)
	}
	desired, err := parseCheckboxEditValue(values[0])
	if err != nil {
		return "", err
	}
	span := snapshot.SourceSpansByID[projection.Ref.NodeID]
	if span == nil || span.Shape != EmbeddedSourceShapeCheckboxItem || span.Checkbox == nil {
		return "", fmt.Errorf("%w: %s is not a checkbox item", errUnsupportedTarget, projection.Ref.String())
	}
	r := span.Checkbox.TokenRange
	if !r.Valid(len(snapshot.Content)) || r.Len() != len("[ ]") {
		return "", fmt.Errorf("%w: invalid checkbox token range for %s", errCollectionDrift, projection.Ref.String())
	}
	if span.Checkbox.Checked == desired {
		return snapshot.Content, nil
	}
	token := "[ ]"
	if desired {
		token = "[x]"
	}
	return replaceRange(snapshot.Content, r, token), nil
}

func parseCheckboxEditValue(value string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "true", "checked", "done", "x", "1":
		return true, nil
	case "false", "unchecked", "open", " ", "0":
		return false, nil
	default:
		return false, fmt.Errorf("%w: invalid checkbox value %q", errUnsupportedTarget, value)
	}
}

func (op addEmbeddedNodeOp) apply(state *documentState) error {
	snapshot, parentProjection, err := projectState(state, op.ParentRef)
	if err != nil {
		return err
	}
	field := parentProjection.Type.ByName[op.Field]
	if field == nil || field.Kind != FieldKindSection || !field.List {
		return fmt.Errorf("%w: collection %s not found on %s", errMissingField, op.Field, parentProjection.Ref.String())
	}
	childType := state.schema.Types[field.TypeName]
	if childType == nil || childType.Role != TypeRoleEmbeddedNode {
		return fmt.Errorf("%w: collection %s does not target embedded nodes", errUnsupportedTarget, op.Field)
	}
	blockID := strings.TrimSpace(strings.TrimPrefix(op.BlockID, "^"))
	if blockID == "" {
		blockID = slugBlockID(op.Heading)
	}
	if !ValidBlockID(blockID) {
		return fmt.Errorf("%w: invalid block ID %q", errUnsupportedTarget, blockID)
	}
	if owner, ok := existingBlockIDs(snapshot)[blockID]; ok && strings.TrimSpace(owner) != "" {
		return fmt.Errorf("%w: duplicate block ID %q", errUnsupportedTarget, blockID)
	}
	level := strings.Repeat("#", sectionLevelInt(field.SectionLevel))
	if level == "" {
		return fmt.Errorf("%w: collection %s has invalid section level", errUnsupportedTarget, op.Field)
	}
	snippet := strings.TrimRight(level+" "+strings.TrimSpace(op.Heading)+"\n"+strings.TrimSpace(op.Body)+"\n^"+blockID+"\n", "\n") + "\n"
	insertAt := collectionInsertOffset(snapshot, parentProjection, op.Field)
	if insertAt < 0 || insertAt > len(state.content) {
		return fmt.Errorf("%w: invalid insert offset for %s", errUnsupportedTarget, op.Field)
	}
	state.setContent(state.content[:insertAt] + snippet + state.content[insertAt:])
	return nil
}

func (op deleteNodeOp) apply(state *documentState) error {
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	if projection.Ref.Kind == NodeKindNote {
		return fmt.Errorf("%w: deleting full notes is out of scope", errUnsupportedTarget)
	}
	r := ByteRange{Start: projection.Ref.StartByte, End: projection.Ref.EndByte}
	if !r.Valid(len(snapshot.Content)) || r.Len() == 0 {
		return fmt.Errorf("%w: invalid node span for %s", errMissingNode, projection.Ref.String())
	}
	state.setContent(replaceRange(state.content, r, ""))
	return nil
}

func (op reorderCollectionOp) apply(state *documentState) error {
	snapshot, parentProjection, err := projectState(state, op.ParentRef)
	if err != nil {
		return err
	}
	collection, ok := parentProjection.Collections[op.Field]
	if !ok {
		return fmt.Errorf("%w: collection %s not found on %s", errMissingField, op.Field, parentProjection.Ref.String())
	}
	if err := validateCollectionPermutation(collection.Items, op.OrderedFragments); err != nil {
		return fmt.Errorf("%w: collection %s %v", errCollectionDrift, op.Field, err)
	}
	if state.baseSnapshot != nil {
		baseProjection, err := ProjectNodeFromSnapshot(state.baseSnapshot, state.schema, op.ParentRef)
		if err != nil {
			return err
		}
		baseCollection, ok := baseProjection.Collections[op.Field]
		if !ok {
			return fmt.Errorf("%w: collection %s not found on %s", errMissingField, op.Field, baseProjection.Ref.String())
		}
		if len(baseCollection.Items) == len(collection.Items) &&
			sameCollectionMembers(baseCollection.Items, collection.Items) &&
			baseCollection.OrderFingerprint != "" && collection.OrderFingerprint != "" &&
			baseCollection.OrderFingerprint != collection.OrderFingerprint {
			return fmt.Errorf("%w: collection %s order changed", errCollectionDrift, op.Field)
		}
	}
	itemByFragment := make(map[string]CollectionItem, len(collection.Items))
	blockByFragment := make(map[string]string, len(collection.Items))
	for _, item := range collection.Items {
		key := strings.TrimSpace(strings.TrimPrefix(item.Ref.Fragment, "#"))
		itemByFragment[key] = item
	}
	for i, item := range collection.Items {
		key := strings.TrimSpace(strings.TrimPrefix(item.Ref.Fragment, "#"))
		blockStart := item.Range.Start
		blockEnd := collection.Range.End
		if i+1 < len(collection.Items) {
			blockEnd = collection.Items[i+1].Range.Start
		}
		if blockEnd < blockStart || blockEnd > len(snapshot.Content) {
			return fmt.Errorf("%w: invalid member span for %s", errCollectionDrift, item.Ref.String())
		}
		blockByFragment[key] = snapshot.Content[blockStart:blockEnd]
	}
	ordered := make([]CollectionItem, 0, len(op.OrderedFragments))
	for _, fragment := range op.OrderedFragments {
		item, ok := itemByFragment[strings.TrimSpace(strings.TrimPrefix(fragment, "#"))]
		if !ok {
			return fmt.Errorf("%w: collection %s is missing %s", errCollectionDrift, op.Field, fragment)
		}
		ordered = append(ordered, item)
	}
	if !collection.Range.Valid(len(snapshot.Content)) || collection.Range.Len() == 0 {
		return fmt.Errorf("%w: collection %s has invalid range", errCollectionDrift, op.Field)
	}
	var b strings.Builder
	for _, item := range ordered {
		key := strings.TrimSpace(strings.TrimPrefix(item.Ref.Fragment, "#"))
		block, ok := blockByFragment[key]
		if !ok {
			return fmt.Errorf("%w: invalid member span for %s", errCollectionDrift, item.Ref.String())
		}
		b.WriteString(block)
	}
	state.setContent(replaceRange(state.content, collection.Range, b.String()))
	return nil
}

func validateCollectionPermutation(items []CollectionItem, orderedFragments []string) error {
	if len(items) != len(orderedFragments) {
		return fmt.Errorf("membership changed")
	}
	actual := make(map[string]struct{}, len(items))
	for _, item := range items {
		key := strings.TrimSpace(strings.TrimPrefix(item.Ref.Fragment, "#"))
		if key == "" {
			return fmt.Errorf("member has no stable fragment")
		}
		if _, exists := actual[key]; exists {
			return fmt.Errorf("member %q is duplicated", key)
		}
		actual[key] = struct{}{}
	}
	requested := make(map[string]struct{}, len(orderedFragments))
	for _, fragment := range orderedFragments {
		key := strings.TrimSpace(strings.TrimPrefix(fragment, "#"))
		if key == "" {
			return fmt.Errorf("requested member is empty")
		}
		if _, exists := requested[key]; exists {
			return fmt.Errorf("requested member %q is duplicated", key)
		}
		if _, exists := actual[key]; !exists {
			return fmt.Errorf("requested member %q is missing", key)
		}
		requested[key] = struct{}{}
	}
	if len(requested) != len(actual) {
		return fmt.Errorf("membership changed")
	}
	return nil
}

func (op setNarrativeOp) apply(state *documentState) error {
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	blocks := BuildNodeBody(projection, state.schema)
	block, err := resolveNarrativeBlock(blocks, op)
	if err != nil {
		return err
	}
	raw := snapshot.Content[block.Range.Start:block.Range.End]
	replacement := preserveNarrativeSuffix(raw, op.Markdown)
	state.setContent(replaceRange(state.content, ByteRange{
		Start: block.Range.Start,
		End:   block.Range.End,
	}, replacement))
	return nil
}

func (op insertNarrativeOp) apply(state *documentState) error {
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	for _, block := range BuildNodeBody(projection, state.schema) {
		if block.Kind == NodeBodyBlockKindNarrative || block.Kind == NodeBodyBlockKindChildSection || block.Kind == NodeBodyBlockKindCollection {
			return fmt.Errorf("%w: %s already has body content", errUnsupportedTarget, op.Ref.String())
		}
	}
	bodyRange, _, ok := nodeBodyContentRange(projection)
	if !ok || bodyRange.Start < 0 || bodyRange.Start > len(snapshot.Content) {
		return fmt.Errorf("%w: no safe narrative insertion point for %s", errUnsupportedTarget, op.Ref.String())
	}
	replacement := strings.TrimRight(op.Markdown, " \t\n") + "\n\n"
	state.setContent(snapshot.Content[:bodyRange.Start] + replacement + snapshot.Content[bodyRange.Start:])
	return nil
}

func (op ensureBlockIDOp) apply(state *documentState) error {
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	if updated, ok, err := ensureIdentifierBackedBlockID(snapshot, projection, op.BlockID); err != nil {
		return err
	} else if ok {
		state.setContent(updated)
		return nil
	}
	updated, _, err := EnsureBlockIDInSnapshot(snapshot, projection, op.BlockID)
	if err != nil {
		return err
	}
	state.setContent(updated)
	return nil
}

func ensureIdentifierBackedBlockID(snapshot *DocumentSnapshot, projection *NodeProjection, preferred string) (string, bool, error) {
	if projection == nil || projection.Ref.Kind != NodeKindEmbedded || projection.Type == nil {
		return "", false, nil
	}
	field := preferredBlockIdentifierField(projection.Type)
	if field == nil || field.SourceKind != FieldSourceInline {
		return "", false, nil
	}
	blockID := strings.TrimSpace(strings.TrimPrefix(preferred, "^"))
	if blockID == "" {
		blockID = GenerateBlockIDForProjection(snapshot, projection)
	}
	blockID = BlockSafeIdentifier(blockID)
	if !ValidBlockID(blockID) {
		return "", false, fmt.Errorf("%w: invalid block ID %q", errUnsupportedTarget, blockID)
	}
	if owner, ok := existingBlockIDs(snapshot)[blockID]; ok && owner != projection.Ref.NodeID {
		return "", false, fmt.Errorf("%w: duplicate block ID %q", errUnsupportedTarget, blockID)
	}
	updated, err := setInlineField(snapshot, projection, field, []string{"^" + blockID})
	if err != nil {
		return "", false, err
	}
	return updated, true, nil
}

func preferredBlockIdentifierField(noteType *NoteType) *Field {
	if noteType == nil {
		return nil
	}
	for _, field := range noteType.Fields {
		if field == nil || field.Kind != FieldKindScalar || field.List {
			continue
		}
		if field.IsPreferredIdentifier {
			return field
		}
	}
	for _, field := range noteType.Fields {
		if field == nil || field.Kind != FieldKindScalar || field.List {
			continue
		}
		if field.IsIdentifier {
			return field
		}
	}
	return nil
}

func (op setBlockIDOp) apply(state *documentState) error {
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	if projection.Ref.Kind != NodeKindEmbedded {
		return nil
	}
	blockID := strings.TrimSpace(strings.TrimPrefix(op.BlockID, "^"))
	if !ValidBlockID(blockID) {
		return fmt.Errorf("%w: invalid block ID %q", errUnsupportedTarget, blockID)
	}
	node := snapshot.SectionsByID[projection.Ref.NodeID]
	if node == nil {
		return fmt.Errorf("%w: embedded node %s not found", errMissingNode, projection.Ref.String())
	}
	if strings.TrimPrefix(strings.TrimSpace(node.BlockID), "^") == blockID {
		return nil
	}
	if owner, ok := existingBlockIDs(snapshot)[blockID]; ok && owner != node.ID {
		return fmt.Errorf("%w: duplicate block ID %q", errUnsupportedTarget, blockID)
	}
	blockRange, ok := sectionBlockIDRange(snapshot.Content, node)
	if !ok {
		updated, _, err := EnsureBlockIDInSnapshot(snapshot, projection, blockID)
		if err != nil {
			return err
		}
		state.setContent(updated)
		return nil
	}
	state.setContent(replaceRange(snapshot.Content, blockRange, "^"+blockID))
	return nil
}

func (op removeBlockIDOp) apply(state *documentState) error {
	snapshot, projection, err := projectState(state, op.Ref)
	if err != nil {
		return err
	}
	if projection.Ref.Kind != NodeKindEmbedded && projection.Ref.Kind != NodeKindSection {
		return nil
	}
	node := snapshot.SectionsByID[projection.Ref.NodeID]
	if node == nil {
		return fmt.Errorf("%w: node %s not found", errMissingNode, projection.Ref.String())
	}
	if strings.TrimSpace(node.BlockID) == "" {
		return nil
	}
	// WHY: per SPEC-0023.US8, identifier-backed lines on derivable-identity
	// fields with populate: ON_LINK become opt-in linkability — when
	// the orphan-cleanup pass strips an unreferenced anchor, the source line
	// to delete is the whole `id:: ^...` line, not just the standalone
	// `^block-id` byte range that sectionBlockIDRange finds.
	if removed, ok, err := tryRemoveDerivableIdentifierLine(state, snapshot, projection, node); err != nil {
		return err
	} else if ok {
		state.setContent(removed)
		return nil
	}
	blockRange, ok := sectionBlockIDRange(snapshot.Content, node)
	if !ok {
		return nil
	}
	// Extend the range to consume the surrounding line so removing the anchor
	// does not leave a blank `^id`-shaped hole behind. Eat the leading newline
	// when the line is anchor-only and the trailing newline likewise. This
	// keeps source markdown clean across iterated cleanup runs.
	start, end := blockRange.Start, blockRange.End
	for end < len(snapshot.Content) && snapshot.Content[end] == ' ' {
		end++
	}
	if end < len(snapshot.Content) && snapshot.Content[end] == '\n' {
		end++
	}
	if start > 0 && snapshot.Content[start-1] == '\n' {
		// Only eat the preceding newline when the anchor sat on its own line;
		// otherwise we would join two unrelated content lines.
		preceding := snapshot.Content[:start-1]
		if idx := strings.LastIndexByte(preceding, '\n'); idx == -1 || strings.TrimSpace(preceding[idx+1:]) == "" {
			start--
		}
	}
	state.setContent(replaceRange(snapshot.Content, ByteRange{Start: start, End: end}, ""))
	return nil
}

// tryRemoveDerivableIdentifierLine deletes the authored `id:: ^...` line on a
// derivable-identity embedded node when the orphan-cleanup pass targets the
// node's preferred-identifier field. Returns (newContent, true, nil) when a
// derivable identifier line was found and removed, or (_, false, nil) when the
// node's anchor is sourced from a standalone `^block-id` and the caller should
// fall back to the legacy byte-range removal.
func tryRemoveDerivableIdentifierLine(state *documentState, snapshot *DocumentSnapshot, projection *NodeProjection, node *SectionNode) (string, bool, error) {
	if projection == nil || projection.Type == nil {
		return "", false, nil
	}
	field := preferredIdentifierField(projection.Type)
	if field == nil || !field.IsDerivableIdentifier || field.SourceKind != FieldSourceInline {
		return "", false, nil
	}
	binding, ok := projection.Fields[field.Name]
	if !ok || binding.Derived || len(binding.InlineSpans) == 0 {
		// Either the field is purely derived (no authored line to remove) or
		// the projection didn't surface a span to delete; either way nothing
		// to do via this path.
		return "", false, nil
	}
	span := binding.InlineSpans[0]
	start, end := span.LineRange.Start, span.LineRange.End
	if start < 0 || end <= start {
		return "", false, nil
	}
	// Walk back to consume the leading newline so the line removal does not
	// leave a blank line behind.
	if start > 0 && snapshot.Content[start-1] == '\n' {
		preceding := snapshot.Content[:start-1]
		if idx := strings.LastIndexByte(preceding, '\n'); idx == -1 || strings.TrimSpace(preceding[idx+1:]) == "" {
			start--
		}
	}
	// Walk forward through the line terminator.
	if end < len(snapshot.Content) && snapshot.Content[end] == '\n' {
		end++
	}
	updated := replaceRange(snapshot.Content, ByteRange{Start: start, End: end}, "")
	_ = state
	return updated, true, nil
}

func sameCollectionMembers(left, right []CollectionItem) bool {
	if len(left) != len(right) {
		return false
	}
	counts := make(map[string]int, len(left))
	for _, item := range left {
		counts[strings.TrimSpace(strings.TrimPrefix(item.Ref.Fragment, "#"))]++
	}
	for _, item := range right {
		key := strings.TrimSpace(strings.TrimPrefix(item.Ref.Fragment, "#"))
		counts[key]--
		if counts[key] < 0 {
			return false
		}
	}
	for _, count := range counts {
		if count != 0 {
			return false
		}
	}
	return true
}

var (
	errMissingNode       = fmt.Errorf("missing node")
	errMissingField      = fmt.Errorf("missing field")
	errCollectionDrift   = fmt.Errorf("collection drift")
	errUnsupportedTarget = fmt.Errorf("unsupported target")
)

func projectState(state *documentState, ref NodeRef) (*DocumentSnapshot, *NodeProjection, error) {
	if rootOnly, err := state.providerRootOnly(); err != nil {
		return nil, nil, err
	} else if rootOnly {
		if ref.Kind != NodeKindNote || strings.TrimSpace(ref.Fragment) != "" || strings.TrimSpace(ref.NodeID) != "" {
			return nil, nil, fmt.Errorf("%w: provider exposes only the note root", errUnsupportedTarget)
		}
		_, _, projection, err := state.projectProviderRoot(state.content)
		if err != nil {
			return nil, nil, err
		}
		return &DocumentSnapshot{
			NotePath: ref.NotePath, Content: state.content, ContentFingerprint: hashText(state.content),
		}, projection, nil
	}
	snapshot, err := state.documentSnapshot()
	if err != nil {
		return nil, nil, err
	}
	projection, err := projectSnapshot(snapshot, state.schema, ref, state.allowSelectorRecovery)
	if err != nil {
		return nil, nil, err
	}
	return snapshot, projection, nil
}

func (s *documentState) documentSnapshot() (*DocumentSnapshot, error) {
	if s.snapshot != nil && s.snapshotFor == s.content {
		return s.snapshot, nil
	}
	snapshot, err := BuildDocumentSnapshot(s.notePath, s.content, time.Time{})
	if err != nil {
		return nil, err
	}
	s.snapshot = snapshot
	s.snapshotFor = s.content
	return snapshot, nil
}

func projectSnapshot(snapshot *DocumentSnapshot, schema *Schema, ref NodeRef, allowSelectorRecovery bool) (*NodeProjection, error) {
	projection, err := ProjectNodeFromSnapshot(snapshot, schema, ref)
	if err != nil {
		return nil, err
	}
	if allowSelectorRecovery && projection.Type == nil && strings.TrimSpace(ref.TypeName) != "" {
		recovered, recoveryErr := ProjectNodeFromSnapshotWithSelectorRecovery(snapshot, schema, ref)
		if recoveryErr != nil {
			return nil, recoveryErr
		}
		if recovered.Type == nil {
			return nil, fmt.Errorf("missing selector-matched note projection for %s", ref.String())
		}
		projection = recovered
	}
	if err := validateResolvedProjectionRef(ref, projection.Ref); err != nil {
		return nil, err
	}
	return projection, nil
}

func setFrontmatterField(content string, field *Field, values []string, asLinks bool) (string, error) {
	if updated, ok, err := patchFrontmatterFieldSource(content, field, values, asLinks); err != nil {
		return "", err
	} else if ok {
		return updated, nil
	}
	doc, mapping, err := parseFrontmatterNode(content)
	if err != nil {
		return "", err
	}
	key := field.Source
	if key == "" {
		key = DefaultPropertyName(field.Name, PropertyCaseKebab)
	}
	encoded := make([]string, 0, len(values))
	for _, value := range values {
		if asLinks {
			encoded = append(encoded, strings.TrimSpace(value))
		} else {
			encoded = append(encoded, value)
		}
	}
	switch {
	case field.List:
		setYAMLSequenceValuePreservingStyle(mapping, key, encoded)
	case len(encoded) == 0:
		deleteYAMLMappingValue(mapping, key)
	default:
		setYAMLMappingValue(mapping, key, scalarYAMLNode(encoded[0]))
	}
	yamlText, err := encodeFrontmatterNode(doc)
	if err != nil {
		return "", err
	}
	fmRange := frontmatterRange(content)
	if fmRange.Len() == 0 {
		return "---\n" + yamlText + "---\n" + content, nil
	}
	return replaceRange(content, fmRange, "---\n"+yamlText+"---\n"), nil
}

func validateResolvedProjectionRef(requested NodeRef, resolved NodeRef) error {
	// WHY: author-facing locators may survive unrelated insertions, but replay
	// must stop when the resolved canonical node identity no longer matches the
	// captured operation. See [[ontology-edit-replay-conflict-contract]].
	// A note root is identified by its path; its structure fingerprint hashes
	// section byte offsets, so any earlier staged edit would move it.
	if requested.Kind == NodeKindNote && resolved.Kind == NodeKindNote {
		return nil
	}
	if requested.Structural != "" &&
		strings.TrimSpace(requested.Structural) != strings.TrimSpace(resolved.Structural) {
		if requested.Kind == NodeKindEmbedded && strings.TrimSpace(resolved.TypeName) != "" {
			if start, ok := sourceSpanStartFromFragment(normalizeSectionFragment(requested.Fragment, requested.NotePath)); ok && start == resolved.StartByte {
				return nil
			}
		}
		return fmt.Errorf("%w: structure changed for %s", errMissingNode, requested.String())
	}
	if requested.Structural == "" && requested.NodeID != "" &&
		strings.TrimSpace(requested.NodeID) != strings.TrimSpace(resolved.NodeID) {
		return fmt.Errorf("%w: node id changed for %s", errMissingNode, requested.String())
	}
	return nil
}

func parseFrontmatterNode(content string) (*yaml.Node, *yaml.Node, error) {
	fmRange := frontmatterRange(content)
	if fmRange.Len() == 0 {
		doc := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{{Kind: yaml.MappingNode}}}
		return doc, doc.Content[0], nil
	}
	raw := content[fmRange.Start:fmRange.End]
	lines := strings.Split(raw, "\n")
	if len(lines) >= 2 {
		raw = strings.Join(lines[1:len(lines)-1], "\n")
	}
	doc := &yaml.Node{}
	if err := yaml.Unmarshal([]byte(raw), doc); err != nil {
		return nil, nil, err
	}
	if doc.Kind == 0 {
		doc = &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{{Kind: yaml.MappingNode}}}
	}
	if doc.Kind != yaml.DocumentNode {
		doc = &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{doc}}
	}
	if len(doc.Content) == 0 || doc.Content[0] == nil {
		doc.Content = []*yaml.Node{{Kind: yaml.MappingNode}}
	}
	if doc.Content[0].Kind != yaml.MappingNode {
		return nil, nil, fmt.Errorf("frontmatter is not a mapping")
	}
	return doc, doc.Content[0], nil
}

func encodeFrontmatterNode(doc *yaml.Node) (string, error) {
	var b strings.Builder
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return "", err
	}
	if err := enc.Close(); err != nil {
		return "", err
	}
	return strings.TrimPrefix(b.String(), "---\n"), nil
}

func yamlSequenceNode(values []string) *yaml.Node {
	node := &yaml.Node{Kind: yaml.SequenceNode}
	for _, value := range values {
		node.Content = append(node.Content, scalarYAMLNode(value))
	}
	return node
}

func scalarYAMLNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value}
}

func setYAMLMappingValue(mapping *yaml.Node, key string, value *yaml.Node) {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			mapping.Content[i+1] = value
			return
		}
	}
	mapping.Content = append(mapping.Content, scalarYAMLNode(key), value)
}

func deleteYAMLMappingValue(mapping *yaml.Node, key string) {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			mapping.Content = append(mapping.Content[:i], mapping.Content[i+2:]...)
			return
		}
	}
}

func setInlineField(snapshot *DocumentSnapshot, projection *NodeProjection, field *Field, values []string) (string, error) {
	edits, err := inlineFieldEdits(snapshot, projection, field, values)
	if err != nil {
		return "", err
	}
	content := snapshot.Content
	for i := len(edits) - 1; i >= 0; i-- {
		content = replaceRange(content, edits[i].r, edits[i].replacement)
	}
	return content, nil
}

func unsetInlineField(snapshot *DocumentSnapshot, projection *NodeProjection, field *Field) (string, error) {
	if snapshot == nil || projection == nil || field == nil {
		return "", fmt.Errorf("%w: inline field projection is required", errMissingNode)
	}
	binding := projection.Fields[field.Name]
	if len(binding.InlineSpans) == 0 {
		return snapshot.Content, nil
	}
	content := snapshot.Content
	for index := len(binding.InlineSpans) - 1; index >= 0; index-- {
		span := binding.InlineSpans[index]
		rangeToRemove := inlineFieldEditRange(snapshot.Content, span)
		if !rangeToRemove.Valid(len(content)) {
			return "", fmt.Errorf("%w: invalid inline field range for %s", errCollectionDrift, field.Name)
		}
		content = replaceRange(content, rangeToRemove, "")
	}
	return content, nil
}

func inlineFieldEditRange(content string, span InlineFieldSpan) ByteRange {
	line, whole := span.LineRange, span.WholeRange
	if !line.Valid(len(content)) || !whole.Valid(len(content)) || whole.Start < line.Start || whole.End > line.End {
		return line
	}
	// Preserve surrounding prose and properties even when the schema does not declare them.
	if strings.TrimSpace(content[line.Start:whole.Start]) != "" || strings.TrimSpace(content[whole.End:line.End]) != "" {
		return whole
	}
	return line
}

func inlineFieldReplacementPrefix(content string, span InlineFieldSpan) string {
	if !span.LineRange.Valid(len(content)) || !span.KeyRange.Valid(len(content)) {
		return ""
	}
	if span.KeyRange.Start < span.LineRange.Start || span.KeyRange.Start > span.LineRange.End {
		return ""
	}
	prefix := content[span.LineRange.Start:span.KeyRange.Start]
	if isBulletInlinePropertyPrefix(prefix) {
		return prefix
	}
	return ""
}

func isBulletInlinePropertyPrefix(prefix string) bool {
	trimmed := strings.TrimSpace(prefix)
	return trimmed == "-" || trimmed == "*" || trimmed == "+"
}

func rangeStartsLine(content string, start int) bool {
	return start <= 0 || start > len(content) || content[start-1] == '\n'
}

func collectionInsertOffset(snapshot *DocumentSnapshot, parentProjection *NodeProjection, fieldName string) int {
	if collection, ok := parentProjection.Collections[fieldName]; ok && len(collection.Items) > 0 {
		return collection.Items[len(collection.Items)-1].Range.End
	}
	if parentProjection.Ref.Kind == NodeKindNote {
		return len(snapshot.Content)
	}
	return parentProjection.Ref.EndByte
}

func inlineInsertOffset(snapshot *DocumentSnapshot, projection *NodeProjection) int {
	if projection.Ref.Kind == NodeKindNote {
		return len(snapshot.Content)
	}
	node := snapshot.SectionsByID[projection.Ref.NodeID]
	if node == nil {
		return projection.Ref.EndByte
	}
	if strings.TrimSpace(node.BlockID) != "" {
		line := "\n^" + strings.TrimPrefix(node.BlockID, "^")
		if idx := strings.LastIndex(node.Content, line); idx >= 0 {
			return node.StartByte + idx
		}
	}
	return node.EndByte
}

func embeddedNodeNeedsBlockID(snapshot *DocumentSnapshot, projection *NodeProjection) bool {
	if projection == nil || projection.Ref.Kind != NodeKindEmbedded {
		return false
	}
	node := snapshot.SectionsByID[projection.Ref.NodeID]
	if node == nil {
		return false
	}
	return strings.TrimSpace(node.BlockID) == ""
}

func replaceRange(content string, r ByteRange, replacement string) string {
	if !r.Valid(len(content)) {
		return content
	}
	return content[:r.Start] + replacement + content[r.End:]
}

func conflictFromError(notePath string, op editOp, err error) ConflictReport {
	ref := ""
	field := ""
	kind := ConflictKindUnsupportedTarget
	switch typed := op.(type) {
	case setFieldOp:
		ref = typed.Ref.String()
		field = typed.Field
	case setRawFrontmatterListOp:
		ref = typed.Ref.String()
		field = typed.Field
	case setNarrativeOp:
		ref = typed.Ref.String()
	case insertNarrativeOp:
		ref = typed.Ref.String()
	case ensureBlockIDOp:
		ref = typed.Ref.String()
	case setBlockIDOp:
		ref = typed.Ref.String()
	case removeBlockIDOp:
		ref = typed.Ref.String()
	case addEmbeddedNodeOp:
		ref = typed.ParentRef.String()
		field = typed.Field
	case deleteNodeOp:
		ref = typed.Ref.String()
	case reorderCollectionOp:
		ref = typed.ParentRef.String()
		field = typed.Field
	case addSectionFieldOp:
		ref = typed.Ref.String()
		field = typed.FieldPath
	}
	switch {
	case strings.Contains(err.Error(), errMissingNode.Error()),
		strings.Contains(err.Error(), " not found in "):
		kind = ConflictKindMissingNode
	case strings.Contains(err.Error(), errMissingField.Error()):
		kind = ConflictKindMissingField
	case strings.Contains(err.Error(), errCollectionDrift.Error()):
		kind = ConflictKindCollectionDrift
	case strings.Contains(strings.ToLower(err.Error()), "source changed"):
		kind = ConflictKindSourceChanged
	default:
		kind = ConflictKindUnsupportedTarget
	}
	return ConflictReport{
		Kind:     kind,
		NotePath: notePath,
		NodeRef:  ref,
		Field:    field,
		Message:  err.Error(),
	}
}

func resolveNarrativeBlock(blocks []NodeBodyBlock, op setNarrativeOp) (*NodeBodyBlock, error) {
	// Docs: [[ontology-edit-replay-conflict-contract#^spec-0046-span-ownership]]
	// keeps narrative edits scoped to narrative body blocks instead of raw byte
	// ranges that might now contain inline fields or child sections.
	prev := normalizeNarrativeMarkdown(op.PreviousMarkdown)
	var exact *NodeBodyBlock
	candidates := make([]*NodeBodyBlock, 0)
	for i := range blocks {
		block := &blocks[i]
		if block.Kind != NodeBodyBlockKindNarrative {
			continue
		}
		if block.Range.Start == op.Range.Start && block.Range.End == op.Range.End {
			exact = block
		}
		if prev == "" || normalizeNarrativeMarkdown(block.Markdown) == prev {
			candidates = append(candidates, block)
		}
	}
	if exact != nil && (prev == "" || normalizeNarrativeMarkdown(exact.Markdown) == prev) {
		return exact, nil
	}
	if len(candidates) == 1 {
		return candidates[0], nil
	}
	if len(candidates) > 1 {
		best := candidates[0]
		bestDistance := absInt(best.Range.Start - op.Range.Start)
		for _, candidate := range candidates[1:] {
			distance := absInt(candidate.Range.Start - op.Range.Start)
			if distance < bestDistance {
				best = candidate
				bestDistance = distance
			}
		}
		return best, nil
	}
	if exact != nil {
		return exact, nil
	}
	return nil, fmt.Errorf("%w: narrative block not found for %s", errMissingNode, op.Ref.String())
}

func normalizeNarrativeMarkdown(markdown string) string {
	return strings.TrimRight(markdown, " \t\n")
}

func preserveNarrativeSuffix(raw, markdown string) string {
	trimmedRaw := strings.TrimRight(raw, " \t\n")
	suffix := raw[len(trimmedRaw):]
	return normalizeNarrativeMarkdown(markdown) + suffix
}

func absInt(value int) int {
	if value < 0 {
		return -value
	}
	return value
}
