//go:build ignore

// This script encrypts API keys and generates the embedded blob for teamkeys.
// Invoked by scripts/teamkeys/release.py; stdout is encrypted Go source.
//
// Required environment variables:
//   - ATOMIC_RHIZOME_KEY: 32-byte base64-encoded encryption key
//   - VOYAGE_API_KEY: Voyage AI API key
//   - TYPESAFE_API_KEY: TypeSafe (Jev) API key

package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
)

type Keys struct {
	Voyage   string `json:"voyage"`
	TypeSafe string `json:"typesafe"`
}

func main() {
	unlockKey := os.Getenv("ATOMIC_RHIZOME_KEY")
	if unlockKey == "" {
		fmt.Fprintln(os.Stderr, "error: ATOMIC_RHIZOME_KEY not set")
		os.Exit(1)
	}

	voyageKey := strings.Trim(os.Getenv("VOYAGE_API_KEY"), "\"")
	if voyageKey == "" {
		fmt.Fprintln(os.Stderr, "error: VOYAGE_API_KEY not set")
		os.Exit(1)
	}

	typesafeKey := strings.TrimSpace(os.Getenv("TYPESAFE_API_KEY"))
	if typesafeKey == "" {
		fmt.Fprintln(os.Stderr, "error: TYPESAFE_API_KEY not set")
		os.Exit(1)
	}

	// Decode the unlock key
	keyBytes, err := base64.StdEncoding.DecodeString(unlockKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error decoding unlock key: %v\n", err)
		os.Exit(1)
	}
	if len(keyBytes) != 32 {
		fmt.Fprintf(os.Stderr, "error: unlock key must be 32 bytes (got %d)\n", len(keyBytes))
		os.Exit(1)
	}

	// Marshal the keys to JSON
	keys := Keys{
		Voyage:   voyageKey,
		TypeSafe: typesafeKey,
	}
	plaintext, err := json.Marshal(keys)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling keys: %v\n", err)
		os.Exit(1)
	}

	// Encrypt with AES-GCM
	block, err := aes.NewCipher(keyBytes)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating cipher: %v\n", err)
		os.Exit(1)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating GCM: %v\n", err)
		os.Exit(1)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		fmt.Fprintf(os.Stderr, "error generating nonce: %v\n", err)
		os.Exit(1)
	}

	ciphertext := gcm.Seal(nonce, nonce, plaintext, nil)
	encoded := "rhizome-internal-keys-v1:" + base64.StdEncoding.EncodeToString(ciphertext)

	// Generate Go source file
	goSource := fmt.Sprintf(`// Code generated by scripts/teamkeys/encrypt.go. DO NOT EDIT.

package teamkeys

// encryptedKeys contains AES-256-GCM encrypted API keys.
// Decrypt with ATOMIC_RHIZOME_KEY environment variable.
var encryptedKeys = %q
`, encoded)

	// The release wrapper captures stdout and writes only to a temporary overlay.
	fmt.Print(goSource)
}
