package indexingperf

import (
	"context"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestCollectorRenderWindowTracksDeltasOnce(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	ctx = WithPhase(ctx, "embed_notes")

	AddCount(ctx, "fs.read", 3)
	AddCount(ctx, "semantic.chunks", 5)
	AddCount(ctx, "provider.calls", 2)
	AddCount(ctx, "provider.texts", 9)
	AddCount(ctx, "fs.discovered", 4)
	AddCount(ctx, "fs.completed", 3)
	AddCount(ctx, "node.prepare.in", 2)
	AddCount(ctx, "node.prepare.out", 2)
	AddCount(ctx, "node.embed.in", 9)
	AddCount(ctx, "node.embed.out", 9)
	AddCount(ctx, "node.write.in", 4)
	AddCount(ctx, "node.write.out", 4)
	ObserveLatency(ctx, "codeembed.prepare", 6*time.Millisecond)
	ObserveLatency(ctx, "node.prepare.busy", 5*time.Millisecond)
	ObserveLatency(ctx, "node.prepare.blocked", 2*time.Millisecond)
	ObserveLatency(ctx, "node.embed.starved", 7*time.Millisecond)
	ObserveLatency(ctx, "node.embed.pack_wait", 3*time.Millisecond)
	ObserveLatency(ctx, "node.embed.free_slots_under_mintexts", 3*time.Millisecond)
	ObserveLatency(ctx, "provider.latency", 12*time.Millisecond)
	ObserveLatency(ctx, "codeembed.hash_prefetch", 4*time.Millisecond)
	ObserveLatency(ctx, "plan.load_anchor_meta", 5*time.Millisecond)
	ObserveLatency(ctx, "plan.load_anchors", 6*time.Millisecond)
	ObserveLatency(ctx, "plan.load_anchors_by_path", 7*time.Millisecond)
	ObserveLatency(ctx, "plan.list_items", 8*time.Millisecond)
	ObserveLatency(ctx, "plan.item_embedding_states", 9*time.Millisecond)
	ObserveLatency(ctx, "plan.call_lookup_files", 10*time.Millisecond)
	ObserveLatency(ctx, "plan.call_lookup_owners", 11*time.Millisecond)
	ObserveLatency(ctx, "noteplan.load_doc_section_meta", 12*time.Millisecond)
	ObserveLatency(ctx, "noteplan.load_doc_sections", 13*time.Millisecond)
	ObserveLatency(ctx, "noteplan.load_doc_sections_by_path", 14*time.Millisecond)
	ObserveLatency(ctx, "noteplan.load_titles", 15*time.Millisecond)
	ObserveLatency(ctx, "noteplan.chunk_hashes_batch", 16*time.Millisecond)
	ObserveLatency(ctx, "noteplan.chunk_hash_lookup", 17*time.Millisecond)
	ObserveLatency(ctx, "noteplan.build_chunks", 18*time.Millisecond)
	ObserveLatency(ctx, "noteplan.plan_chunk_updates", 19*time.Millisecond)
	ObserveLatency(ctx, "noteplan.load_stored_chunks", 20*time.Millisecond)
	ObserveLatency(ctx, "noteplan.cache_lookup", 21*time.Millisecond)
	ObserveLatency(ctx, "noteplan.meta_submit", 22*time.Millisecond)
	ObserveLatency(ctx, "noteplan.meta_flush_wait", 23*time.Millisecond)
	ObserveLatency(ctx, "noteembed.prepare", 4*time.Millisecond)
	ObserveLatency(ctx, "noteembed.finalize", 24*time.Millisecond)
	ObserveLatency(ctx, "noteembed.finalize.writeback_submit", 24*time.Millisecond)
	ObserveLatency(ctx, "noteembed.finalize.write_chunks", 25*time.Millisecond)
	ObserveLatency(ctx, "noteembed.finalize.write_intel", 26*time.Millisecond)
	ObserveLatency(ctx, "noteemb.sync_note_chunks.lookup_note_row", 27*time.Millisecond)
	ObserveLatency(ctx, "noteemb.sync_note_chunks.upsert_cache", 28*time.Millisecond)
	ObserveLatency(ctx, "noteemb.sync_note_chunks.upsert_rows", 29*time.Millisecond)
	ObserveLatency(ctx, "noteemb.sync_note_chunks.delete_stale", 30*time.Millisecond)
	ObserveLatency(ctx, "noteembed.writeback.flush_wait", 28*time.Millisecond)
	ObserveLatency(ctx, "noteplan.writeback.meta.submit_wait", 6*time.Millisecond)
	ObserveLatency(ctx, "noteplan.writeback.meta.flush", 7*time.Millisecond)
	AddCount(ctx, "noteplan.writeback.meta.flush.count", 2)
	ObserveSample(ctx, "noteplan.writeback.meta.batch_rows", 11)
	ObserveSample(ctx, "noteplan.writeback.meta.batch_bytes", 768)
	SetGauge(ctx, "noteplan.writeback.meta.queue_depth", 8)
	SetGauge(ctx, "noteplan.writeback.meta.queue_depth", 3)
	ObserveLatency(ctx, "noteembed.writeback.chunk.submit_wait", 8*time.Millisecond)
	ObserveLatency(ctx, "noteembed.writeback.chunk.flush", 9*time.Millisecond)
	AddCount(ctx, "noteembed.writeback.chunk.flush.count", 2)
	ObserveSample(ctx, "noteembed.writeback.chunk.batch_rows", 12)
	ObserveSample(ctx, "noteembed.writeback.chunk.batch_bytes", 1792)
	SetGauge(ctx, "noteembed.writeback.chunk.queue_depth", 9)
	SetGauge(ctx, "noteembed.writeback.chunk.queue_depth", 4)
	ObserveLatency(ctx, "noteembed.writeback.intel.submit_wait", 10*time.Millisecond)
	ObserveLatency(ctx, "noteembed.writeback.intel.flush", 11*time.Millisecond)
	AddCount(ctx, "noteembed.writeback.intel.flush.count", 2)
	ObserveSample(ctx, "noteembed.writeback.intel.batch_rows", 18)
	ObserveSample(ctx, "noteembed.writeback.intel.batch_bytes", 2560)
	SetGauge(ctx, "noteembed.writeback.intel.queue_depth", 10)
	SetGauge(ctx, "noteembed.writeback.intel.queue_depth", 5)
	ObserveLatency(ctx, "embed.gate_wait", 4*time.Millisecond)
	ObserveLatency(ctx, "db.wait", 7*time.Millisecond)
	ObserveLatency(ctx, "fs.walk", 8*time.Millisecond)
	ObserveLatency(ctx, "fs.stat", 2*time.Millisecond)
	ObserveLatency(ctx, "fs.read_latency", 9*time.Millisecond)
	ObserveLatency(ctx, "node.write.starved", 11*time.Millisecond)
	ObserveLatency(ctx, "node.write.busy", 13*time.Millisecond)
	ObserveLatency(ctx, "node.write.deferred", 17*time.Millisecond)
	ObserveLatency(ctx, "embed.queue_age", 10*time.Millisecond)
	ObserveLatency(ctx, "embed.queue_age", 14*time.Millisecond)
	ObserveLatency(ctx, "embed.batch_oldest_age", 14*time.Millisecond)
	ObserveLatency(ctx, "provider.dispatch_idle", 6*time.Millisecond)
	ObserveSample(ctx, "provider.batch_texts", 4)
	ObserveSample(ctx, "provider.batch_texts", 8)
	ObserveSample(ctx, "provider.batch_bytes", 400)
	ObserveSample(ctx, "provider.batch_bytes", 1200)
	AddCount(ctx, "codeembed.hash_prefetch.calls", 1)
	AddCount(ctx, "codeembed.hash_prefetch.hashes", 5)
	AddCount(ctx, "codeembed.hash_prefetch.hits", 3)
	AddCount(ctx, "codeembed.reuse_mem.hit", 7)
	AddCount(ctx, "codeembed.reuse_mem.miss", 2)
	ObserveSample(ctx, "codeembed.hash_prefetch.batch", 5)
	AddCount(ctx, "calledge.flush.count", 1)
	ObserveSample(ctx, "calledge.flush.paths", 12)
	ObserveSample(ctx, "calledge.flush.work", 18)
	SetGauge(ctx, "embed.ready_depth", 5)
	SetGauge(ctx, "embed.ready_depth", 3)
	SetGauge(ctx, "provider.inflight", 3)
	SetGauge(ctx, "provider.inflight", 1)
	SetGauge(ctx, "queue.depth", 4)
	SetGauge(ctx, "queue.depth", 2)
	ObserveLatency(ctx, "codeindex.result_submit_wait", 4*time.Millisecond)
	ObserveLatency(ctx, "codeindex.result_reduce", 6*time.Millisecond)
	ObserveLatency(ctx, "codeindex.result_reduce_indexed", 2*time.Millisecond)
	ObserveLatency(ctx, "codeindex.result_reduce_touched", 1*time.Millisecond)
	ObserveLatency(ctx, "codeindex.result_reduce_changed_callers", 3*time.Millisecond)
	ObserveLatency(ctx, "codeindex.result_reduce_defdeltas", 5*time.Millisecond)
	ObserveLatency(ctx, "codeindex.result_finalize", 7*time.Millisecond)
	SetGauge(ctx, "codeindex.result_queue_depth", 6)
	SetGauge(ctx, "codeindex.result_queue_depth", 2)
	ObserveLatency(ctx, "codeembed.writeback.item.submit_wait", 3*time.Millisecond)
	ObserveLatency(ctx, "codeembed.writeback.item.flush", 9*time.Millisecond)
	AddCount(ctx, "codeembed.writeback.item.flush.count", 2)
	ObserveSample(ctx, "codeembed.writeback.item.batch_rows", 4)
	ObserveSample(ctx, "codeembed.writeback.item.batch_bytes", 512)
	SetGauge(ctx, "codeembed.writeback.item.queue_depth", 5)
	SetGauge(ctx, "codeembed.writeback.item.queue_depth", 1)
	ObserveLatency(ctx, "codeembed.writeback.chunk.submit_wait", 4*time.Millisecond)
	ObserveLatency(ctx, "codeembed.writeback.chunk.flush", 10*time.Millisecond)
	AddCount(ctx, "codeembed.writeback.chunk.flush.count", 1)
	ObserveSample(ctx, "codeembed.writeback.chunk.batch_rows", 8)
	ObserveSample(ctx, "codeembed.writeback.chunk.batch_bytes", 1536)
	SetGauge(ctx, "codeembed.writeback.chunk.queue_depth", 6)
	SetGauge(ctx, "codeembed.writeback.chunk.queue_depth", 2)
	ObserveLatency(ctx, "codeembed.writeback.intel.submit_wait", 5*time.Millisecond)
	ObserveLatency(ctx, "codeembed.writeback.intel.flush", 11*time.Millisecond)
	AddCount(ctx, "codeembed.writeback.intel.flush.count", 3)
	ObserveSample(ctx, "codeembed.writeback.intel.batch_rows", 16)
	ObserveSample(ctx, "codeembed.writeback.intel.batch_bytes", 2048)
	SetGauge(ctx, "codeembed.writeback.intel.queue_depth", 7)
	SetGauge(ctx, "codeembed.writeback.intel.queue_depth", 3)

	first := FromContext(ctx).RenderWindow(10 * time.Second)
	require.Contains(t, first, "[index-perf]")
	require.Contains(t, first, "phase=embed_notes")
	require.Contains(t, first, "files=3")
	require.Contains(t, first, "discovered=4")
	require.Contains(t, first, "completed=3")
	require.Contains(t, first, "chunks=5")
	require.Contains(t, first, "calls=2")
	require.Contains(t, first, "texts=9")
	require.Contains(t, first, "avg_texts_call=4.5")
	require.Contains(t, first, "files_s=0.3")
	require.Contains(t, first, "chunks_s=0.5")
	require.Contains(t, first, "calls_s=0.2")
	require.Contains(t, first, "texts_s=0.9")
	require.Contains(t, first, "prepare_busy_ms=5")
	require.Contains(t, first, "prepare_blocked_ms=2")
	require.Contains(t, first, "embed_starved_ms=7")
	require.Contains(t, first, "embed_pack_wait_ms=3")
	require.Contains(t, first, "free_slots_under_mintexts_ms=3")
	require.Contains(t, first, "prep_cum_ms=10")
	require.Contains(t, first, "walk_cum_ms=8")
	require.Contains(t, first, "stat_cum_ms=2")
	require.Contains(t, first, "read_cum_ms=9")
	require.Contains(t, first, "provider_cum_ms=12")
	require.Contains(t, first, "hash_prefetch_cum_ms=4")
	require.Contains(t, first, "load_anchor_meta_cum_ms=5")
	require.Contains(t, first, "load_anchors_cum_ms=6")
	require.Contains(t, first, "load_anchors_by_path_cum_ms=7")
	require.Contains(t, first, "list_items_cum_ms=8")
	require.Contains(t, first, "item_embedding_states_cum_ms=9")
	require.Contains(t, first, "call_lookup_files_cum_ms=10")
	require.Contains(t, first, "call_lookup_owners_cum_ms=11")
	require.Contains(t, first, "load_doc_section_meta_cum_ms=12")
	require.Contains(t, first, "load_doc_sections_cum_ms=13")
	require.Contains(t, first, "load_doc_sections_by_path_cum_ms=14")
	require.Contains(t, first, "load_titles_cum_ms=15")
	require.Contains(t, first, "chunk_hashes_batch_cum_ms=16")
	require.Contains(t, first, "chunk_hash_lookup_cum_ms=17")
	require.Contains(t, first, "build_chunks_cum_ms=18")
	require.Contains(t, first, "plan_chunk_updates_cum_ms=19")
	require.Contains(t, first, "load_stored_chunks_cum_ms=20")
	require.Contains(t, first, "cache_lookup_cum_ms=21")
	require.Contains(t, first, "meta_submit_cum_ms=22")
	require.Contains(t, first, "meta_flush_wait_cum_ms=23")
	require.Contains(t, first, "gate_wait_cum_ms=4")
	require.Contains(t, first, "db_wait_cum_ms=7")
	require.Contains(t, first, "writer_idle_ms=11")
	require.Contains(t, first, "writer_busy_ms=13")
	require.Contains(t, first, "writer_deferred_ms=17")
	require.Contains(t, first, "result_submit_cum_ms=4")
	require.Contains(t, first, "result_reduce_cum_ms=6")
	require.Contains(t, first, "result_reduce_indexed_cum_ms=2")
	require.Contains(t, first, "result_reduce_touched_cum_ms=1")
	require.Contains(t, first, "result_reduce_changed_callers_cum_ms=3")
	require.Contains(t, first, "result_reduce_defdeltas_cum_ms=5")
	require.Contains(t, first, "result_finalize_cum_ms=7")
	require.Contains(t, first, "queue_depth_avg=3.0")
	require.Contains(t, first, "result_queue_depth_peak=6")
	require.Contains(t, first, "result_queue_depth_avg=4.0")
	require.Contains(t, first, "writeback_item_submit_wait_cum_ms=3")
	require.Contains(t, first, "writeback_item_flushes=2")
	require.Contains(t, first, "writeback_item_batch_rows_p50=4")
	require.Contains(t, first, "writeback_item_batch_bytes_p50=512B")
	require.Contains(t, first, "writeback_item_queue_depth_peak=5")
	require.Contains(t, first, "writeback_chunk_submit_wait_cum_ms=4")
	require.Contains(t, first, "writeback_chunk_flushes=1")
	require.Contains(t, first, "writeback_chunk_batch_rows_p50=8")
	require.Contains(t, first, "writeback_chunk_batch_bytes_p50=1.5KiB")
	require.Contains(t, first, "writeback_chunk_queue_depth_peak=6")
	require.Contains(t, first, "writeback_intel_submit_wait_cum_ms=5")
	require.Contains(t, first, "writeback_intel_flushes=3")
	require.Contains(t, first, "writeback_intel_batch_rows_p50=16")
	require.Contains(t, first, "writeback_intel_batch_bytes_p50=2.0KiB")
	require.Contains(t, first, "writeback_intel_queue_depth_peak=7")
	require.Contains(t, first, "finalize_cum_ms=24")
	require.Contains(t, first, "finalize_writeback_submit_cum_ms=24")
	require.Contains(t, first, "finalize_write_chunks_cum_ms=25")
	require.Contains(t, first, "finalize_write_intel_cum_ms=26")
	require.Contains(t, first, "sync_note_chunks_lookup_note_row_cum_ms=27")
	require.Contains(t, first, "sync_note_chunks_upsert_cache_cum_ms=28")
	require.Contains(t, first, "sync_note_chunks_upsert_rows_cum_ms=29")
	require.Contains(t, first, "sync_note_chunks_delete_stale_cum_ms=30")
	require.Contains(t, first, "writeback_flush_wait_cum_ms=28")
	require.Contains(t, first, "writeback_meta_submit_wait_cum_ms=6")
	require.Contains(t, first, "writeback_meta_flushes=2")
	require.Contains(t, first, "writeback_meta_batch_rows_p50=11")
	require.Contains(t, first, "writeback_meta_batch_bytes_p50=768B")
	require.Contains(t, first, "writeback_meta_queue_depth_peak=8")
	require.Contains(t, first, "writeback_note_chunk_submit_wait_cum_ms=8")
	require.Contains(t, first, "writeback_note_chunk_flushes=2")
	require.Contains(t, first, "writeback_note_chunk_batch_rows_p50=12")
	require.Contains(t, first, "writeback_note_chunk_batch_bytes_p50=1.8KiB")
	require.Contains(t, first, "writeback_note_chunk_queue_depth_peak=9")
	require.Contains(t, first, "writeback_note_intel_submit_wait_cum_ms=10")
	require.Contains(t, first, "writeback_note_intel_flushes=2")
	require.Contains(t, first, "writeback_note_intel_batch_rows_p50=18")
	require.Contains(t, first, "writeback_note_intel_batch_bytes_p50=2.5KiB")
	require.Contains(t, first, "writeback_note_intel_queue_depth_peak=10")
	require.Contains(t, first, "ready_depth_peak=5")
	require.Contains(t, first, "ready_depth_avg=4.0")
	require.Contains(t, first, "provider_inflight_peak=3")
	require.Contains(t, first, "provider_inflight_avg=2.0")
	require.Contains(t, first, "embed_queue_age_avg_ms=12")
	require.Contains(t, first, "embed_queue_age_max_ms=14")
	require.Contains(t, first, "embed_batch_oldest_max_ms=14")
	require.Contains(t, first, "dispatch_idle_ms=6")
	require.Contains(t, first, "batch_texts_p50=4")
	require.Contains(t, first, "batch_texts_p95=8")
	require.Contains(t, first, "batch_bytes_p50=400B")
	require.Contains(t, first, "batch_bytes_p95=1.2KiB")
	require.Contains(t, first, "hash_prefetch_calls=1")
	require.Contains(t, first, "hash_prefetch_hashes=5")
	require.Contains(t, first, "hash_prefetch_hits=3")
	require.Contains(t, first, "hash_prefetch_batch_p50=5")
	require.Contains(t, first, "reuse_mem_hits=7")
	require.Contains(t, first, "reuse_mem_misses=2")
	require.Contains(t, first, "calledge_flushes=1")
	require.Contains(t, first, "calledge_paths_p50=12")
	require.Contains(t, first, "calledge_work_p50=18")
	require.NotContains(t, first, "calledge_source_fallback_runtime_missing_refs=")
	require.NotContains(t, first, "calledge_source_fallback_runtime_parse_untrusted=")
	require.NotContains(t, first, "calledge_source_fallback_no_authoritative_inputs=")
	require.Contains(t, first, "prepare_tasks_in=2")
	require.Contains(t, first, "prepare_tasks_out=2")
	require.Contains(t, first, "embed_texts_in=9")
	require.Contains(t, first, "embed_texts_out=9")
	require.Contains(t, first, "writer_cmds_in=4")
	require.Contains(t, first, "writer_rows_out=4")

	SetGauge(ctx, "provider.inflight", 0)
	second := FromContext(ctx).RenderWindow(10 * time.Second)
	require.Empty(t, second)
}

func TestCollectorRenderSummaryIncludesPhaseDetails(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "embed_code")
	AddCount(phaseCtx, "semantic.chunks", 9)
	AddCount(phaseCtx, "semantic.code_plan.kind.function", 4)
	AddCount(phaseCtx, "semantic.code_plan.granularity.anchor", 4)
	AddCount(phaseCtx, "semantic.code_chunks.kind.function", 3)
	AddCount(phaseCtx, "semantic.code_chunks.granularity.anchor", 3)
	AddCount(phaseCtx, "ontology_nodes.body_chunks_planned", 2)
	AddCount(phaseCtx, "fs.discovered", 12)
	AddCount(phaseCtx, "fs.completed", 9)
	AddCount(phaseCtx, "node.prepare.in", 3)
	AddCount(phaseCtx, "node.prepare.out", 3)
	AddCount(phaseCtx, "node.embed.in", 12)
	AddCount(phaseCtx, "node.embed.out", 12)
	AddCount(phaseCtx, "node.write.in", 5)
	AddCount(phaseCtx, "node.write.out", 5)
	AddCount(phaseCtx, "provider.calls", 3)
	AddCount(phaseCtx, "provider.texts", 12)
	AddCount(phaseCtx, "provider.logical_texts", 14)
	AddBytes(phaseCtx, "provider.text", 1200)
	ObserveLatency(phaseCtx, "codeembed.prepare", 9*time.Millisecond)
	ObserveLatency(phaseCtx, "fs.walk", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "fs.stat", 3*time.Millisecond)
	ObserveLatency(phaseCtx, "fs.read_latency", 2*time.Millisecond)
	ObserveLatency(phaseCtx, "node.prepare.busy", 11*time.Millisecond)
	ObserveLatency(phaseCtx, "node.prepare.blocked", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "node.embed.starved", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "node.embed.pack_wait", 2*time.Millisecond)
	ObserveLatency(phaseCtx, "node.embed.free_slots_under_mintexts", 2*time.Millisecond)
	ObserveLatency(phaseCtx, "provider.latency", 20*time.Millisecond)
	ObserveLatency(phaseCtx, "codeembed.hash_prefetch", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.load_anchor_meta", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.load_anchors", 7*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.load_anchors_by_path", 8*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.list_items", 9*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.item_embedding_states", 10*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.call_lookup_files", 11*time.Millisecond)
	ObserveLatency(phaseCtx, "plan.call_lookup_owners", 12*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.gate_wait", 3*time.Millisecond)
	ObserveLatency(phaseCtx, "queue.wait", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "node.write.busy", 7*time.Millisecond)
	ObserveLatency(phaseCtx, "node.write.deferred", 9*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.queue_age", 8*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.queue_age", 12*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.batch_oldest_age", 12*time.Millisecond)
	ObserveLatency(phaseCtx, "provider.dispatch_idle", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.submit_wait", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.future_wait", 19*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.node_pack_wait", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "embed.node_slots_wait", 7*time.Millisecond)
	ObserveSample(phaseCtx, "provider.batch_texts", 4)
	ObserveSample(phaseCtx, "provider.batch_texts", 8)
	ObserveSample(phaseCtx, "provider.batch_bytes", 400)
	ObserveSample(phaseCtx, "provider.batch_bytes", 800)
	ObserveSample(phaseCtx, "provider.input_texts", 5)
	ObserveSample(phaseCtx, "provider.input_texts", 10)
	ObserveSample(phaseCtx, "provider.input_bytes", 500)
	ObserveSample(phaseCtx, "provider.input_bytes", 1000)
	ObserveSample(phaseCtx, "provider.cap_texts", 10)
	ObserveSample(phaseCtx, "provider.dispatch_floor_texts", 4)
	ObserveSample(phaseCtx, "provider.capacity", 32)
	ObserveSample(phaseCtx, "provider.batch_fill_ratio", 80)
	ObserveSample(phaseCtx, "provider.bytes_fill_ratio", 25)
	AddCount(phaseCtx, "provider.mixed_batches", 2)
	AddCount(phaseCtx, "embed.dedupe.saved", 2)
	AddCount(phaseCtx, "embed.dedupe.saved_bytes", 200)
	ObserveSample(phaseCtx, "codeembed.hash_prefetch.batch", 6)
	AddCount(phaseCtx, "codeembed.hash_prefetch.calls", 2)
	AddCount(phaseCtx, "codeembed.hash_prefetch.hashes", 12)
	AddCount(phaseCtx, "codeembed.hash_prefetch.hits", 9)
	AddCount(phaseCtx, "codeembed.reuse_mem.hit", 10)
	AddCount(phaseCtx, "codeembed.reuse_mem.miss", 3)
	AddCount(phaseCtx, "codeembed.need.item_hash_mismatch", 4)
	AddCount(phaseCtx, "codeembed.state.fingerprint_mismatch", 5)
	ObserveInterval(phaseCtx, "embed.ready_state.empty", time.Now(), 3*time.Millisecond)
	ObserveInterval(phaseCtx, "embed.ready_state.nonzero", time.Now(), 17*time.Millisecond)
	ObserveInterval(phaseCtx, "provider.slots.1_2", time.Now(), 4*time.Millisecond)
	ObserveInterval(phaseCtx, "provider.slots.3_6", time.Now(), 9*time.Millisecond)
	AddCount(phaseCtx, "calledge.flush.count", 2)
	ObserveSample(phaseCtx, "calledge.flush.paths", 32)
	ObserveSample(phaseCtx, "calledge.flush.paths", 96)
	ObserveSample(phaseCtx, "calledge.flush.work", 40)
	ObserveSample(phaseCtx, "calledge.flush.work", 144)
	ObserveLatency(phaseCtx, "codeindex.parse", 13*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.hashcheck", 2*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.normalize", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.intel", 7*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.rationale", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.doclinks", 8*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.refs", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.defdeltas", 3*time.Millisecond)
	ObserveLatency(phaseCtx, "process.code", 17*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.file_queue_wait", 19*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.file_enqueue_wait", 15*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_submit_wait", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_reduce", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_reduce_indexed", 2*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_reduce_touched", 1*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_reduce_changed_callers", 3*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_reduce_defdeltas", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.result_finalize", 7*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.semantic_submit_wait", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.write_submit_wait", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.write_drain_wait", 21*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.write_flush_wait", 23*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.semantic_drain_wait", 18*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_service", 30*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_build", 12*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_submit_local", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_submit_semantic", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_submit_write", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_submit", 15*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.worker_total", 45*time.Millisecond)
	ObserveLatency(phaseCtx, "codeembed.writeback.item.submit_wait", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "codeembed.writeback.item.flush", 8*time.Millisecond)
	AddCount(phaseCtx, "codeembed.writeback.item.flush.count", 2)
	ObserveSample(phaseCtx, "codeembed.writeback.item.batch_rows", 5)
	ObserveSample(phaseCtx, "codeembed.writeback.item.batch_bytes", 600)
	ObserveLatency(phaseCtx, "codeembed.writeback.chunk.submit_wait", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "codeembed.writeback.chunk.flush", 9*time.Millisecond)
	AddCount(phaseCtx, "codeembed.writeback.chunk.flush.count", 1)
	ObserveSample(phaseCtx, "codeembed.writeback.chunk.batch_rows", 9)
	ObserveSample(phaseCtx, "codeembed.writeback.chunk.batch_bytes", 1600)
	ObserveLatency(phaseCtx, "codeembed.writeback.intel.submit_wait", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "codeembed.writeback.intel.flush", 10*time.Millisecond)
	AddCount(phaseCtx, "codeembed.writeback.intel.flush.count", 3)
	ObserveSample(phaseCtx, "codeembed.writeback.intel.batch_rows", 18)
	ObserveSample(phaseCtx, "codeembed.writeback.intel.batch_bytes", 2200)
	ObserveLatency(phaseCtx, "codepersist.apply", 15*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.summary_meta", 9*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.doclinks", 8*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.sqlite_batch", 11*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.refs", 10*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.intel", 12*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.rationale", 13*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.writer_apply", 14*time.Millisecond)
	ObserveLatency(phaseCtx, "codepersist.writer_after", 16*time.Millisecond)
	SetGauge(phaseCtx, "provider.inflight", 4)
	SetGauge(phaseCtx, "provider.inflight", 2)
	SetGauge(phaseCtx, "embed.ready_depth", 17)
	SetGauge(phaseCtx, "embed.ready_depth", 9)
	SetGauge(phaseCtx, "queue.depth", 7)
	SetGauge(phaseCtx, "queue.depth", 5)
	SetGauge(phaseCtx, "codeindex.semantic_queue_depth", 6)
	SetGauge(phaseCtx, "codeindex.semantic_queue_depth", 2)
	SetGauge(phaseCtx, "codeindex.result_queue_depth", 5)
	SetGauge(phaseCtx, "codeindex.result_queue_depth", 1)
	SetGauge(phaseCtx, "codeembed.writeback.item.queue_depth", 4)
	SetGauge(phaseCtx, "codeembed.writeback.item.queue_depth", 2)
	SetGauge(phaseCtx, "codeembed.writeback.chunk.queue_depth", 5)
	SetGauge(phaseCtx, "codeembed.writeback.chunk.queue_depth", 3)
	SetGauge(phaseCtx, "codeembed.writeback.intel.queue_depth", 6)
	SetGauge(phaseCtx, "codeembed.writeback.intel.queue_depth", 2)
	totalCtx := WithPhase(ctx, "total")
	ObserveLatency(totalCtx, "node.write.starved", 8*time.Millisecond)
	FromContext(ctx).RecordSpan("embed_code", 20*time.Millisecond, nil)
	FromContext(ctx).RecordSpan("plan_code_embeddings", 10*time.Millisecond, nil)
	FromContext(ctx).RecordSpan("total", 50*time.Millisecond, nil)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "Index timings:")
	require.Contains(t, summary, "embed_code")
	require.Contains(t, summary, "discovery=9/12")
	require.Contains(t, summary, "chunks=9")
	require.Contains(t, summary, "code_plan_kind=function:4")
	require.Contains(t, summary, "code_plan_granularity=anchor:4")
	require.Contains(t, summary, "code_embedded_kind=function:3")
	require.Contains(t, summary, "code_embedded_granularity=anchor:3")
	require.Contains(t, summary, "ontology_body_chunks_planned=2")
	require.Contains(t, summary, "calls=3")
	require.Contains(t, summary, "texts=12")
	require.Contains(t, summary, "logical_texts=14")
	require.Contains(t, summary, "calls_needed_at_provider_cap=2")
	require.Contains(t, summary, "calls_needed_at_dispatch_floor=4")
	require.Contains(t, summary, "avg_texts/call=4.0")
	require.Contains(t, summary, "avg_bytes/call=400B")
	require.Contains(t, summary, "mixed_batches=2")
	require.Contains(t, summary, "dedupe_saved=2")
	require.Contains(t, summary, "dedupe_saved_bytes=200B")
	require.Contains(t, summary, "chunks/s=450.0")
	require.Contains(t, summary, "calls/s=150.0")
	require.Contains(t, summary, "texts/s=600.0")
	require.Contains(t, summary, "prep_cum=9ms")
	require.Contains(t, summary, "walk_cum=4ms")
	require.Contains(t, summary, "stat_cum=3ms")
	require.Contains(t, summary, "read_cum=2ms")
	require.Contains(t, summary, "prepare_busy=11ms")
	require.Contains(t, summary, "prepare_blocked=4ms")
	require.Contains(t, summary, "embed_starved=6ms")
	require.Contains(t, summary, "embed_pack_wait=2ms")
	require.Contains(t, summary, "embed_submit_wait=4ms")
	require.Contains(t, summary, "future_wait=19ms")
	require.Contains(t, summary, "node_pack_wait=6ms")
	require.Contains(t, summary, "node_slots_wait=7ms")
	require.Contains(t, summary, "free_slots_under_mintexts=2ms")
	require.Contains(t, summary, "provider_cum=20ms")
	require.Contains(t, summary, "provider_latency_p50=20ms")
	require.Contains(t, summary, "provider_latency_p95=20ms")
	require.Contains(t, summary, "provider_latency_max=20ms")
	require.Contains(t, summary, "future_wait_p50=19ms")
	require.Contains(t, summary, "future_wait_p95=19ms")
	require.Contains(t, summary, "future_wait_max=19ms")
	require.Contains(t, summary, "dispatch_idle=5ms")
	require.Contains(t, summary, "hash_prefetch_cum=5ms")
	require.Contains(t, summary, "load_anchor_meta_cum=6ms")
	require.Contains(t, summary, "load_anchors_cum=7ms")
	require.Contains(t, summary, "load_anchors_by_path_cum=8ms")
	require.Contains(t, summary, "list_items_cum=9ms")
	require.Contains(t, summary, "item_embedding_states_cum=10ms")
	require.Contains(t, summary, "call_lookup_files_cum=11ms")
	require.Contains(t, summary, "call_lookup_owners_cum=12ms")
	require.Contains(t, summary, "gate_wait_cum=3ms")
	require.Contains(t, summary, "queue_wait_cum=5ms")
	require.Contains(t, summary, "writer_busy=7ms")
	require.Contains(t, summary, "writer_deferred=9ms")
	require.Contains(t, summary, "provider_inflight_peak=4")
	require.Contains(t, summary, "provider_inflight_avg=3.0")
	require.Contains(t, summary, "batch_texts_p50=4")
	require.Contains(t, summary, "batch_texts_p95=8")
	require.Contains(t, summary, "batch_bytes_p50=400B")
	require.Contains(t, summary, "batch_bytes_p95=800B")
	require.Contains(t, summary, "input_texts_p50=5")
	require.Contains(t, summary, "input_texts_p95=10")
	require.Contains(t, summary, "input_bytes_p50=500B")
	require.Contains(t, summary, "input_bytes_p95=1000B")
	require.Contains(t, summary, "provider_capacity_max=32")
	require.Contains(t, summary, "batch_fill_ratio_max=80%")
	require.Contains(t, summary, "bytes_fill_ratio_max=25%")
	require.Contains(t, summary, "hash_prefetch_calls=2")
	require.Contains(t, summary, "hash_prefetch_hashes=12")
	require.Contains(t, summary, "hash_prefetch_hits=9")
	require.Contains(t, summary, "hash_prefetch_batch_p50=6")
	require.Contains(t, summary, "reuse_mem_hits=10")
	require.Contains(t, summary, "reuse_mem_misses=3")
	require.Contains(t, summary, "need_item_hash_mismatch=4")
	require.Contains(t, summary, "state_fingerprint_mismatch=5")
	require.Contains(t, summary, "ready_depth_peak=17")
	require.Contains(t, summary, "ready_depth_avg=13.0")
	require.Contains(t, summary, "ready_empty=3ms")
	require.Contains(t, summary, "ready_nonzero=17ms")
	require.Contains(t, summary, "slots_1_2=4ms")
	require.Contains(t, summary, "slots_3_6=9ms")
	require.Contains(t, summary, "calledge_flushes=2")
	require.Contains(t, summary, "calledge_paths_p50=32")
	require.Contains(t, summary, "calledge_paths_p95=96")
	require.Contains(t, summary, "calledge_work_p50=40")
	require.Contains(t, summary, "calledge_work_p95=144")
	require.Contains(t, summary, "parse_cum=13ms")
	require.Contains(t, summary, "hashcheck_cum=2ms")
	require.Contains(t, summary, "normalize_cum=4ms")
	require.Contains(t, summary, "intel_cum=7ms")
	require.Contains(t, summary, "rationale_cum=6ms")
	require.Contains(t, summary, "doclinks_cum=8ms")
	require.Contains(t, summary, "refs_cum=5ms")
	require.Contains(t, summary, "defdeltas_cum=3ms")
	require.Contains(t, summary, "process_cum=17ms")
	require.Contains(t, summary, "file_queue_wait_cum=19ms")
	require.Contains(t, summary, "file_enqueue_wait_cum=15ms")
	require.Contains(t, summary, "file_enqueue_wait_p50=15ms")
	require.Contains(t, summary, "result_submit_cum=5ms")
	require.Contains(t, summary, "result_submit_p50=5ms")
	require.Contains(t, summary, "result_reduce_cum=6ms")
	require.Contains(t, summary, "result_reduce_indexed_cum=2ms")
	require.Contains(t, summary, "result_reduce_touched_cum=1ms")
	require.Contains(t, summary, "result_reduce_changed_callers_cum=3ms")
	require.Contains(t, summary, "result_reduce_defdeltas_cum=4ms")
	require.Contains(t, summary, "result_finalize_cum=7ms")
	require.Contains(t, summary, "semantic_submit_cum=4ms")
	require.Contains(t, summary, "semantic_submit_p50=4ms")
	require.Contains(t, summary, "write_submit_cum=6ms")
	require.Contains(t, summary, "write_submit_p50=6ms")
	require.Contains(t, summary, "write_drain_cum=21ms")
	require.Contains(t, summary, "write_flush_cum=23ms")
	require.Contains(t, summary, "semantic_drain_cum=18ms")
	require.Contains(t, summary, "worker_service_cum=30ms")
	require.Contains(t, summary, "worker_build_cum=12ms")
	require.Contains(t, summary, "worker_submit_local_cum=5ms")
	require.Contains(t, summary, "worker_submit_semantic_cum=4ms")
	require.Contains(t, summary, "worker_submit_write_cum=6ms")
	require.Contains(t, summary, "worker_submit_cum=15ms")
	require.Contains(t, summary, "worker_total_cum=45ms")
	require.Contains(t, summary, "writeback_item_submit_wait_cum=4ms")
	require.Contains(t, summary, "writeback_item_flushes=2")
	require.Contains(t, summary, "writeback_item_batch_rows_p50=5")
	require.Contains(t, summary, "writeback_item_queue_depth_peak=4")
	require.Contains(t, summary, "writeback_chunk_submit_wait_cum=5ms")
	require.Contains(t, summary, "writeback_chunk_flushes=1")
	require.Contains(t, summary, "writeback_chunk_batch_rows_p50=9")
	require.Contains(t, summary, "writeback_chunk_queue_depth_peak=5")
	require.Contains(t, summary, "writeback_intel_submit_wait_cum=6ms")
	require.Contains(t, summary, "writeback_intel_flushes=3")
	require.Contains(t, summary, "writeback_intel_batch_rows_p50=18")
	require.Contains(t, summary, "writeback_intel_queue_depth_peak=6")
	require.Contains(t, summary, "persist_apply_cum=15ms")
	require.Contains(t, summary, "persist_summary_meta_cum=9ms")
	require.Contains(t, summary, "persist_doclinks_cum=8ms")
	require.Contains(t, summary, "persist_sqlite_batch_cum=11ms")
	require.Contains(t, summary, "persist_refs_cum=10ms")
	require.Contains(t, summary, "persist_intel_cum=12ms")
	require.Contains(t, summary, "persist_rationale_cum=13ms")
	require.Contains(t, summary, "writer_apply_cum=14ms")
	require.Contains(t, summary, "writer_after_cum=16ms")
	require.Contains(t, summary, "queue_depth_avg=6.0")
	require.Contains(t, summary, "semantic_queue_depth_peak=6")
	require.Contains(t, summary, "semantic_queue_depth_avg=4.0")
	require.Contains(t, summary, "result_queue_depth_peak=5")
	require.Contains(t, summary, "result_queue_depth_avg=3.0")
	require.Contains(t, summary, "embed_queue_age_avg=10ms")
	require.Contains(t, summary, "embed_queue_age_max=12ms")
	require.Contains(t, summary, "embed_batch_oldest_max=12ms")
	require.Contains(t, summary, "prepare_tasks=3/3")
	require.Contains(t, summary, "embed_texts=12/12")
	require.Contains(t, summary, "writer_cmds=5")
	require.Contains(t, summary, "writer_rows=5")
	require.Contains(t, summary, "Bottlenecks:")
	require.Contains(t, summary, "embed_code provider_busy=20ms")
	require.Contains(t, summary, "writer_idle=8ms")
	require.NotContains(t, summary, "writer_starved")
	require.Contains(t, summary, "embed_code enqueue_blocked=5ms")
	require.Contains(t, summary, "Overlaps:")
	require.Contains(t, summary, "Critical path walls:")
	require.False(t, strings.Contains(summary, "error"))
}

func TestCollectorRenderSummaryIncludesNotePhaseDetails(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "embed_notes")
	ObserveLatency(phaseCtx, "noteplan.load_doc_sections", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "noteplan.chunk_hash_lookup", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "noteplan.meta_submit", 7*time.Millisecond)
	ObserveLatency(phaseCtx, "noteembed.finalize", 8*time.Millisecond)
	AddCount(phaseCtx, "noteembed.reuse_hits", 2)
	ObserveLatency(phaseCtx, "noteembed.finalize.writeback_submit", 8*time.Millisecond)
	ObserveLatency(phaseCtx, "noteembed.finalize.write_chunks", 9*time.Millisecond)
	ObserveLatency(phaseCtx, "noteemb.sync_note_chunks.lookup_note_row", 4*time.Millisecond)
	ObserveLatency(phaseCtx, "noteemb.sync_note_chunks.upsert_cache", 5*time.Millisecond)
	ObserveLatency(phaseCtx, "noteemb.sync_note_chunks.upsert_rows", 6*time.Millisecond)
	ObserveLatency(phaseCtx, "noteemb.sync_note_chunks.delete_stale", 7*time.Millisecond)
	ObserveLatency(phaseCtx, "noteembed.writeback.flush_wait", 10*time.Millisecond)
	ObserveLatency(phaseCtx, "noteplan.writeback.meta.submit_wait", 11*time.Millisecond)
	ObserveLatency(phaseCtx, "noteembed.writeback.chunk.submit_wait", 12*time.Millisecond)
	ObserveLatency(phaseCtx, "noteembed.writeback.intel.submit_wait", 13*time.Millisecond)
	AddCount(phaseCtx, "noteplan.writeback.meta.flush.count", 1)
	AddCount(phaseCtx, "noteembed.writeback.chunk.flush.count", 2)
	AddCount(phaseCtx, "noteembed.writeback.intel.flush.count", 3)
	ObserveSample(phaseCtx, "noteplan.writeback.meta.batch_rows", 14)
	ObserveSample(phaseCtx, "noteembed.writeback.chunk.batch_rows", 15)
	ObserveSample(phaseCtx, "noteembed.writeback.intel.batch_rows", 16)
	ObserveSample(phaseCtx, "noteplan.writeback.meta.batch_bytes", 1024)
	ObserveSample(phaseCtx, "noteembed.writeback.chunk.batch_bytes", 2048)
	ObserveSample(phaseCtx, "noteembed.writeback.intel.batch_bytes", 3072)
	SetGauge(phaseCtx, "noteplan.writeback.meta.queue_depth", 4)
	SetGauge(phaseCtx, "noteembed.writeback.chunk.queue_depth", 5)
	SetGauge(phaseCtx, "noteembed.writeback.intel.queue_depth", 6)
	FromContext(ctx).RecordSpan("embed_notes", 20*time.Millisecond, nil)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "load_doc_sections_cum=5ms")
	require.Contains(t, summary, "chunk_hash_lookup_cum=6ms")
	require.Contains(t, summary, "meta_submit_cum=7ms")
	require.Contains(t, summary, "finalize_cum=8ms")
	require.Contains(t, summary, "reuse_hits=2")
	require.Contains(t, summary, "finalize_writeback_submit_cum=8ms")
	require.Contains(t, summary, "finalize_write_chunks_cum=9ms")
	require.Contains(t, summary, "sync_note_chunks_lookup_note_row_cum=4ms")
	require.Contains(t, summary, "sync_note_chunks_upsert_cache_cum=5ms")
	require.Contains(t, summary, "sync_note_chunks_upsert_rows_cum=6ms")
	require.Contains(t, summary, "sync_note_chunks_delete_stale_cum=7ms")
	require.Contains(t, summary, "writeback_flush_wait_cum=10ms")
	require.Contains(t, summary, "writeback_meta_submit_wait_cum=11ms")
	require.Contains(t, summary, "writeback_note_chunk_submit_wait_cum=12ms")
	require.Contains(t, summary, "writeback_note_intel_submit_wait_cum=13ms")
	require.Contains(t, summary, "writeback_meta_flushes=1")
	require.Contains(t, summary, "writeback_note_chunk_flushes=2")
	require.Contains(t, summary, "writeback_note_intel_flushes=3")
	require.Contains(t, summary, "writeback_meta_queue_depth_peak=4")
	require.Contains(t, summary, "writeback_note_chunk_queue_depth_peak=5")
	require.Contains(t, summary, "writeback_note_intel_queue_depth_peak=6")
}

func TestCollectorRenderSummaryIncludesOntologyFieldRowCounters(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "write_ontology")
	AddCount(phaseCtx, "ontology.delta_rows", 4)
	AddCount(phaseCtx, "ontology.field_rows_planned", 7)
	AddCount(phaseCtx, "ontology.field_rows_written", 6)
	FromContext(ctx).RecordSpan("write_ontology", 10*time.Millisecond, nil)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "write_ontology")
	require.Contains(t, summary, "delta_rows=4")
	require.Contains(t, summary, "field_rows_planned=7")
	require.Contains(t, summary, "field_rows_written=6")
}

func TestCollectorRenderSummaryIncludesCounterOnlyVoyageProviderPhase(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "embed_ontology_nodes")
	AddCount(phaseCtx, "provider.request.voyage", 2)
	AddCount(phaseCtx, "provider.request.voyage.attempt", 3)
	AddCount(phaseCtx, "provider.request.voyage.network_failures", 1)
	AddCount(phaseCtx, "provider.request.voyage.split", 1)
	AddCount(phaseCtx, "provider.request.voyage.completed", 2)
	ObserveLatency(phaseCtx, "provider.request.voyage.backoff", 2*time.Second)
	AddBytes(phaseCtx, "provider.request.voyage.body", 1536)
	ObserveSample(phaseCtx, "provider.request.voyage.inputs", 100)
	ObserveSample(phaseCtx, "provider.request.voyage.status", 429)
	ObserveSample(phaseCtx, "provider.request.voyage.status", 200)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "embed_ontology_nodes")
	require.Contains(t, summary, "unspanned")
	require.Contains(t, summary, "voyage_requests=2")
	require.Contains(t, summary, "voyage_attempts=3")
	require.Contains(t, summary, "voyage_attempts_returned=2")
	require.Contains(t, summary, "voyage_network_failures=1")
	require.Contains(t, summary, "voyage_splits=1")
	require.Contains(t, summary, "voyage_backoff_cum=2.0s")
	require.Contains(t, summary, "voyage_responses=2")
	require.Contains(t, summary, "voyage_status_p50=200")
	require.Contains(t, summary, "voyage_status_p95=429")
	require.Contains(t, summary, "voyage_inputs_max=100")
	require.Contains(t, summary, "voyage_body_bytes=1.5KiB")
}

func TestCollectorRenderWindowIncludesVoyageRequestProgress(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "embed_ontology_nodes")
	AddCount(phaseCtx, "provider.request.voyage", 1)
	AddCount(phaseCtx, "provider.request.voyage.attempt", 2)
	AddCount(phaseCtx, "provider.request.voyage.http_retry", 1)
	AddCount(phaseCtx, "provider.request.voyage.split", 1)
	AddCount(phaseCtx, "provider.request.voyage.completed", 2)
	AddBytes(phaseCtx, "provider.request.voyage.body", 2048)
	ObserveLatency(phaseCtx, "provider.request.voyage.backoff", 3*time.Second)
	ObserveSample(phaseCtx, "provider.request.voyage.inputs", 64)
	ObserveSample(phaseCtx, "provider.request.voyage.status", 429)
	ObserveSample(phaseCtx, "provider.request.voyage.status", 200)

	window := FromContext(ctx).RenderWindow(time.Second)
	require.Contains(t, window, "phase=embed_ontology_nodes")
	require.Contains(t, window, "voyage_requests=1")
	require.Contains(t, window, "voyage_attempts=2")
	require.Contains(t, window, "voyage_attempts_returned=2")
	require.Contains(t, window, "voyage_http_retries=1")
	require.Contains(t, window, "voyage_splits=1")
	require.Contains(t, window, "voyage_backoff_cum_ms=3000")
	require.Contains(t, window, "voyage_responses=2")
	require.Contains(t, window, "voyage_status_p50=200")
	require.Contains(t, window, "voyage_status_p95=429")
	require.Contains(t, window, "voyage_inputs_max=64")
	require.Contains(t, window, "voyage_body_bytes=2.0KiB")
}

func TestCollectorRenderSummarySplitsWriteLockedOpsAndQueueWaitPercentiles(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "index_code")

	ObserveLatency(phaseCtx, "codeindex.file_queue_wait", 10*time.Millisecond)
	ObserveLatency(phaseCtx, "codeindex.file_queue_wait", 30*time.Millisecond)
	ObserveDBWrite(WithOp(phaseCtx, "intel.replace_code_file"), "intel-store", time.Millisecond, 4*time.Millisecond)
	ObserveDBWrite(WithOp(phaseCtx, "auto.anchors.sqlite.CallFilesByCallees"), "intel-store", 0, 3*time.Millisecond)
	FromContext(ctx).RecordSpan("index_code", 50*time.Millisecond, nil)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "file_queue_wait_p50=10ms")
	require.Contains(t, summary, "file_queue_wait_p95=30ms")
	require.Contains(t, summary, "file_queue_wait_max=30ms")
	require.Contains(t, summary, "Write-locked DB ops:")
	require.Contains(t, summary, "- writes:")
	require.Contains(t, summary, "intel.replace_code_file")
	require.Contains(t, summary, "- read-like:")
	require.Contains(t, summary, "auto.anchors.sqlite.CallFilesByCallees")
}

func TestCollectorRenderSummaryAccumulatesRepeatedPhaseSpans(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	phaseCtx := WithPhase(ctx, "rebuild_call_edges")
	ObserveLatency(phaseCtx, "db.hold", 15*time.Millisecond)
	FromContext(ctx).RecordSpan("rebuild_call_edges", 40*time.Millisecond, nil)
	FromContext(ctx).RecordSpan("rebuild_call_edges", 60*time.Millisecond, nil)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "rebuild_call_edges")
	require.Contains(t, summary, "100ms x2")
}

func TestCollectorRenderWindowPrefersProviderActivePhase(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	indexPhase := WithPhase(ctx, "index_code")
	embedPhase := WithPhase(ctx, "embed_code")

	AddCount(indexPhase, "fs.read", 40)
	ObserveLatency(indexPhase, "fs.walk", 123*time.Millisecond)
	ObserveLatency(indexPhase, "db.hold", 8*time.Millisecond)
	AddCount(embedPhase, "provider.calls", 2)
	AddCount(embedPhase, "provider.texts", 32)
	ObserveLatency(embedPhase, "provider.latency", 30*time.Millisecond)

	window := FromContext(ctx).RenderWindow(10 * time.Second)
	lines := strings.Split(window, "\n")
	require.NotEmpty(t, lines)
	require.Contains(t, lines[0], "phase=embed_code")
	require.NotContains(t, lines[0], "walk_cum_ms=123")
}

func TestCollectorRenderWindowCanEmitMultipleActivePhases(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	indexPhase := WithPhase(ctx, "index_code")
	rebuildPhase := WithPhase(ctx, "rebuild_call_edges")

	AddCount(indexPhase, "fs.read", 10)
	SetGauge(indexPhase, "codeindex.file_queue_depth", 7)
	ObserveLatency(indexPhase, "codeindex.file_queue_wait", 20*time.Millisecond)
	AddCount(rebuildPhase, "calledge.flush.count", 1)
	ObserveSample(rebuildPhase, "calledge.flush.paths", 64)
	ObserveLatency(rebuildPhase, "db.hold", 15*time.Millisecond)

	window := FromContext(ctx).RenderWindow(time.Second)
	require.Contains(t, window, "phase=index_code")
	require.Contains(t, window, "file_queue_depth_peak=7")
	require.Contains(t, window, "phase=rebuild_call_edges")
	require.Contains(t, window, "calledge_flushes=1")
}

func TestCollectorRenderWindowIncludesQueueLaneAndCallEdgeStageMetrics(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	indexPhase := WithPhase(ctx, "index_code")
	rebuildPhase := WithPhase(ctx, "rebuild_call_edges")

	AddCount(indexPhase, "fs.read", 1)
	ObserveLatency(indexPhase, "queue.code_wait", 3*time.Millisecond)
	ObserveLatency(indexPhase, "queue.other_wait", 5*time.Millisecond)
	SetGauge(indexPhase, "queue.code_depth", 9)
	SetGauge(indexPhase, "queue.other_depth", 4)

	AddCount(rebuildPhase, "calledge.flush.count", 1)
	ObserveSample(rebuildPhase, "calledge.flush.paths", 8)
	ObserveLatency(rebuildPhase, "db.hold", time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.source_load", 7*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.refs_load", 9*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.anchor_prefetch", 11*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build", 12*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build.fqn_lookup", 19*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build.fqn_lookup.exact", 13*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build.fqn_lookup.suffix", 6*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build.import_lookup", 23*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build.go_method_lookup", 29*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.cache_build.py_fallback_lookup", 31*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.edge_build", 13*time.Millisecond)
	ObserveLatency(rebuildPhase, "calledge.batch_write", 17*time.Millisecond)
	AddCount(rebuildPhase, "calledge.direct_paths", 3)
	AddCount(rebuildPhase, "calledge.planned_paths", 5)
	AddCount(rebuildPhase, "calledge.runtime_paths", 2)
	AddCount(rebuildPhase, "calledge.stored_paths", 3)
	AddCount(rebuildPhase, "calledge.source_fallback.count", 2)
	AddCount(rebuildPhase, "calledge.source_fallback.runtime_missing_refs.count", 1)
	AddCount(rebuildPhase, "calledge.source_fallback.runtime_parse_untrusted.count", 2)
	AddCount(rebuildPhase, "calledge.source_fallback.no_authoritative_inputs.count", 3)
	AddCount(rebuildPhase, "calledge.cache.fqn.entry", 4)
	AddCount(rebuildPhase, "calledge.cache.fqn.hit", 10)
	AddCount(rebuildPhase, "calledge.cache.fqn.miss", 2)
	AddCount(rebuildPhase, "calledge.cache.import.entry", 1)
	AddCount(rebuildPhase, "calledge.cache.import.hit", 3)
	AddCount(rebuildPhase, "calledge.cache.import.miss", 1)
	AddCount(rebuildPhase, "calledge.cache.go_method.entry", 2)
	AddCount(rebuildPhase, "calledge.cache.go_method.hit", 5)
	AddCount(rebuildPhase, "calledge.cache.go_method.miss", 1)
	AddCount(rebuildPhase, "calledge.cache.py_fallback.entry", 1)
	AddCount(rebuildPhase, "calledge.cache.py_fallback.hit", 2)
	AddCount(rebuildPhase, "calledge.cache.py_fallback.miss", 4)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_candidate.count", 12)
	AddCount(rebuildPhase, "calledge.cache_build.import_candidate.count", 5)
	AddCount(rebuildPhase, "calledge.cache_build.go_method_candidate.count", 3)
	AddCount(rebuildPhase, "calledge.cache_build.py_fallback_candidate.count", 7)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_skipped_py_unqualified.count", 11)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.seed.count", 4)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.index_entry.count", 8)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.call_candidate.count", 6)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.typeref_candidate.count", 5)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.memberref_candidate.count", 7)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.candidate.go.count", 2)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.candidate.py.count", 3)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.candidate.cs.count", 4)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.candidate.ts.count", 1)
	AddCount(rebuildPhase, "calledge.cache_build_suffix_skipped.member_ref.count", 7)
	AddCount(rebuildPhase, "calledge.cache_build_suffix_skipped.unqualified_pkg.count", 9)
	AddCount(rebuildPhase, "calledge.cache_build_suffix_skipped.py_fallback_only.count", 2)
	AddCount(rebuildPhase, "calledge.cache_build_suffix_skipped.go_method_only.count", 3)
	AddCount(rebuildPhase, "calledge.cache_build_suffix_skipped.bare_name.count", 4)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.input.count", 20)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.unique.count", 18)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.chunk.count", 4)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.exact_resolved.count", 9)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.suffix_requested.count", 6)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.suffix_resolved.count", 5)

	window := FromContext(ctx).RenderWindow(time.Second)
	require.Contains(t, window, "code_queue_wait_cum_ms=3")
	require.Contains(t, window, "other_queue_wait_cum_ms=5")
	require.Contains(t, window, "code_queue_depth_peak=9")
	require.Contains(t, window, "other_queue_depth_peak=4")
	require.Contains(t, window, "calledge_source_load_cum_ms=7")
	require.Contains(t, window, "calledge_refs_load_cum_ms=9")
	require.Contains(t, window, "calledge_anchor_prefetch_cum_ms=11")
	require.Contains(t, window, "calledge_cache_build_cum_ms=12")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_cum_ms=19")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_exact_cum_ms=13")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_suffix_cum_ms=6")
	require.Contains(t, window, "calledge_cache_build_import_lookup_cum_ms=23")
	require.Contains(t, window, "calledge_cache_build_go_method_lookup_cum_ms=29")
	require.Contains(t, window, "calledge_cache_build_py_fallback_lookup_cum_ms=31")
	require.Contains(t, window, "calledge_edge_build_cum_ms=13")
	require.Contains(t, window, "calledge_batch_write_cum_ms=17")
	require.Contains(t, window, "calledge_direct_paths=3")
	require.Contains(t, window, "calledge_planned_paths=5")
	require.Contains(t, window, "calledge_runtime_paths=2")
	require.Contains(t, window, "calledge_stored_paths=3")
	require.Contains(t, window, "calledge_source_fallbacks=2")
	require.Contains(t, window, "calledge_source_fallback_runtime_missing_refs=1")
	require.Contains(t, window, "calledge_source_fallback_runtime_parse_untrusted=2")
	require.Contains(t, window, "calledge_source_fallback_no_authoritative_inputs=3")
	require.Contains(t, window, "calledge_cache_fqn_entries=4")
	require.Contains(t, window, "calledge_cache_fqn_hits=10")
	require.Contains(t, window, "calledge_cache_fqn_misses=2")
	require.Contains(t, window, "calledge_cache_import_entries=1")
	require.Contains(t, window, "calledge_cache_import_hits=3")
	require.Contains(t, window, "calledge_cache_import_misses=1")
	require.Contains(t, window, "calledge_cache_go_method_entries=2")
	require.Contains(t, window, "calledge_cache_go_method_hits=5")
	require.Contains(t, window, "calledge_cache_go_method_misses=1")
	require.Contains(t, window, "calledge_cache_py_fallback_entries=1")
	require.Contains(t, window, "calledge_cache_py_fallback_hits=2")
	require.Contains(t, window, "calledge_cache_py_fallback_misses=4")
	require.Contains(t, window, "calledge_cache_build_fqn_candidates=12")
	require.Contains(t, window, "calledge_cache_build_import_candidates=5")
	require.Contains(t, window, "calledge_cache_build_go_method_candidates=3")
	require.Contains(t, window, "calledge_cache_build_py_fallback_candidates=7")
	require.Contains(t, window, "calledge_cache_build_fqn_skipped_py_unqualified=11")
	require.Contains(t, window, "calledge_cache_build_suffix_seed_count=4")
	require.Contains(t, window, "calledge_cache_build_suffix_index_entries=8")
	require.Contains(t, window, "calledge_cache_build_suffix_call_candidates=6")
	require.Contains(t, window, "calledge_cache_build_suffix_typeref_candidates=5")
	require.Contains(t, window, "calledge_cache_build_suffix_memberref_candidates=7")
	require.Contains(t, window, "calledge_cache_build_suffix_candidates_go=2")
	require.Contains(t, window, "calledge_cache_build_suffix_candidates_py=3")
	require.Contains(t, window, "calledge_cache_build_suffix_candidates_cs=4")
	require.Contains(t, window, "calledge_cache_build_suffix_candidates_ts=1")
	require.Contains(t, window, "calledge_cache_build_suffix_skipped_member_ref=7")
	require.Contains(t, window, "calledge_cache_build_suffix_skipped_unqualified_pkg=9")
	require.Contains(t, window, "calledge_cache_build_suffix_skipped_py_fallback_only=2")
	require.Contains(t, window, "calledge_cache_build_suffix_skipped_go_method_only=3")
	require.Contains(t, window, "calledge_cache_build_suffix_skipped_bare_name=4")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_inputs=20")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_unique=18")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_chunks=4")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_exact_resolved=9")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_suffix_requested=6")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_suffix_resolved=5")

	FromContext(ctx).RecordSpan("index_code", 25*time.Millisecond, nil)
	FromContext(ctx).RecordSpan("rebuild_call_edges", 30*time.Millisecond, nil)
	FromContext(ctx).RecordSpan("total", 55*time.Millisecond, nil)
	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "code_queue_wait_cum=3ms")
	require.Contains(t, summary, "other_queue_wait_cum=5ms")
	require.Contains(t, summary, "code_queue_depth_peak=9")
	require.Contains(t, summary, "other_queue_depth_peak=4")
	require.Contains(t, summary, "calledge_source_load_cum=7ms")
	require.Contains(t, summary, "calledge_refs_load_cum=9ms")
	require.Contains(t, summary, "calledge_anchor_prefetch_cum=11ms")
	require.Contains(t, summary, "calledge_cache_build_cum=12ms")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_cum=19ms")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_exact_cum=13ms")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_suffix_cum=6ms")
	require.Contains(t, summary, "calledge_cache_build_import_lookup_cum=23ms")
	require.Contains(t, summary, "calledge_cache_build_go_method_lookup_cum=29ms")
	require.Contains(t, summary, "calledge_cache_build_py_fallback_lookup_cum=31ms")
	require.Contains(t, summary, "calledge_edge_build_cum=13ms")
	require.Contains(t, summary, "calledge_batch_write_cum=17ms")
	require.Contains(t, summary, "calledge_direct_paths=3")
	require.Contains(t, summary, "calledge_planned_paths=5")
	require.Contains(t, summary, "calledge_runtime_paths=2")
	require.Contains(t, summary, "calledge_stored_paths=3")
	require.Contains(t, summary, "calledge_source_fallbacks=2")
	require.Contains(t, summary, "calledge_source_fallback_runtime_missing_refs=1")
	require.Contains(t, summary, "calledge_source_fallback_runtime_parse_untrusted=2")
	require.Contains(t, summary, "calledge_source_fallback_no_authoritative_inputs=3")
	require.Contains(t, summary, "calledge_cache_fqn_entries=4")
	require.Contains(t, summary, "calledge_cache_fqn_hits=10")
	require.Contains(t, summary, "calledge_cache_fqn_misses=2")
	require.Contains(t, summary, "calledge_cache_import_entries=1")
	require.Contains(t, summary, "calledge_cache_import_hits=3")
	require.Contains(t, summary, "calledge_cache_import_misses=1")
	require.Contains(t, summary, "calledge_cache_go_method_entries=2")
	require.Contains(t, summary, "calledge_cache_go_method_hits=5")
	require.Contains(t, summary, "calledge_cache_go_method_misses=1")
	require.Contains(t, summary, "calledge_cache_py_fallback_entries=1")
	require.Contains(t, summary, "calledge_cache_py_fallback_hits=2")
	require.Contains(t, summary, "calledge_cache_py_fallback_misses=4")
	require.Contains(t, summary, "calledge_cache_build_fqn_candidates=12")
	require.Contains(t, summary, "calledge_cache_build_import_candidates=5")
	require.Contains(t, summary, "calledge_cache_build_go_method_candidates=3")
	require.Contains(t, summary, "calledge_cache_build_py_fallback_candidates=7")
	require.Contains(t, summary, "calledge_cache_build_fqn_skipped_py_unqualified=11")
	require.Contains(t, summary, "calledge_cache_build_suffix_seed_count=4")
	require.Contains(t, summary, "calledge_cache_build_suffix_index_entries=8")
	require.Contains(t, summary, "calledge_cache_build_suffix_call_candidates=6")
	require.Contains(t, summary, "calledge_cache_build_suffix_typeref_candidates=5")
	require.Contains(t, summary, "calledge_cache_build_suffix_memberref_candidates=7")
	require.Contains(t, summary, "calledge_cache_build_suffix_candidates_go=2")
	require.Contains(t, summary, "calledge_cache_build_suffix_candidates_py=3")
	require.Contains(t, summary, "calledge_cache_build_suffix_candidates_cs=4")
	require.Contains(t, summary, "calledge_cache_build_suffix_candidates_ts=1")
	require.Contains(t, summary, "calledge_cache_build_suffix_skipped_member_ref=7")
	require.Contains(t, summary, "calledge_cache_build_suffix_skipped_unqualified_pkg=9")
	require.Contains(t, summary, "calledge_cache_build_suffix_skipped_py_fallback_only=2")
	require.Contains(t, summary, "calledge_cache_build_suffix_skipped_go_method_only=3")
	require.Contains(t, summary, "calledge_cache_build_suffix_skipped_bare_name=4")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_inputs=20")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_unique=18")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_chunks=4")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_exact_resolved=9")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_suffix_requested=6")
	require.Contains(t, summary, "calledge_cache_build_fqn_lookup_suffix_resolved=5")
}

func TestCollectorRenderWindowIncludesCounterOnlyCallEdgePhase(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	rebuildPhase := WithPhase(ctx, "rebuild_call_edges")

	AddCount(rebuildPhase, "calledge.cache_build_suffix.seed.count", 2)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.index_entry.count", 1)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.call_candidate.count", 1)
	AddCount(rebuildPhase, "calledge.cache_build_suffix.candidate.py.count", 1)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.suffix_requested.count", 1)
	AddCount(rebuildPhase, "calledge.cache_build.fqn_lookup.suffix_resolved.count", 1)

	window := FromContext(ctx).RenderWindow(time.Second)
	require.Contains(t, window, "calledge_cache_build_suffix_seed_count=2")
	require.Contains(t, window, "calledge_cache_build_suffix_index_entries=1")
	require.Contains(t, window, "calledge_cache_build_suffix_call_candidates=1")
	require.Contains(t, window, "calledge_cache_build_suffix_candidates_py=1")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_suffix_requested=1")
	require.Contains(t, window, "calledge_cache_build_fqn_lookup_suffix_resolved=1")
}

func unlabeledDBWrite(ctx context.Context) {
	ObserveDBWrite(ctx, "intel-store", time.Millisecond, 2*time.Millisecond)
}

func TestObserveDBWriteInfersCallerOpWhenMissing(t *testing.T) {
	t.Parallel()

	ctx := WithCollector(context.Background(), New())
	unlabeledDBWrite(ctx)

	summary := FromContext(ctx).RenderSummary()
	require.Contains(t, summary, "auto.indexingperf.unlabeledDBWrite")
	require.NotContains(t, summary, "unknown")
}
