package indexingperf

// These ordered tables keep window and cumulative reports on the same metric
// names and output labels. Detail counters do not independently activate a window.

var callEdgeLatencyMetrics = [...]latencyReportMetric{
	{name: "calledge.source_load", label: "calledge_source_load"},
	{name: "calledge.refs_load", label: "calledge_refs_load"},
	{name: "calledge.anchor_prefetch", label: "calledge_anchor_prefetch"},
	{name: "calledge.cache_build", label: "calledge_cache_build"},
	{name: "calledge.cache_build.fqn_lookup", label: "calledge_cache_build_fqn_lookup"},
	{name: "calledge.cache_build.fqn_lookup.exact", label: "calledge_cache_build_fqn_lookup_exact"},
	{name: "calledge.cache_build.fqn_lookup.suffix", label: "calledge_cache_build_fqn_lookup_suffix"},
	{name: "calledge.cache_build.import_lookup", label: "calledge_cache_build_import_lookup"},
	{name: "calledge.cache_build.go_method_lookup", label: "calledge_cache_build_go_method_lookup"},
	{name: "calledge.cache_build.py_fallback_lookup", label: "calledge_cache_build_py_fallback_lookup"},
	{name: "calledge.edge_build", label: "calledge_edge_build"},
	{name: "calledge.batch_write", label: "calledge_batch_write"},
}

var callEdgeCounterMetrics = [...]counterReportMetric{
	{name: "calledge.direct_paths", label: "calledge_direct_paths"},
	{name: "calledge.planned_paths", label: "calledge_planned_paths"},
	{name: "calledge.runtime_paths", label: "calledge_runtime_paths"},
	{name: "calledge.stored_paths", label: "calledge_stored_paths"},
	{name: "calledge.source_fallback.count", label: "calledge_source_fallbacks"},
	{name: "calledge.source_fallback.runtime_missing_refs.count", label: "calledge_source_fallback_runtime_missing_refs"},
	{name: "calledge.source_fallback.runtime_parse_untrusted.count", label: "calledge_source_fallback_runtime_parse_untrusted"},
	{name: "calledge.source_fallback.no_authoritative_inputs.count", label: "calledge_source_fallback_no_authoritative_inputs"},
	{name: "calledge.cache.fqn.entry", label: "calledge_cache_fqn_entries"},
	{name: "calledge.cache.fqn.hit", label: "calledge_cache_fqn_hits"},
	{name: "calledge.cache.fqn.miss", label: "calledge_cache_fqn_misses"},
	{name: "calledge.cache.import.entry", label: "calledge_cache_import_entries"},
	{name: "calledge.cache.import.hit", label: "calledge_cache_import_hits"},
	{name: "calledge.cache.import.miss", label: "calledge_cache_import_misses"},
	{name: "calledge.cache.go_method.entry", label: "calledge_cache_go_method_entries"},
	{name: "calledge.cache.go_method.hit", label: "calledge_cache_go_method_hits"},
	{name: "calledge.cache.go_method.miss", label: "calledge_cache_go_method_misses"},
	{name: "calledge.cache.py_fallback.entry", label: "calledge_cache_py_fallback_entries"},
	{name: "calledge.cache.py_fallback.hit", label: "calledge_cache_py_fallback_hits"},
	{name: "calledge.cache.py_fallback.miss", label: "calledge_cache_py_fallback_misses"},
	{name: "calledge.cache_build.fqn_candidate.count", label: "calledge_cache_build_fqn_candidates"},
	{name: "calledge.cache_build.import_candidate.count", label: "calledge_cache_build_import_candidates"},
	{name: "calledge.cache_build.go_method_candidate.count", label: "calledge_cache_build_go_method_candidates"},
	{name: "calledge.cache_build.py_fallback_candidate.count", label: "calledge_cache_build_py_fallback_candidates"},
	{name: "calledge.cache_build.fqn_skipped_py_unqualified.count", label: "calledge_cache_build_fqn_skipped_py_unqualified"},
	{name: "calledge.cache_build_suffix.seed.count", label: "calledge_cache_build_suffix_seed_count"},
	{name: "calledge.cache_build_suffix.index_entry.count", label: "calledge_cache_build_suffix_index_entries"},
	{name: "calledge.cache_build_suffix.call_candidate.count", label: "calledge_cache_build_suffix_call_candidates"},
	{name: "calledge.cache_build_suffix.typeref_candidate.count", label: "calledge_cache_build_suffix_typeref_candidates"},
	{name: "calledge.cache_build_suffix.memberref_candidate.count", label: "calledge_cache_build_suffix_memberref_candidates"},
	{name: "calledge.cache_build_suffix.candidate.go.count", label: "calledge_cache_build_suffix_candidates_go"},
	{name: "calledge.cache_build_suffix.candidate.py.count", label: "calledge_cache_build_suffix_candidates_py"},
	{name: "calledge.cache_build_suffix.candidate.cs.count", label: "calledge_cache_build_suffix_candidates_cs"},
	{name: "calledge.cache_build_suffix.candidate.ts.count", label: "calledge_cache_build_suffix_candidates_ts"},
	{name: "calledge.cache_build_suffix_skipped.member_ref.count", label: "calledge_cache_build_suffix_skipped_member_ref"},
	{name: "calledge.cache_build_suffix_skipped.unqualified_pkg.count", label: "calledge_cache_build_suffix_skipped_unqualified_pkg"},
	{name: "calledge.cache_build_suffix_skipped.py_fallback_only.count", label: "calledge_cache_build_suffix_skipped_py_fallback_only"},
	{name: "calledge.cache_build_suffix_skipped.go_method_only.count", label: "calledge_cache_build_suffix_skipped_go_method_only"},
	{name: "calledge.cache_build_suffix_skipped.bare_name.count", label: "calledge_cache_build_suffix_skipped_bare_name"},
}

var callEdgeLookupCounterMetrics = [...]counterReportMetric{
	{name: "calledge.cache_build.fqn_lookup.input.count", label: "calledge_cache_build_fqn_lookup_inputs"},
	{name: "calledge.cache_build.fqn_lookup.unique.count", label: "calledge_cache_build_fqn_lookup_unique"},
	{name: "calledge.cache_build.fqn_lookup.chunk.count", label: "calledge_cache_build_fqn_lookup_chunks"},
	{name: "calledge.cache_build.fqn_lookup.exact_resolved.count", label: "calledge_cache_build_fqn_lookup_exact_resolved"},
	{name: "calledge.cache_build.fqn_lookup.suffix_requested.count", label: "calledge_cache_build_fqn_lookup_suffix_requested"},
	{name: "calledge.cache_build.fqn_lookup.suffix_resolved.count", label: "calledge_cache_build_fqn_lookup_suffix_resolved"},
}

var codeIndexLatencyMetrics = [...]latencyReportMetric{
	{name: "codeindex.file_queue_wait", label: "file_queue_wait", percentiles: true},
	{name: "codeindex.file_enqueue_wait", label: "file_enqueue_wait", percentiles: true},
	{name: "codeindex.result_submit_wait", label: "result_submit", percentiles: true},
	{name: "codeindex.result_reduce", label: "result_reduce", percentiles: true},
	{name: "codeindex.result_reduce_indexed", label: "result_reduce_indexed"},
	{name: "codeindex.result_reduce_touched", label: "result_reduce_touched"},
	{name: "codeindex.result_reduce_changed_callers", label: "result_reduce_changed_callers"},
	{name: "codeindex.result_reduce_defdeltas", label: "result_reduce_defdeltas"},
	{name: "codeindex.result_finalize", label: "result_finalize", percentiles: true},
	{name: "codeindex.semantic_submit_wait", label: "semantic_submit", percentiles: true},
	{name: "codeindex.write_submit_wait", label: "write_submit", percentiles: true},
	{name: "codeindex.write_drain_wait", label: "write_drain"},
	{name: "codeindex.write_flush_wait", label: "write_flush"},
	{name: "codeindex.semantic_drain_wait", label: "semantic_drain"},
	{name: "codeindex.worker_service", label: "worker_service", percentiles: true},
	{name: "codeindex.worker_build", label: "worker_build", percentiles: true},
	{name: "codeindex.worker_submit_local", label: "worker_submit_local", percentiles: true},
	{name: "codeindex.worker_submit_semantic", label: "worker_submit_semantic", percentiles: true},
	{name: "codeindex.worker_submit_write", label: "worker_submit_write", percentiles: true},
	{name: "codeindex.worker_submit", label: "worker_submit", percentiles: true},
	{name: "codeindex.worker_total", label: "worker_total", percentiles: true},
}

var planningLatencyMetrics = [...]latencyReportMetric{
	{name: "codeembed.hash_prefetch", label: "hash_prefetch"},
	{name: "plan.load_anchor_meta", label: "load_anchor_meta"},
	{name: "plan.load_anchors", label: "load_anchors"},
	{name: "plan.load_anchors_by_path", label: "load_anchors_by_path"},
	{name: "plan.list_items", label: "list_items"},
	{name: "plan.item_embedding_states", label: "item_embedding_states"},
	{name: "plan.call_lookup_files", label: "call_lookup_files"},
	{name: "plan.call_lookup_owners", label: "call_lookup_owners"},
	{name: "noteplan.load_doc_section_meta", label: "load_doc_section_meta"},
	{name: "noteplan.load_doc_sections", label: "load_doc_sections"},
	{name: "noteplan.load_doc_sections_by_path", label: "load_doc_sections_by_path"},
	{name: "noteplan.load_titles", label: "load_titles"},
	{name: "noteplan.chunk_hashes_batch", label: "chunk_hashes_batch"},
	{name: "noteplan.chunk_hash_lookup", label: "chunk_hash_lookup"},
	{name: "noteplan.build_chunks", label: "build_chunks"},
	{name: "noteplan.plan_chunk_updates", label: "plan_chunk_updates"},
	{name: "noteplan.load_stored_chunks", label: "load_stored_chunks"},
	{name: "noteplan.cache_lookup", label: "cache_lookup"},
	{name: "noteplan.meta_submit", label: "meta_submit"},
	{name: "noteplan.meta_flush_wait", label: "meta_flush_wait"},
}

var noteFinalizeLatencyMetrics = [...]latencyReportMetric{
	{name: "noteembed.finalize.writeback_submit", label: "finalize_writeback_submit"},
	{name: "noteembed.finalize.write_chunks", label: "finalize_write_chunks"},
	{name: "noteembed.finalize.write_intel", label: "finalize_write_intel"},
	{name: "noteembed.finalize.cleanup", label: "finalize_cleanup"},
	{name: "noteemb.sync_note_chunks.lookup_note_row", label: "sync_note_chunks_lookup_note_row"},
	{name: "noteemb.sync_note_chunks.upsert_cache", label: "sync_note_chunks_upsert_cache"},
	{name: "noteemb.sync_note_chunks.upsert_rows", label: "sync_note_chunks_upsert_rows"},
	{name: "noteemb.sync_note_chunks.delete_stale", label: "sync_note_chunks_delete_stale"},
	{name: "noteembed.writeback.flush_wait", label: "writeback_flush_wait"},
}

var codeStageLatencyMetrics = [...]latencyReportMetric{
	{name: "codeindex.parse", label: "parse"},
	{name: "codeindex.hashcheck", label: "hashcheck"},
	{name: "codeindex.normalize", label: "normalize"},
	{name: "codeindex.intel", label: "intel"},
	{name: "codeindex.rationale", label: "rationale"},
	{name: "codeindex.doclinks", label: "doclinks"},
	{name: "codeindex.refs", label: "refs"},
	{name: "codeindex.defdeltas", label: "defdeltas"},
	{name: "process.code", label: "process"},
}

var codePersistLatencyMetrics = [...]latencyReportMetric{
	{name: "codepersist.apply", label: "persist_apply"},
	{name: "codepersist.summary_meta", label: "persist_summary_meta"},
	{name: "codepersist.doclinks", label: "persist_doclinks"},
	{name: "codepersist.sqlite_batch", label: "persist_sqlite_batch"},
	{name: "codepersist.refs", label: "persist_refs"},
	{name: "codepersist.intel", label: "persist_intel"},
	{name: "codepersist.rationale", label: "persist_rationale"},
	{name: "codepersist.writer_apply", label: "writer_apply"},
	{name: "codepersist.writer_after", label: "writer_after"},
}
