// Package ignore provides gitignore-style pattern matching for vault file exclusion.
//
// Docs: [Ignore + exclude rules](docs/reference/guides/Ignore + exclude rules.md)
package ignore

import (
	"path"
	"strings"

	"github.com/atomicobject/rhizome/pkg/paths"
)

// SystemContextFilename is Rhizome's exact, case-sensitive repository context
// convention.
const SystemContextFilename = "CONTEXT.md"

var defaultIgnorePatterns = []string{
	".git/",
	".github/",
	".idea/",
	".vscode/",
	".cursor/",
	".codex/",
	".cache/",
	".claude/",
	".DS_Store",
	".gitignore-d",
	"node_modules/",
	"vendor/",
	"dist/",
	"build/",
	"out/",
	"tmp/",
	"temp/",
	"venv/",
	".venv/",
	".pytest_cache/",
	".mypy_cache/",
	".ruff_cache/",
	"__pycache__/",
	"coverage/",
	"coverage.out",
	"target/",
	"bin/",
}

// DefaultIgnorePatterns returns a copy of the built-in ignore prefixes.
func DefaultIgnorePatterns() []string {
	out := make([]string, len(defaultIgnorePatterns))
	copy(out, defaultIgnorePatterns)
	return out
}

// DefaultIgnoreDirnames returns default ignore directory names derived from patterns.
func DefaultIgnoreDirnames() []string {
	patterns := DefaultIgnorePatterns()
	out := make([]string, 0, len(patterns))
	seen := map[string]struct{}{}
	for _, pattern := range patterns {
		pattern = strings.TrimSpace(pattern)
		if pattern == "" || !strings.HasSuffix(pattern, "/") {
			continue
		}
		name := strings.TrimSuffix(pattern, "/")
		name = strings.Trim(name, "/")
		if name == "" {
			continue
		}
		if strings.Contains(name, "/") {
			name = path.Base(name)
		}
		if name == "" {
			continue
		}
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		out = append(out, name)
	}
	return out
}

// IsSystemContextPath reports whether relPath names Rhizome's exact,
// case-sensitive repository context convention.
func IsSystemContextPath(relPath string) bool {
	relPath = paths.Normalize(strings.TrimSpace(relPath)).String()
	return relPath != "" && path.Base(relPath) == SystemContextFilename
}

// IsDefaultInfrastructurePath reports whether a path crosses one of Rhizome's
// built-in infrastructure directory boundaries.
func IsDefaultInfrastructurePath(relPath string) bool {
	ignored := make(map[string]struct{})
	for _, name := range DefaultIgnoreDirnames() {
		ignored[name] = struct{}{}
	}
	parts := strings.Split(paths.Normalize(strings.TrimSpace(relPath)).String(), "/")
	for _, part := range parts[:max(0, len(parts)-1)] {
		if _, ok := ignored[part]; ok {
			return true
		}
	}
	return false
}

// DefaultIgnoreFile renders a .rhizome/ignore body using the default patterns.
func DefaultIgnoreFile() string {
	var b strings.Builder
	b.WriteString("# Default .rhizome/ignore generated by rhizome\n")
	b.WriteString("# Remove entries you want to include in indexing/search\n")
	b.WriteString("# To override an ignore from .gitignore, add negations like:\n")
	b.WriteString("#   !some/dir/\n")
	b.WriteString("# Hidden entries (e.g., .git) are ignored automatically\n")
	for _, p := range defaultIgnorePatterns {
		b.WriteString(p)
		if !strings.HasSuffix(p, "\n") {
			b.WriteString("\n")
		}
	}
	return b.String()
}
