// `cjs:<package>` modules are generated by vite.kit.config.ts.
declare module "cjs:react" {
  export * from "react";
  export { default } from "react";
}

declare module "cjs:react/jsx-runtime" {
  export * from "react/jsx-runtime";
  const runtime: typeof import("react/jsx-runtime");
  export default runtime;
}

declare module "cjs:react-dom" {
  export * from "react-dom";
  export { default } from "react-dom";
}

declare module "cjs:react-dom/client" {
  export * from "react-dom/client";
  const client: typeof import("react-dom/client");
  export default client;
}
