import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { Profiler } from "react";
import { describe, expect, it, vi } from "vitest";

import { jsonReply, withFakeFetch } from "../test/fakeFetch";
import { HTMLNoteViewer } from "./HTMLNoteViewer";

const http = withFakeFetch();

const session = {
  id: "viewer-1",
  url: "https://viewer-1.content.example.test/reports/prototype.html?mode=demo#chart",
  nonce: "nonce-1",
  expiresAt: "2030-01-01T00:00:00Z",
};

type ViewerMessagePayload = {
  target?: string;
  resolved?: string;
  beside?: boolean;
  filename?: string;
  mediaType?: string;
  size?: number;
  encoding?: string;
  data?: ArrayBuffer;
};

function viewerMessage(
  type: string,
  payload: ViewerMessagePayload = {},
  requestId = `${session.id}:1`,
) {
  return {
    version: 1,
    nonce: session.nonce,
    viewerId: session.id,
    notePath: "reports/prototype.html",
    requestId,
    type,
    ...payload,
  };
}

function viewerFrame(): HTMLIFrameElement {
  const frame = document.querySelector<HTMLIFrameElement>("iframe.html-note-viewer__frame");

  if (!frame) throw new Error("HTML viewer frame was not rendered");

  return frame;
}

function configureHTTP() {
  http.on("POST", "/api/v1/html-viewers", () => jsonReply(session, 201));
  http.on(
    "DELETE",
    `/api/v1/html-viewers/${session.id}`,
    () => new Response(null, { status: 204 }),
  );
}

describe("HTMLNoteViewer", () => {
  it("keeps one sandboxed frame mounted across Read and Source", async () => {
    configureHTTP();

    const props = {
      path: "reports/prototype.html",
      query: "mode=demo",
      fragment: "chart",
      applicationHref: "/notes?note=reports%2Fprototype.html",
      onNavigate: vi.fn(),
    };

    const view = render(<HTMLNoteViewer {...props} visible />);
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    expect(frame).toHaveAttribute("sandbox", "allow-scripts");
    expect(frame).toHaveAttribute("referrerpolicy", "no-referrer");

    view.rerender(<HTMLNoteViewer {...props} visible={false} />);
    expect(screen.getByTitle("Interactive HTML note: reports/prototype.html")).toBe(frame);
    expect(frame).toHaveAttribute("hidden");
    expect(http.count("POST", "/api/v1/html-viewers")).toBe(1);
  });

  it("requires a parent click before saving generated bytes", async () => {
    configureHTTP();
    const createObjectURL = vi.fn((_object: Blob) => "blob:parent-owned");
    const revokeObjectURL = vi.fn();
    vi.stubGlobal("URL", Object.assign(URL, { createObjectURL, revokeObjectURL }));
    const anchorClick = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});

    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={vi.fn()}
      />,
    );
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    fireEvent(
      window,
      new MessageEvent("message", {
        source: frame.contentWindow,
        data: viewerMessage("ready"),
      }),
    );
    await waitFor(() => expect(screen.queryByText("Loading prototype…")).not.toBeInTheDocument());
    const bytes = new TextEncoder().encode("a,b\n1,2\n").buffer;

    const message = new MessageEvent("message", {
      source: frame.contentWindow,
      data: viewerMessage("download", {
        filename: "../report.csv",
        mediaType: "text/csv",
        size: bytes.byteLength,
        encoding: "arrayBuffer",
        data: bytes,
      }),
    });

    expect(message.source).toBe(frame.contentWindow);
    fireEvent(window, message);

    expect(await screen.findByText("report.csv · 8 B")).toBeInTheDocument();
    expect(createObjectURL).not.toHaveBeenCalled();
    expect(anchorClick).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole("button", { name: "Download" }));
    await waitFor(() => expect(createObjectURL).toHaveBeenCalledOnce());
    expect(anchorClick).toHaveBeenCalledOnce();
    const downloaded = createObjectURL.mock.calls[0]?.[0];
    expect(downloaded).toBeInstanceOf(Blob);
    // SAFETY: the assertion immediately above verifies the recorded argument is a Blob.
    await expect((downloaded as Blob).arrayBuffer()).resolves.toEqual(bytes);
  });

  it("passes both authored and resolved navigation through the validated bridge", async () => {
    configureHTTP();
    const onNavigate = vi.fn();
    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={onNavigate}
      />,
    );
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    fireEvent(
      window,
      new MessageEvent("message", {
        source: frame.contentWindow,
        data: viewerMessage("navigate", {
          target: "../status#results",
          resolved: "https://viewer-1.content.example.test/status.html#results",
          beside: true,
        }),
      }),
    );

    expect(onNavigate).toHaveBeenCalledWith("status.html#results", true, "../status#results");
  });

  it("handles navigation as soon as the frame is committed", async () => {
    configureHTTP();
    const onNavigate = vi.fn();
    render(
      <Profiler
        id="viewer"
        onRender={() => {
          const frame = document.querySelector<HTMLIFrameElement>("iframe.html-note-viewer__frame");

          if (!frame) return;
          window.dispatchEvent(
            new MessageEvent("message", {
              source: frame.contentWindow,
              data: viewerMessage("navigate", {
                target: "../status#results",
                resolved: "https://viewer-1.content.example.test/status.html#results",
                beside: true,
              }),
            }),
          );
        }}
      >
        <HTMLNoteViewer
          path="reports/prototype.html"
          visible
          applicationHref="/notes?note=reports%2Fprototype.html"
          onNavigate={onNavigate}
        />
      </Profiler>,
    );
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    expect(onNavigate).toHaveBeenCalledExactlyOnceWith(
      "status.html#results",
      true,
      "../status#results",
    );
  });

  it("surfaces a precise backend error when the viewer cannot be created", async () => {
    http.on("POST", "/api/v1/html-viewers", () =>
      jsonReply({ error: "HTML note is not currently admitted", code: "NOT_ADMITTED" }, 404),
    );

    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={vi.fn()}
      />,
    );

    expect(await screen.findByRole("alert")).toHaveTextContent(
      "HTML note is not currently admitted",
    );
  });

  it("shows an error when the iframe fails to load", async () => {
    configureHTTP();
    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={vi.fn()}
      />,
    );

    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    fireEvent(frame, new Event("error"));
    expect(await screen.findByRole("alert")).toHaveTextContent(
      "HTML viewer could not load its content",
    );

    fireEvent.click(screen.getByRole("button", { name: "Refresh" }));
    await waitFor(() => expect(viewerFrame()).not.toBe(frame));
    expect(screen.queryByRole("alert")).not.toBeInTheDocument();
    fireEvent(frame, new Event("error"));
    expect(screen.queryByRole("alert")).not.toBeInTheDocument();

    fireEvent(viewerFrame(), new Event("error"));
    expect(await screen.findByRole("alert")).toHaveTextContent(
      "HTML viewer could not load its content",
    );
  });

  it("shows an error when the iframe never completes its readiness handshake", async () => {
    vi.useFakeTimers();

    try {
      configureHTTP();
      render(
        <HTMLNoteViewer
          path="reports/prototype.html"
          visible
          applicationHref="/notes?note=reports%2Fprototype.html"
          onNavigate={vi.fn()}
        />,
      );
      await act(async () => {
        await Promise.resolve();
        await Promise.resolve();
        await Promise.resolve();
      });
      expect(
        screen.getByTitle("Interactive HTML note: reports/prototype.html"),
      ).toBeInTheDocument();

      await act(async () => {
        await vi.advanceTimersByTimeAsync(10_001);
      });
      expect(screen.getByRole("alert")).toHaveTextContent(
        "HTML viewer did not become ready before the request timed out",
      );
    } finally {
      vi.useRealTimers();
    }
  });

  it("ignores forged bridge messages before checking the download prompt", async () => {
    configureHTTP();
    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={vi.fn()}
      />,
    );
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    const bytes = new TextEncoder().encode("csv").buffer;

    const valid = viewerMessage("download", {
      filename: "report.csv",
      mediaType: "text/csv",
      size: bytes.byteLength,
      encoding: "arrayBuffer",
      data: bytes,
    });

    fireEvent(
      window,
      new MessageEvent("message", {
        source: frame.contentWindow,
        origin: "https://attacker.example.test",
        data: valid,
      }),
    );
    fireEvent(
      window,
      new MessageEvent("message", { source: frame.contentWindow, data: { ...valid, extra: true } }),
    );
    fireEvent(
      window,
      new MessageEvent("message", {
        source: frame.contentWindow,
        data: { ...valid, nonce: "forged" },
      }),
    );

    expect(screen.queryByText("report.csv · 3 B")).not.toBeInTheDocument();
  });

  it("accepts one download request ID only once", async () => {
    configureHTTP();
    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={vi.fn()}
      />,
    );
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    const bytes = new TextEncoder().encode("csv").buffer;

    const message = viewerMessage("download", {
      filename: "report.csv",
      mediaType: "text/csv",
      size: bytes.byteLength,
      encoding: "arrayBuffer",
      data: bytes,
    });

    fireEvent(window, new MessageEvent("message", { source: frame.contentWindow, data: message }));
    expect(await screen.findByText("report.csv · 3 B")).toBeInTheDocument();
    expect(screen.getAllByRole("button", { name: "Download" })).toHaveLength(1);
    fireEvent.click(screen.getByRole("button", { name: "Cancel" }));
    expect(screen.queryByText("report.csv · 3 B")).not.toBeInTheDocument();

    fireEvent(window, new MessageEvent("message", { source: frame.contentWindow, data: message }));
    expect(screen.queryByText("report.csv · 3 B")).not.toBeInTheDocument();

    fireEvent(
      window,
      new MessageEvent("message", {
        source: frame.contentWindow,
        data: { ...message, requestId: `${session.id}:2` },
      }),
    );
    expect(await screen.findByText("report.csv · 3 B")).toBeInTheDocument();
  });

  it("rate limits downloads after four accepted requests in the window", async () => {
    configureHTTP();
    render(
      <HTMLNoteViewer
        path="reports/prototype.html"
        visible
        applicationHref="/notes?note=reports%2Fprototype.html"
        onNavigate={vi.fn()}
      />,
    );
    await screen.findByTitle("Interactive HTML note: reports/prototype.html");
    const frame = viewerFrame();
    const bytes = new TextEncoder().encode("csv").buffer;

    for (let index = 1; index <= 4; index += 1) {
      fireEvent(
        window,
        new MessageEvent("message", {
          source: frame.contentWindow,
          data: viewerMessage(
            "download",
            {
              filename: `report-${index}.csv`,
              mediaType: "text/csv",
              size: bytes.byteLength,
              encoding: "arrayBuffer",
              data: bytes,
            },
            `${session.id}:${index}`,
          ),
        }),
      );
      expect(
        await screen.findByText(`report-${index}.csv · 3 B`, undefined, { timeout: 3_000 }),
      ).toBeInTheDocument();
      fireEvent.click(screen.getByRole("button", { name: "Cancel" }));
    }

    fireEvent(
      window,
      new MessageEvent("message", {
        source: frame.contentWindow,
        data: viewerMessage(
          "download",
          {
            filename: "report-5.csv",
            mediaType: "text/csv",
            size: bytes.byteLength,
            encoding: "arrayBuffer",
            data: bytes,
          },
          `${session.id}:5`,
        ),
      }),
    );

    expect(screen.queryByText("report-5.csv · 3 B")).not.toBeInTheDocument();
  });

  it("opens the chrome-free note route in a new tab and links back from bare mode", () => {
    configureHTTP();

    const props = {
      path: "reports/prototype.html",
      applicationHref: "/notes?note=reports%2Fprototype.html#chart",
      onNavigate: vi.fn(),
    };

    const view = render(<HTMLNoteViewer {...props} visible />);
    expect(screen.getByRole("link", { name: "Open in browser tab" })).toHaveAttribute(
      "href",
      "/notes?note=reports%2Fprototype.html&bare=1#chart",
    );

    view.rerender(<HTMLNoteViewer {...props} visible bare />);
    expect(screen.queryByRole("link", { name: "Open in browser tab" })).not.toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Open in Rhizome" })).toHaveAttribute(
      "href",
      props.applicationHref,
    );
  });
});
